Repository mui/toolpad, pull requests merged in 2022-11, with the labels that each got.

#1229 Support duplicating queries
  packages/toolpad-app/src/components/SystemDialogs.tsx
  packages/toolpad-app/src/theme.ts
  packages/toolpad-app/src/toolpad/AppEditor/HierarchyExplorer/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/NodeMenu.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/QueryEditor.tsx
Labels: feature: Queries

#1257 Fix app templates tests
  test/integration/appTemplates.spec.ts
Labels: test, core, bug 🐛, dx

#1232 Improve dev mode performance
  .eslintrc.js
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-core/package.json
  packages/toolpad-core/src/index.tsx
  packages/toolpad-core/src/runtime.tsx
Labels: core

#1264 Provide accessible locators
  test/integration/appTemplates.spec.ts
Labels: test, enhancement

#1256 Fix Elastic Search configuration
  packages/toolpad-app/src/server/config.ts
  packages/toolpad-app/src/server/logs/logger.ts
Labels: core, bug 🐛

#1265 Release v0.0.25
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
Labels: core

#1234 Add Link Component
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentCatalog/ComponentCatalogItem.tsx
  packages/toolpad-app/src/toolpadComponents/index.tsx
  packages/toolpad-components/src/Link.tsx
  packages/toolpad-components/src/index.tsx
Labels: new feature

#1266 Undo redo fix proposal
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/toolpad/DomLoader.tsx
Labels: bug 🐛, feature: App Editor

#1267 Index pino logs to data stream
  packages/toolpad-app/src/server/logs/logger.ts
Labels: core

#1269 useEvent: Only check for calls during render in development
  packages/toolpad-app/src/utils/useEvent.ts
Labels: enhancement

#1225 Add undo & redo functionality
  packages/toolpad-app/src/toolpad/AppEditor/AppEditorShell.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/EditorCanvasHost.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/RenderOverlay.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/index.tsx
  packages/toolpad-app/src/toolpad/DomLoader.tsx
  packages/toolpad-app/src/utils/fields.ts
  packages/toolpad-app/src/utils/useShortcut.ts
Labels: feature: App Editor

#1279 [docs] Link changelog
  README.md
Labels: docs

#1284 Small improvements to Datagrid component
  packages/toolpad-components/src/DataGrid.tsx
Labels: enhancement

#1276 Add Next.js bundle analyzer
  packages/toolpad-app/next.config.mjs
  packages/toolpad-app/package.json
  yarn.lock
Labels: core

#1283 Update code component name on save
  packages/toolpad-app/src/appDom/index.ts
  packages/toolpad-app/src/toolpad/AppEditor/CodeComponentEditor/index.tsx
Labels: design: ui

#1295 [core] Add OSSF Scorecard action
  .github/workflows/scorecards.yml
Labels: core, security

#1301 Reduce amount of chunks for the runtime
  packages/toolpad-app/src/runtime/loadModule.tsx
  packages/toolpad-app/src/runtime/muiExports.tsx
Labels: core

#1305 Add prefix to custom GA event
  packages/toolpad-app/src/utils/ga.ts
Labels: core

#1302 Remove react from the runtime chunk
  packages/toolpad-app/src/runtime/loadModule.tsx
  packages/toolpad-app/src/runtime/muiExports.tsx
Labels: core

#1299 Upgrade monorepo dependency
  yarn.lock
Labels: docs

#1306 Make sure to define a _jsxFilename for custom components
  packages/toolpad-app/src/runtime/AppModulesProvider.tsx
  packages/toolpad-app/src/runtime/loadCodeComponent.tsx
  packages/toolpad-app/src/runtime/loadModule.tsx
  packages/toolpad-app/src/toolpad/AppEditor/CodeComponentEditor/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/CodeComponentEditor/useCodeComponent.tsx
Labels: core

#1282 Fix adding parameter with duplicate name
  packages/toolpad-app/src/appDom/index.ts
  packages/toolpad-app/src/appDom/migrations/v3.ts
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/QueryEditor.tsx
  packages/toolpad-app/src/toolpadDataSources/function/client.tsx
  packages/toolpad-app/src/toolpadDataSources/googleSheets/client.tsx
  packages/toolpad-app/src/toolpadDataSources/movies/client.tsx
  packages/toolpad-app/src/toolpadDataSources/postgres/client.tsx
  packages/toolpad-app/src/toolpadDataSources/rest/client.tsx
  packages/toolpad-app/src/types.ts
Labels: design: ui, feature: Queries

#1315 Remove pullRequestPreviewsEnabled from render.yml
  render.yaml
Labels: core, bug 🐛

#1318 v0.0.26
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
Labels: core

#1314 Change dots to ellipsis
  packages/toolpad-app/src/toolpad/AppEditor/AppEditorShell.tsx
  packages/toolpad-app/src/toolpadDataSources/googleSheets/client.tsx
Labels: design: ui

#1317 Show creation dialog as loading while navigating to newly created app
  packages/toolpad-app/src/toolpad/Home/index.tsx
Labels: design: ui

#1316 Remove package.json resolutions field
  package.json
  yarn.lock
Labels: core

#1322 Reorganize QueryEditor into its own folder
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/QueryEditor/QueryEditorDialog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/QueryEditor/index.tsx
Labels: core

#1329 Fix hud overlay index
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/NodeHud.tsx
Labels: bug 🐛, feature: App Editor

#1328 Fix undo/redo race condition
  packages/toolpad-app/src/toolpad/DomLoader.tsx
Labels: feature: App Editor

#1281 Simplify menu actions
  packages/toolpad-app/src/toolpad/AppEditor/HierarchyExplorer/CreateCodeComponentNodeDialog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/HierarchyExplorer/CreateConnectionNodeDialog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/HierarchyExplorer/CreatePageNodeDialog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/HierarchyExplorer/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/NodeMenu.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/QueryEditor/QueryEditorDialog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/QueryEditor/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/NodeHud.tsx
  packages/toolpad-app/src/toolpad/Home/index.tsx
  test/integration/duplication/index.spec.ts
  test/integration/editor/index.spec.ts
  test/models/ToolpadEditor.ts
  test/models/ToolpadHome.ts
Labels: design: ux, enhancement

#1331 [docs] Fix path typo in Fetch docs
  docs/data/toolpad/connecting-to-datasources/fetch.md
Labels: docs

#1274 Fix windows and AZERTY shortcuts for undo redo
  packages/toolpad-app/src/toolpad/AppEditor/BindingEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/CodeComponentEditor/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/EditorCanvasHost.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/PageModuleEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/index.tsx
  packages/toolpad-app/src/toolpad/DomLoader.tsx
  packages/toolpad-app/src/toolpad/propertyControls/json.tsx
  packages/toolpad-app/src/toolpadDataSources/function/client.tsx
  packages/toolpad-app/src/utils/useShortcut.ts
Labels: bug 🐛, feature: App Editor

#1342 Add github repository link from landing page
  docs/pages/toolpad/index.js
Labels: website

#1307 Convert scripts to ESM
  package.json
  scripts/deduplicate.js
  scripts/deduplicate.mjs
  scripts/jsonlint.js
  scripts/jsonlint.mjs
  scripts/releaseChangelog.js
  scripts/releaseChangelog.mjs
  yarn.lock
Labels: core

#1343 Remove externalResolver for Sentry
  packages/toolpad-app/pages/api/data/[appId]/[version]/[queryId].ts
  packages/toolpad-app/pages/api/dataSources/[dataSource]/[...path].ts
  packages/toolpad-app/pages/api/health-check.ts
  packages/toolpad-app/pages/api/rpc.ts
Labels: core

#1332 Move component compilation serverside
  packages/toolpad-app/pages/app/[appId]/[version]/[[...path]].tsx
  packages/toolpad-app/pages/deploy/[appId]/[[...path]].tsx
  packages/toolpad-app/src/canvas/index.tsx
  packages/toolpad-app/src/createRuntimeState.tsx
  packages/toolpad-app/src/runtime/AppModulesProvider.tsx
  packages/toolpad-app/src/runtime/ToolpadApp.spec.tsx
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/runtime/loadCodeComponent.tsx
  packages/toolpad-app/src/runtime/loadModule.tsx
  packages/toolpad-app/src/server/data.ts
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/EditorCanvasHost.tsx
  packages/toolpad-app/src/types.ts
Labels: core

#1294 Upgrade to next 13
  package.json
  packages/toolpad-app/middleware.ts
  packages/toolpad-app/next.config.mjs
  packages/toolpad-app/package.json
  packages/toolpad-app/src/components/Link.tsx
  packages/toolpad-app/src/server/getLatestRelease.ts
  renovate.json
  test/models/ToolpadHome.ts
  yarn.lock
Labels: core

#1348 Make sure code components can run against React in production mode
  packages/toolpad-app/src/createRuntimeState.tsx
Labels: core, bug 🐛, regression

#1344 Make sure to show a 404 for non existing apps in the preview
  packages/toolpad-app/pages/app/[appId]/[version]/[[...path]].tsx
  packages/toolpad-app/src/server/data.ts
Labels: core

#1351 Automatic app names in demo
  packages/toolpad-app/src/server/data.ts
  packages/toolpad-app/src/toolpad/Home/index.tsx
Labels: core, enhancement

#1355 Fix prettier script in CI
  .circleci/config.yml
Labels: core

#1350 Show IP address in log messages
  packages/toolpad-app/src/server/logs/logInfo.ts
  packages/toolpad-app/src/server/logs/logSerializers.ts
  packages/toolpad-app/src/server/logs/logger.ts
  packages/toolpad-app/src/server/logs/withLogs.ts
Labels: core, enhancement

#1325 Run functions client side
  packages/toolpad-app/src/appDom/index.ts
  packages/toolpad-app/src/compileModule.ts
  packages/toolpad-app/src/components/FlexFill.tsx
  packages/toolpad-app/src/createRuntimeState.tsx
  packages/toolpad-app/src/runtime/loadCodeComponent.tsx
  packages/toolpad-app/src/toolpadDataSources/QueryInputPanel.tsx
  packages/toolpad-app/src/toolpadDataSources/function/client.tsx
  packages/toolpad-app/src/toolpadDataSources/function/runtime.tsx
  packages/toolpad-app/src/toolpadDataSources/function/types.ts
  packages/toolpad-app/src/toolpadDataSources/runtime.tsx
Labels: feature: Queries

#1357 Refactor overview page
  packages/toolpad-app/pages/index.tsx
  packages/toolpad-app/src/constants.ts
  packages/toolpad-app/src/toolpad/Apps/index.tsx
  packages/toolpad-app/src/toolpad/Toolpad.tsx
  packages/toolpad-app/src/toolpad/ToolpadHomeShell.tsx
  packages/toolpad-app/src/toolpad/ToolpadShell/DemoBar.tsx
  packages/toolpad-app/src/toolpad/ToolpadShell/index.tsx
Labels: design: ui

#1272 Fallback to visible captcha if invisible captcha fails
  packages/toolpad-app/pages/_app.tsx
  packages/toolpad-app/pages/api/rpc.ts
  packages/toolpad-app/sentry.client.config.js
  packages/toolpad-app/sentry.server.config.js
  packages/toolpad-app/src/api.ts
  packages/toolpad-app/src/config.ts
  packages/toolpad-app/src/errorCodes.ts
  packages/toolpad-app/src/server/config.ts
  packages/toolpad-app/src/server/data.ts
  packages/toolpad-app/src/server/logs/logInfo.ts
  packages/toolpad-app/src/server/logs/logSerializers.ts
  packages/toolpad-app/src/server/logs/logger.ts
  packages/toolpad-app/src/server/logs/withLogs.ts
  packages/toolpad-app/src/server/validateRecaptchaToken.ts
  packages/toolpad-app/src/storageKeys.ts
  packages/toolpad-app/src/toolpad/Apps/index.tsx
  packages/toolpad-app/src/types.ts
  packages/toolpad-app/src/utils/types.ts
Labels: core

#1287 Upgrade eslint
  package.json
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  renovate.json
  yarn.lock
Labels: core

#1341 [core] Group renovate GitHub Action dependency updates
  renovate.json
Labels: core, dependencies

#1361 Remove sentry debug option
  packages/toolpad-app/sentry.client.config.js
  packages/toolpad-app/sentry.server.config.js
Labels: core

#1366 Move typescript to devDependencies
  packages/toolpad-app/package.json
Labels: core

#1368 Remove demo configuration from render.yaml
  render.yaml
Labels: core

#1369 Remove demo docker
  docker/images/toolpad-demo/Dockerfile
Labels: core

#1360 Fix next regression that broke sucrase
  packages/toolpad-app/package.json
  test/integration/components/componentsDom.json
  test/integration/components/index.spec.ts
  yarn.lock
Labels: core, bug 🐛, regression

#1356 Add "alpha" label to app and landing page hero
  docs/src/components/landing/Hero.js
  packages/toolpad-app/src/toolpad/ToolpadShell/Header/index.tsx
Labels: design: ui, website

#1372 Fix overflow for explorer
  packages/toolpad-app/src/toolpad/AppEditor/HierarchyExplorer/index.tsx
Labels: design: ui

#1375 Fix landing page hydration issue
  docs/src/components/landing/Hero.js
Labels: website

#1378 v0.0.28
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
Labels: core

#1286 Unify app editor options menus
  packages/toolpad-app/src/errorCodes.ts
  packages/toolpad-app/src/server/data.ts
  packages/toolpad-app/src/toolpad/AppEditor/PagePanel.tsx
  packages/toolpad-app/src/toolpad/AppOptions/AppDeleteDialog.tsx
  packages/toolpad-app/src/toolpad/AppOptions/AppDuplicateDialog.tsx
  packages/toolpad-app/src/toolpad/AppOptions/AppExportDialog.tsx
  packages/toolpad-app/src/toolpad/AppOptions/AppNameEditable.tsx
  packages/toolpad-app/src/toolpad/AppOptions/AppSettingsDialog.tsx
  packages/toolpad-app/src/toolpad/AppOptions/index.tsx
  packages/toolpad-app/src/toolpad/Apps/index.tsx
  test/integration/appRename.spec.ts
  test/models/ToolpadHome.ts
Labels: design: ui, design: ux

#1323 Set connection/query available options in demo
  packages/toolpad-app/src/constants.ts
  packages/toolpad-app/src/server/appTemplateDoms/doms.ts
  packages/toolpad-app/src/server/appTemplateDoms/images-demo.json
  packages/toolpad-app/src/server/appTemplateDoms/statistics-demo.json
  packages/toolpad-app/src/toolpad/AppEditor/ConnectionEditor/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/HierarchyExplorer/CreateConnectionNodeDialog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ConnectionSelect.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/QueryEditor/QueryEditorDialog.tsx
  packages/toolpad-app/src/toolpad/ToolpadShell/DemoBar.tsx
  packages/toolpad-app/src/toolpadDataSources/QueryInputPanel.tsx
  packages/toolpad-app/src/toolpadDataSources/client.tsx
  packages/toolpad-app/src/toolpadDataSources/function/client.tsx
  packages/toolpad-app/src/toolpadDataSources/function/server.ts
  packages/toolpad-app/src/toolpadDataSources/movies/client.tsx
  packages/toolpad-app/src/toolpadDataSources/movies/server.ts
  packages/toolpad-app/src/toolpadDataSources/movies/types.ts
  packages/toolpad-app/src/toolpadDataSources/rest/client.tsx
  packages/toolpad-app/src/toolpadDataSources/rest/demoBaseUrls.ts
  packages/toolpad-app/src/toolpadDataSources/rest/server.ts
  packages/toolpad-app/src/toolpadDataSources/rest/shared.ts
  packages/toolpad-app/src/toolpadDataSources/server.ts
  packages/toolpad-app/src/types.ts
Labels: core, enhancement

#1384 Create apps programmatically in integration tests
  packages/toolpad-app/src/api.ts
  packages/toolpad-app/src/rpcClient.ts
  test/integration/appDuplicate.spec.ts
  test/integration/components/index.spec.ts
  test/integration/duplication/index.spec.ts
  test/integration/editor/index.spec.ts
  test/integration/function-basic/index.spec.ts
  test/integration/large-dom/index.spec.ts
  test/integration/propControls/index.spec.ts
  test/integration/rest-basic/index.spec.ts
  test/integration/runtime-basic/index.spec.ts
  test/models/ToolpadRuntime.ts
  test/playwright/test.ts
  test/utils/fetchPolyfill.ts
Labels: test

#1393 Hide connections tree in demo
  packages/toolpad-app/src/toolpad/AppEditor/HierarchyExplorer/index.tsx
Labels: core

#1308 Undo redo tests
  packages/toolpad-app/src/toolpad/AppEditor/AppEditorShell.tsx
  test/integration/editor/index.spec.ts
  test/integration/undo-redo/dom.json
  test/integration/undo-redo/index.spec.ts
  test/models/ToolpadEditor.ts
Labels: core

#1396 Release v0.0.29
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
Labels: core

#1394 Undoable/redoable node selection
  packages/toolpad-app/src/toolpad/AppEditor/BindingEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/CodeComponentEditor/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/ConnectionEditor/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/HierarchyExplorer/CreateCodeComponentNodeDialog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/HierarchyExplorer/CreateConnectionNodeDialog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/HierarchyExplorer/CreatePageNodeDialog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/HierarchyExplorer/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/NodeMenu.tsx
  packages/toolpad-app/src/toolpad/AppEditor/NodeNameEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentCatalog/ComponentCatalog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ConnectionSelect.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/PageEditorProvider.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/PageModuleEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/PageOptionsPanel.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/QueryEditor/QueryEditorDialog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/QueryEditor/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/NodeDropArea.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/NodeHud.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/RenderOverlay.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/RenderPanel.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ThemeEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/UrlQueryEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PagePanel.tsx
  packages/toolpad-app/src/toolpad/AppEditor/index.tsx
  packages/toolpad-app/src/toolpad/DomLoader.tsx
Labels: core, enhancement
