Repository mui/toolpad, pull requests merged in 2022-09, with the labels that each got.

#809 [website] Landing page
  .eslintrc.js
  README.md
  docs/data/toolpad/getting-started/tutorial.md
  docs/next.config.js
  docs/pages/toolpad/index.js
  docs/public/static/branding/pricing/block-blue.svg
  docs/public/static/branding/pricing/block-gold.svg
  docs/public/static/branding/pricing/block-green.svg
  docs/public/static/branding/pricing/no-dark.svg
  docs/public/static/branding/pricing/no-light.svg
  docs/public/static/branding/pricing/time-dark.svg
  docs/public/static/branding/pricing/time-light.svg
  docs/public/static/branding/pricing/yes-dark.svg
  docs/public/static/branding/pricing/yes-light.svg
  docs/public/static/branding/product-toolpad-dark.svg
  docs/public/static/branding/product-toolpad-light.svg
  docs/public/static/toolpad/docs/add-textfield.png
  docs/public/static/toolpad/docs/apps-overview.png
  docs/public/static/toolpad/docs/bind-query-state.png
  docs/public/static/toolpad/docs/create-api.png
  docs/public/static/toolpad/docs/create-connection.png
  docs/public/static/toolpad/docs/create-state.png
  docs/public/static/toolpad/docs/editor-overview.png
  docs/public/static/toolpad/docs/page-editor.png
  docs/public/static/toolpad/docs/release.png
  docs/public/static/toolpad/docs/result.png
  docs/public/static/toolpad/docs/updated-binding.png
  docs/public/static/toolpad/marketing/hero-screenshot.png
  docs/public/static/toolpad/marketing/hero-video.mp4
  docs/public/static/toolpad/marketing/toolpad-admin-panel.svg
  docs/public/static/toolpad/marketing/toolpad-custom-cms.svg
  docs/public/static/toolpad/marketing/toolpad-monitoring-dashboard.svg
  docs/src/components/landing/Banner.js
  docs/src/components/landing/CardGrid.js
  docs/src/components/landing/DemoVideo.js
  docs/src/components/landing/Hero.js
  docs/src/components/landing/Marquee.js
  docs/src/components/landing/PricingTable.js
  docs/src/components/landing/SignUp.js
  docs/src/components/landing/SignUpToast.js
  docs/src/components/landing/ToolpadHero.js
  docs/src/content/features.js
  docs/src/content/marquee.js
  docs/src/content/pricing.js
  docs/src/content/upvote.js
  docs/src/content/useCases.js
  docs/src/layouts/ToolpadHeroContainer.tsx
  docs/src/route.ts
  yarn.lock
Labels: website

#888 [website] Fix logo dimension
  docs/src/components/landing/Hero.js
Labels: bug 🐛, website

#891 [core] Update monorepo
  .eslintignore
  yarn.lock
Labels: core, website

#892 [website] Improve video poster
  docs/public/static/toolpad/marketing/hero-screenshot.png
  docs/public/static/toolpad/marketing/index-admin-panel.svg
  docs/public/static/toolpad/marketing/index-custom-cms.svg
  docs/public/static/toolpad/marketing/index-hero-video-poster.jpg
  docs/public/static/toolpad/marketing/index-hero-video.mp4
  docs/public/static/toolpad/marketing/index-monitoring-dashboard.svg
  docs/src/components/landing/DemoVideo.js
  docs/src/content/useCases.js
Labels: performance, website

#890 [core] Add release step for the docs
  CONTRIBUTING.md
Labels: core

#906 [website] Landing Page follow up
  docs/src/components/landing/Banner.js
  docs/src/content/features.js
Labels: website

#889 [core] Fix markdown format
  .github/PULL_REQUEST_TEMPLATE.md
Labels: core

#1011 [docs] Add Building UI documentation
  docs/data/pages.ts
  docs/data/toolpad/building-ui/canvas-and-inspector.md
  docs/data/toolpad/building-ui/component-library.md
  docs/data/toolpad/building-ui/custom-components.md
  docs/pages/toolpad/building-ui/canvas-and-inspector.js
  docs/pages/toolpad/building-ui/component-library.js
  docs/pages/toolpad/building-ui/custom-components.js
  docs/public/static/toolpad/docs/canvas-columns.png
  docs/public/static/toolpad/docs/canvas-grid.png
  docs/public/static/toolpad/docs/canvas-move.png
  docs/public/static/toolpad/docs/canvas-rows.png
  docs/public/static/toolpad/docs/canvas-selected.png
  docs/public/static/toolpad/docs/component-library.png
  docs/public/static/toolpad/docs/custom-component-1.png
  docs/public/static/toolpad/docs/custom-component-2.png
  docs/public/static/toolpad/docs/custom-component-3.png
  docs/public/static/toolpad/docs/inspector.png
  docs/public/static/toolpad/docs/sx-editor.png
  docs/public/static/toolpad/docs/sx.png
Labels: docs

#1012 [docs] Link the docs in the README.md
  README.md
Labels: docs

#1013 [security] Improve the HTTP headers for security
  docs/public/_headers
  packages/toolpad-app/next.config.mjs
Labels: security

#866 [core] Fix scroll restoration in the docs
  docs/next.config.js
  docs/package.json
  yarn.lock
Labels: core, docs

#1030 [Docs] Documentation docker
  docs/data/pages.ts
  docs/data/toolpad/building-ui/canvas-and-inspector.md
  docs/data/toolpad/getting-started/installation.md
  docs/pages/toolpad/getting-started/installation.js
  docs/src/route.ts
Labels: docs

#1042 [core] Improve Windows compatibility
  packages/toolpad-app/next.config.mjs
Labels: core, bug 🐛

#1053 [docs] Disable todo pages in docs
  docs/data/pages.ts
Labels: docs
