Repository mui/toolpad, pull requests merged in 2022-08, with the labels that each got.

#700 Make DataTable vertically resizeable
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/NodeHud.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel.tsx
  packages/toolpad-components/src/DataGrid.tsx
  packages/toolpad-core/src/types.ts
Labels: new feature

#729 Add RFC template
  .github/ISSUE_TEMPLATE/3.rfc.yml
Labels: core, RFC

#788 Fix scrollbar when selection options
  packages/toolpad-app/src/toolpad/propertyControls/SelectOptions.tsx
Labels: bug 🐛, design: ui

#811 Create postgres dataSource prototype
  packages/toolpad-app/package.json
  packages/toolpad-app/src/components/MonacoEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/QueryEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/useEvaluateLiveBinding.ts
  packages/toolpad-app/src/toolpadDataSources/client.tsx
  packages/toolpad-app/src/toolpadDataSources/function/client.tsx
  packages/toolpad-app/src/toolpadDataSources/googleSheets/client.tsx
  packages/toolpad-app/src/toolpadDataSources/movies/client.tsx
  packages/toolpad-app/src/toolpadDataSources/postgres/client.tsx
  packages/toolpad-app/src/toolpadDataSources/postgres/server.ts
  packages/toolpad-app/src/toolpadDataSources/postgres/types.ts
  packages/toolpad-app/src/toolpadDataSources/rest/client.tsx
  packages/toolpad-app/src/toolpadDataSources/server.ts
  packages/toolpad-app/src/toolpadDataSources/useFetchPrivate.ts
  packages/toolpad-app/src/toolpadDataSources/useQueryPreview.ts
  packages/toolpad-app/src/types.ts
  packages/toolpad-components/src/DataGrid.tsx
  packages/toolpad-components/src/index.tsx
  packages/toolpad-core/src/types.ts
  yarn.lock
Labels: feature: Connections

#842 Fix missing key warning
  .circleci/config.yml
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentCatalog.tsx
  packages/toolpad-app/src/toolpad/Home.tsx
  test/integration/appRename.spec.ts
  test/integration/smoke.spec.ts
  test/playwright/test.ts
Labels: bug 🐛, regression

#865 Improved and updated tutorial.md
  docs/data/toolpad/getting-started/tutorial.md
Labels: docs
