Repository mui/toolpad, pull requests merged in 2022-10, with the labels that each got.

#1046 [core] Remove outdated docsearch.js dependency
  docs/package.json
  yarn.lock
Labels: core

#1081 [core] Don't build on render for docs changes
  render.yaml
Labels: core, docs

#1085 [core] Fix buildFilter property in render.yml
  render.yaml
Labels: core

#1098 [core] x10 speedup of yarn install in the CI
  .circleci/config.yml
Labels: test, core

#857 Avoid state update during layout effect in NoSsr
  packages/toolpad-app/src/components/NoSsr.tsx
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/toolpad/Toolpad.tsx
  packages/toolpad-app/src/utils/lazyComponent.tsx
Labels: new feature

#1109 [core] Remove jsdoc eslint
  .eslintrc.js
  package.json
  yarn.lock
Labels: core

#1138 Make sure parameters work in query preview
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/MutationEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/QueryEditor.tsx
  packages/toolpad-app/src/types.ts
Labels: priority: important, regression

#1154 Fix visible horizontal scroll
  packages/toolpad-app/src/toolpad/ToolpadShell/index.tsx
Labels: design: ui

#1153 Improve preview feedback in fetch query
  packages/toolpad-app/src/toolpadDataSources/rest/client.tsx
Labels: feature: Queries

#1159 [docs] Improve markdownlint
  .markdownlint-cli2.cjs
  .markdownlint.jsonc
  .markdownlintignore
  package.json
  packages/toolpad-app/NOTES.md
  yarn.lock
Labels: docs

#1161 [core] Harden GitHub Actions permissions
  .github/workflows/maintenance.yml
  .github/workflows/mark-duplicate.yml
  .github/workflows/no-response.yml
  .github/workflows/release-docker.yml
Labels: core, security

#1151 [core] eslint: Disallow enum
  .eslintrc.js
  package.json
  packages/toolpad-app/src/toolpadDataSources/googleSheets/client.tsx
  packages/toolpad-app/src/toolpadDataSources/googleSheets/server.ts
  packages/toolpad-app/src/toolpadDataSources/googleSheets/types.ts
  yarn.lock
Labels: core

#1149 Disable queries until dom node has been saved serverside
  packages/toolpad-app/src/canvas/index.tsx
  packages/toolpad-app/src/runtime/AppContext.tsx
  packages/toolpad-app/src/runtime/CanvasHooksContext.tsx
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/runtime/useDataQuery.ts
  packages/toolpad-app/src/server/handleDataRequest.ts
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/EditorCanvasHost.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/RenderPanel.tsx
  packages/toolpad-app/src/toolpad/DomLoader.tsx
  packages/toolpad-core/src/index.tsx
Labels: core

#1003 [ui] New component catalog
  packages/toolpad-app/src/runtime/ComponentsContext.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentCatalog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentCatalog/ComponentCatalog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentCatalog/ComponentCatalogItem.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentCatalog/index.tsx
  packages/toolpad-app/src/toolpadComponents/index.tsx
  test/integration/editor/index.spec.ts
Labels: design: ui, design: ux

#988 [ui] Add branding theme to Toolpad app
  packages/toolpad-app/pages/_app.tsx
  packages/toolpad-app/pages/_document.tsx
  packages/toolpad-app/src/ThemeContext.tsx
  packages/toolpad-app/src/components/Console.tsx
  packages/toolpad-app/src/components/HarViewer.tsx
  packages/toolpad-app/src/components/JsonView.tsx
  packages/toolpad-app/src/components/MonacoEditor.tsx
  packages/toolpad-app/src/components/SystemDialogs.tsx
  packages/toolpad-app/src/inspectorTheme.ts
  packages/toolpad-app/src/monacoEditorTheme.ts
  packages/toolpad-app/src/theme.ts
  packages/toolpad-app/src/toolpad/AppEditor/AppEditorShell.tsx
  packages/toolpad-app/src/toolpad/AppEditor/HierarchyExplorer/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/PageModuleEditor.tsx
  packages/toolpad-app/src/toolpad/Home/index.tsx
  packages/toolpad-app/src/toolpad/ToolpadShell/Header/ThemeModeMenu.tsx
  packages/toolpad-app/src/toolpad/ToolpadShell/Header/UserFeedback/index.tsx
  packages/toolpad-app/src/toolpad/ToolpadShell/Header/index.tsx
Labels: design: ui

#1162 Allow iframes
  package.json
  packages/toolpad-app/next.config.mjs
  packages/toolpad-app/pages/deploy/[appId]/[[...path]].tsx
  test/integration/deploy.spec.ts
Labels: new feature

#908 Bug template: Move reproduction above current behavior
  .github/ISSUE_TEMPLATE/1.bug.yml
Labels: core

#1182 Release v0.0.23
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
Labels: core

#1181 [ui] Some tweaks to the Monaco editor theme
  packages/toolpad-app/src/components/MonacoEditor.tsx
Labels: enhancement

#1180 Allow typing event arguments for autocomplete
  packages/toolpad-app/src/components/Console.tsx
  packages/toolpad-app/src/components/JsonView.tsx
  packages/toolpad-app/src/components/MonacoEditor.tsx
  packages/toolpad-app/src/components/ObjectInspector.tsx
  packages/toolpad-app/src/inspectorTheme.ts
  packages/toolpad-app/src/toolpad/AppEditor/BindingEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/ElementContext.tsx
  packages/toolpad-app/src/toolpad/AppEditor/GlobalScopeExplorer.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/JsExpressionEditor.tsx
  packages/toolpad-app/src/utils/types.ts
  packages/toolpad-components/src/DataGrid.tsx
  packages/toolpad-core/src/types.ts
Labels: core

#1167 Add a staleTime to queries
  packages/toolpad-app/package.json
  packages/toolpad-app/src/appDom/index.ts
  packages/toolpad-app/src/canvas/index.tsx
  packages/toolpad-app/src/runtime/CanvasHooksContext.tsx
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/runtime/useDataQuery.ts
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/EditorCanvasHost.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/QueryEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/RenderPanel.tsx
  packages/toolpad-app/src/toolpad/DomLoader.tsx
  packages/toolpad-app/src/types.ts
  packages/toolpad-app/src/utils/insecureHash.ts
  packages/toolpad-app/src/utils/useBoolean.ts
  yarn.lock
Labels: enhancement

#1092 Set up demo with Docker
  docker/images/toolpad-demo/Dockerfile
  packages/toolpad-app/next.config.mjs
  packages/toolpad-app/src/config.ts
  packages/toolpad-app/src/server/data.ts
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ConnectionSelect.tsx
  packages/toolpad-app/src/toolpad/Home/index.tsx
  packages/toolpad-app/src/toolpad/ToolpadShell/Header/index.tsx
  packages/toolpad-app/src/toolpadDataSources/client.tsx
  packages/toolpad-app/src/toolpadDataSources/rest/client.tsx
  packages/toolpad-app/src/toolpadDataSources/rest/server.ts
  packages/toolpad-app/src/toolpadDataSources/server.ts
  render.yaml
Labels: docs

#1169 Implement component duplication logic
  packages/toolpad-app/src/appDom/index.ts
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/NodeHud.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/RenderOverlay.tsx
  packages/toolpad-app/src/toolpad/DomLoader.tsx
Labels: new feature, feature: App Editor

#1189 Remove branch option from database in render.yaml
  render.yaml
Labels: bug 🐛

#1187 Add option to DataGrid to hide toolbar
  packages/toolpad-components/src/DataGrid.tsx
Labels: feature: App Editor, enhancement

#1197 [core] Add code scanning via CodeQL
  .github/workflows/codeql.yml
Labels: core, security

#1165 Fix fetch query preview
  packages/toolpad-app/src/components/JsonView.tsx
  packages/toolpad-app/src/toolpadDataSources/rest/client.tsx
Labels: bug 🐛, feature: Connections

#1202 Part 2: Update queries docs
  docs/data/toolpad/connecting-to-datasources/queries.md
  docs/public/static/toolpad/docs/queries/query-1.png
  docs/public/static/toolpad/docs/queries/query-2.png
  docs/public/static/toolpad/docs/queries/query-3.png
  docs/public/static/toolpad/docs/query-1.png
  docs/public/static/toolpad/docs/query-2.png
  docs/public/static/toolpad/docs/query-3.png
Labels: docs

#1199 [core] Harden the datasource handler implementation
  packages/toolpad-app/pages/api/dataSources/[dataSource]/[...path].ts
Labels: core, security

#1156 Option to send logs to Elastic Cloud Search
  packages/toolpad-app/package.json
  packages/toolpad-app/pages/api/data/[appId]/[version]/[queryId].ts
  packages/toolpad-app/pages/api/dataSources/[dataSource]/[...path].ts
  packages/toolpad-app/pages/api/rpc.ts
  packages/toolpad-app/src/server/config.ts
  packages/toolpad-app/src/server/logSerializers.ts
  packages/toolpad-app/src/server/logger.ts
  packages/toolpad-app/src/server/withLogs.ts
  packages/toolpad-app/src/server/withReqResLogs.ts
  packages/toolpad-app/src/utils/crypto.ts
  packages/toolpad-app/src/utils/uuid.ts
  yarn.lock
Labels: new feature

#1195 Log captcha validations
  packages/toolpad-app/pages/api/data/[appId]/[version]/[queryId].ts
  packages/toolpad-app/pages/api/dataSources/[dataSource]/[...path].ts
  packages/toolpad-app/pages/api/rpc.ts
  packages/toolpad-app/src/server/config.ts
  packages/toolpad-app/src/server/logs/logInfo.ts
  packages/toolpad-app/src/server/logs/logSerializers.ts
  packages/toolpad-app/src/server/logs/logger.ts
  packages/toolpad-app/src/server/logs/withLogs.ts
  packages/toolpad-app/src/server/validateRecaptchaToken.ts
Labels: core, PR: out-of-date

#1194 [core] Relax the restrictions on node naming
  packages/toolpad-app/src/appDom/index.ts
  packages/toolpad-app/src/toolpad/AppEditor/HierarchyExplorer/CreateCodeComponentNodeDialog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/HierarchyExplorer/CreateConnectionNodeDialog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/HierarchyExplorer/CreatePageNodeDialog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/HierarchyExplorer/validation.ts
  packages/toolpad-app/src/toolpad/AppEditor/NodeNameEditor.tsx
  packages/toolpad-app/src/toolpad/DomLoader.tsx
  packages/toolpad-app/src/utils/useEvent.ts
Labels: feature: App Editor, enhancement

#1191 Use public environment settings for demo
  render.yaml
Labels: core

#1200 Part 1: Update overview + quickstart screenshots
  docs/data/toolpad/getting-started/overview.md
  docs/data/toolpad/getting-started/quickstart.md
  docs/public/static/toolpad/docs/deploy-1.png
  docs/public/static/toolpad/docs/deploy-2.png
  docs/public/static/toolpad/docs/overview/main.png
  docs/public/static/toolpad/docs/quickstart/apps-overview.png
  docs/public/static/toolpad/docs/quickstart/deploy-1.png
  docs/public/static/toolpad/docs/quickstart/deploy-2.png
  docs/public/static/toolpad/docs/quickstart/step-1.png
  docs/public/static/toolpad/docs/quickstart/step-10.png
  docs/public/static/toolpad/docs/quickstart/step-11.png
  docs/public/static/toolpad/docs/quickstart/step-12.png
  docs/public/static/toolpad/docs/quickstart/step-13.png
  docs/public/static/toolpad/docs/quickstart/step-2.png
  docs/public/static/toolpad/docs/quickstart/step-3.png
  docs/public/static/toolpad/docs/quickstart/step-4.png
  docs/public/static/toolpad/docs/quickstart/step-5.png
  docs/public/static/toolpad/docs/quickstart/step-6.png
  docs/public/static/toolpad/docs/quickstart/step-7.png
  docs/public/static/toolpad/docs/quickstart/step-8.png
  docs/public/static/toolpad/docs/quickstart/step-9.png
  docs/public/static/toolpad/docs/step-1.png
  docs/public/static/toolpad/docs/step-10.png
  docs/public/static/toolpad/docs/step-11.png
  docs/public/static/toolpad/docs/step-12.png
  docs/public/static/toolpad/docs/step-13.png
  docs/public/static/toolpad/docs/step-2.png
  docs/public/static/toolpad/docs/step-3.png
  docs/public/static/toolpad/docs/step-4.png
  docs/public/static/toolpad/docs/step-5.png
  docs/public/static/toolpad/docs/step-6.png
  docs/public/static/toolpad/docs/step-7.png
  docs/public/static/toolpad/docs/step-8.png
  docs/public/static/toolpad/docs/step-9.png
  docs/public/static/toolpad/docs/terminology.png
Labels: docs

#1203 Part 3: Update connections docs
  docs/data/toolpad/connecting-to-datasources/connections.md
  docs/public/static/toolpad/docs/connection-fetch-1.png
  docs/public/static/toolpad/docs/connection-function-1.png
  docs/public/static/toolpad/docs/connection-function-2.png
  docs/public/static/toolpad/docs/connection-postgres-1.png
  docs/public/static/toolpad/docs/connection-sheets-1.png
  docs/public/static/toolpad/docs/connection-sheets-2.png
  docs/public/static/toolpad/docs/connection.png
  docs/public/static/toolpad/docs/connections/fetch-1.png
  docs/public/static/toolpad/docs/connections/function-1.png
  docs/public/static/toolpad/docs/connections/function-2.png
  docs/public/static/toolpad/docs/connections/new.png
  docs/public/static/toolpad/docs/connections/postgres-1.png
  docs/public/static/toolpad/docs/connections/sheets-1.png
  docs/public/static/toolpad/docs/connections/sheets-2.png
Labels: docs

#1207 [core] query editor, only insert node after the flow
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/QueryEditor.tsx
Labels: core

#1186 [website] Remove LanguageNegotation
  docs/pages/_app.js
Labels: website

#1188 Deploy with keyboard enter
  packages/toolpad-app/src/components/DialogForm.tsx
  packages/toolpad-app/src/toolpad/AppEditor/AppEditorShell.tsx
  packages/toolpad-app/src/toolpad/AppEditor/HierarchyExplorer/CreateCodeComponentNodeDialog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/HierarchyExplorer/CreateConnectionNodeDialog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/HierarchyExplorer/CreatePageNodeDialog.tsx
  packages/toolpad-app/src/toolpad/Home/index.tsx
Labels: enhancement

#1031 Improve Paper component
  packages/toolpad-app/src/canvas/getPageViewState.ts
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/RenderOverlay.tsx
  packages/toolpad-components/src/PageRow.tsx
  packages/toolpad-components/src/Paper.tsx
  packages/toolpad-core/src/runtime.tsx
  packages/toolpad-core/src/types.ts
Labels: enhancement

#1066 Add API and datasource logging
  packages/toolpad-app/package.json
  packages/toolpad-app/pages/api/data/[appId]/[version]/[queryId].ts
  packages/toolpad-app/pages/api/dataSources/[dataSource]/[...path].ts
  packages/toolpad-app/pages/api/rpc.ts
  packages/toolpad-app/src/server/config.ts
  packages/toolpad-app/src/server/logs/logInfo.ts
  packages/toolpad-app/src/server/logs/logSerializers.ts
  packages/toolpad-app/src/server/logs/logger.ts
  packages/toolpad-app/src/server/logs/withLogs.ts
  packages/toolpad-app/src/server/validateRecaptchaToken.ts
  packages/toolpad-app/src/utils/crypto.ts
  packages/toolpad-app/src/utils/uuid.ts
  yarn.lock
Labels: core

#1205 Part 4: Update datasource docs
  docs/data/toolpad/connecting-to-datasources/fetch.md
  docs/data/toolpad/connecting-to-datasources/function.md
  docs/data/toolpad/connecting-to-datasources/google-sheets.md
  docs/data/toolpad/connecting-to-datasources/postgre-sql.md
  docs/public/static/toolpad/docs/fetch-query-1.png
  docs/public/static/toolpad/docs/fetch-query-2.png
  docs/public/static/toolpad/docs/fetch-query-3.png
  docs/public/static/toolpad/docs/fetch-query-4.png
  docs/public/static/toolpad/docs/fetch/query-1.png
  docs/public/static/toolpad/docs/fetch/query-2.png
  docs/public/static/toolpad/docs/fetch/query-3.png
  docs/public/static/toolpad/docs/fetch/query-4.png
  docs/public/static/toolpad/docs/function-query-1.png
  docs/public/static/toolpad/docs/function-query-2.png
  docs/public/static/toolpad/docs/function-query-3.png
  docs/public/static/toolpad/docs/function-query-4.png
  docs/public/static/toolpad/docs/function-query-5.png
  docs/public/static/toolpad/docs/function-query-6.png
  docs/public/static/toolpad/docs/function/function-1.png
  docs/public/static/toolpad/docs/function/function-2.png
  docs/public/static/toolpad/docs/function/function-3.png
  docs/public/static/toolpad/docs/function/function-4.png
  docs/public/static/toolpad/docs/function/function-5.png
  docs/public/static/toolpad/docs/function/function-6.png
  docs/public/static/toolpad/docs/google-sheets-query-1.png
  docs/public/static/toolpad/docs/google-sheets-query-2.png
  docs/public/static/toolpad/docs/google-sheets/sheets-1.png
  docs/public/static/toolpad/docs/google-sheets/sheets-2.png
  docs/public/static/toolpad/docs/postgres-query-1.png
  docs/public/static/toolpad/docs/postgres-query-2.png
  docs/public/static/toolpad/docs/postgres-query-3.png
  docs/public/static/toolpad/docs/postgres/postgres-1.png
  docs/public/static/toolpad/docs/postgres/postgres-2.png
  docs/public/static/toolpad/docs/postgres/postgres-3.png
Labels: docs

#1219 v0.0.24
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
Labels: core

#1216 Part 6: Update data binding docs
  docs/data/toolpad/data-binding.md
  docs/public/static/toolpad/docs/data-binding-1.png
  docs/public/static/toolpad/docs/data-binding-2.png
  docs/public/static/toolpad/docs/data-binding-3.png
  docs/public/static/toolpad/docs/data-binding-4.png
  docs/public/static/toolpad/docs/data-binding-4x2.png
  docs/public/static/toolpad/docs/data-binding-5.png
  docs/public/static/toolpad/docs/data-binding-6.png
  docs/public/static/toolpad/docs/data-binding-7.png
  docs/public/static/toolpad/docs/data-binding-8.png
  docs/public/static/toolpad/docs/data-binding-9.png
  docs/public/static/toolpad/docs/data-binding/bind-1.png
  docs/public/static/toolpad/docs/data-binding/bind-2.png
  docs/public/static/toolpad/docs/data-binding/bind-3.png
  docs/public/static/toolpad/docs/data-binding/bind-4.png
  docs/public/static/toolpad/docs/data-binding/bind-5.png
  docs/public/static/toolpad/docs/data-binding/bind-6.png
  docs/public/static/toolpad/docs/data-binding/bind-7.png
  docs/public/static/toolpad/docs/data-binding/bind-8.png
  docs/public/static/toolpad/docs/data-binding/bind-9.png
Labels: docs

#1215 Part 5: Update building ui docs
  docs/data/toolpad/building-ui/canvas-and-inspector.md
  docs/data/toolpad/building-ui/component-library.md
  docs/data/toolpad/building-ui/custom-components.md
  docs/public/static/toolpad/docs/building-ui/ui-1.png
  docs/public/static/toolpad/docs/building-ui/ui-10.png
  docs/public/static/toolpad/docs/building-ui/ui-11.png
  docs/public/static/toolpad/docs/building-ui/ui-12.png
  docs/public/static/toolpad/docs/building-ui/ui-2.png
  docs/public/static/toolpad/docs/building-ui/ui-3.png
  docs/public/static/toolpad/docs/building-ui/ui-4.png
  docs/public/static/toolpad/docs/building-ui/ui-5.png
  docs/public/static/toolpad/docs/building-ui/ui-6.png
  docs/public/static/toolpad/docs/building-ui/ui-7.png
  docs/public/static/toolpad/docs/building-ui/ui-8.png
  docs/public/static/toolpad/docs/building-ui/ui-9.png
  docs/public/static/toolpad/docs/canvas-columns.png
  docs/public/static/toolpad/docs/canvas-grid.png
  docs/public/static/toolpad/docs/canvas-move.png
  docs/public/static/toolpad/docs/canvas-rows.png
  docs/public/static/toolpad/docs/canvas-selected.png
  docs/public/static/toolpad/docs/component-library.png
  docs/public/static/toolpad/docs/custom-component-1.png
  docs/public/static/toolpad/docs/custom-component-2.png
  docs/public/static/toolpad/docs/custom-component-3.png
  docs/public/static/toolpad/docs/inspector.png
  docs/public/static/toolpad/docs/sx-editor.png
  docs/public/static/toolpad/docs/sx.png
Labels: docs

#1210 Support duplicating pages, connection, components
  packages/toolpad-app/src/appDom/index.ts
  packages/toolpad-app/src/toolpad/AppEditor/HierarchyExplorer/CreateConnectionNodeDialog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/HierarchyExplorer/index.tsx
  packages/toolpad-app/src/toolpad/DomLoader.tsx
  packages/toolpad-app/src/toolpad/Home/index.tsx
  packages/toolpad-app/src/utils/useMenu.ts
  test/integration/duplication/dom.json
  test/integration/duplication/index.spec.ts
  test/models/ToolpadEditor.ts
  test/models/ToolpadHome.ts
  test/models/ToolpadRuntime.ts
  test/models/shared.ts
Labels: core

#1218 Use link component in app overview
  packages/toolpad-app/src/runtime/AppOverview.tsx
  test/models/ToolpadRuntime.ts
Labels: core

#1212 Disable making applications public in demo mode
  packages/toolpad-app/src/toolpad/Home/index.tsx
Labels: core

#1226 Support undefined values in serverside bindings
  packages/toolpad-app/src/server/evalExpression.spec.ts
  packages/toolpad-app/src/server/evalExpression.ts
  packages/toolpad-app/src/toolpad/AppEditor/BindingEditor.tsx
  test/models/ToolpadEditor.ts
Labels: core, bug 🐛

#1193 [ui] Add button size property
  packages/toolpad-components/src/Button.tsx
Labels: feature: Components

#1206 [core] Add clarifying comment in the dev env compose file
  docker-compose.dev.yml
Labels: core

#1250 [core] Pin GitHub Action to digests
  renovate.json
Labels: core, security

#1233 Fix node not found error
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/RenderOverlay.tsx
Labels: bug 🐛

#1223 Add new column types
  packages/toolpad-app/src/toolpad/propertyControls/GridColumns.tsx
  packages/toolpad-components/src/DataGrid.tsx
  packages/toolpad-components/tsconfig.json
  packages/toolpad-core/package.json
  packages/toolpad-core/src/constants.ts
  packages/toolpad-core/src/path.ts
Labels: core, new feature, feature: Components

#1249 [core] Fixes for upcoming eslint upgrade
  .eslintrc.js
  docs/next.config.js
  docs/pages/_app.js
  docs/scripts/helpers.js
  docs/src/components/landing/Marquee.js
  docs/src/components/landing/PricingTable.js
  docs/src/components/landing/SignUp.js
  docs/src/content/pricing.js
  packages/toolpad-app/scripts/waitForDb.ts
  packages/toolpad-app/src/components/DialogForm.tsx
  packages/toolpad-app/src/components/NoSsr.tsx
  packages/toolpad-app/src/toolpad/AppEditor/CodeComponentEditor/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentCatalog/ComponentCatalogItem.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/RenderOverlay.tsx
  packages/toolpad-app/src/toolpad/Home/index.tsx
  packages/toolpad-app/src/toolpad/Toolpad.tsx
  packages/toolpad-app/src/toolpadDataSources/rest/BodyEditor.tsx
  packages/toolpad-core/src/jsRuntime.tsx
  packages/toolpad-core/src/runtime.tsx
Labels: core

#1255 Deploy latest Docker image in demo
  docker/images/toolpad-demo/Dockerfile
Labels: core
