Repository mui/toolpad, pull requests merged in 2022-12, with the labels that each got.

#1400 Make sure EditableText updates when underlying string changes
  packages/toolpad-app/src/components/EditableText.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PagePanel.tsx
  packages/toolpad-app/src/toolpad/AppOptions/AppNameEditable.tsx
  packages/toolpad-app/src/toolpad/Apps/index.tsx
Labels: bug 🐛

#1397 Don't immediately open duplicated apps
  packages/toolpad-app/src/toolpad/AppEditor/PagePanel.tsx
  packages/toolpad-app/src/toolpad/AppOptions/AppDuplicateDialog.tsx
  packages/toolpad-app/src/toolpad/AppOptions/index.tsx
  packages/toolpad-app/src/toolpad/Apps/index.tsx
  packages/toolpad-app/src/utils/useRisingEdge.ts
Labels: design: ux

#1362 Try out transpilePackages on latest next
  packages/toolpad-app/next.config.mjs
  packages/toolpad-app/package.json
  packages/toolpad-app/pages/_app.tsx
  packages/toolpad-app/src/components/HarViewer.tsx
  yarn.lock
Labels: core

#1406 Add note about missing connections to demo footer
  packages/toolpad-app/src/toolpad/ToolpadShell/DemoBar.tsx
Labels: core

#1404 Move to next.config.mjs
  docs/next.config.js
  docs/next.config.mjs
Labels: core

#1403 Update dependencies
  docs/package.json
  package.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/next.config.mjs
  packages/toolpad-app/package.json
  packages/toolpad-app/scripts/tsconfig.json
  packages/toolpad-app/scripts/typings.mts
  packages/toolpad-app/scripts/waitForApp.mts
  packages/toolpad-app/scripts/waitForDb.mts
  packages/toolpad-app/tsconfig.json
  packages/toolpad-core/package.json
  renovate.json
  tsconfig.json
  yarn.lock
Labels: core

#1418 Remove stats template
  packages/toolpad-app/src/server/appTemplateDoms/doms.ts
  packages/toolpad-app/src/server/appTemplateDoms/statistics-demo.json
  packages/toolpad-app/src/server/appTemplateDoms/statistics.json
  packages/toolpad-app/src/toolpad/Apps/index.tsx
  packages/toolpad-app/src/types.ts
  test/integration/appTemplates.spec.ts
Labels: bug 🐛

#1381 Add a Default app template
  packages/toolpad-app/public/static/employees.json
  packages/toolpad-app/src/server/appTemplateDoms/default.json
  packages/toolpad-app/src/server/appTemplateDoms/doms.ts
  packages/toolpad-app/src/toolpad/Apps/index.tsx
  packages/toolpad-app/src/types.ts
  test/models/ToolpadHome.ts
Labels: enhancement

#1319 Add demo link to the docs
  README.md
  docs/data/toolpad/getting-started/overview.md
  docs/pages/toolpad/getting-started/overview.js
  docs/pages/toolpad/index.js
  docs/public/static/toolpad/marketing/readme-hero-poster.jpeg
  docs/src/components/landing/Banner.js
  docs/src/content/upvote.js
Labels: docs

#1426 Revert accidental react-router-dom update
  yarn.lock
Labels: regression

#1428 v0.0.30
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
Labels: core

#1434 Fix controlled value reset when default value changes
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  test/integration/propControls/defaultValueDom.json
  test/integration/propControls/index.spec.ts
Labels: feature: Components

#1433 Landing page tweaks
  docs/src/components/landing/Banner.js
  docs/src/components/landing/Marquee.js
Labels: website

#1424 Add roadmap to the docs
  docs/data/pages.ts
  docs/data/toolpad/getting-started/roadmap.md
  docs/pages/toolpad/getting-started/roadmap.js
Labels: docs

#1443 Fix yarnlock
  yarn.lock
Labels: core

#1444 Revert react-router-dom to 6.3
  package.json
  packages/toolpad-app/src/components/MonacoEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/CodeComponentEditor/index.tsx
  test/integration/codeComponents/dom.json
  test/integration/codeComponents/index.spec.ts
  test/models/ToolpadEditor.ts
  yarn.lock
Labels: core, regression

#1442 Document and cleanup of utility functions
  packages/toolpad-app/src/toolpad/AppEditor/BindingEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/GlobalScopeExplorer.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/BindableEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/JsExpressionEditor.tsx
  packages/toolpad-app/src/toolpadDataSources/rest/client.tsx
  packages/toolpad-app/src/types.ts
  packages/toolpad-app/src/utils/bindings.ts
  packages/toolpad-app/src/utils/collections.ts
  packages/toolpad-app/src/utils/crypto.ts
  packages/toolpad-app/src/utils/errors.ts
  packages/toolpad-app/src/utils/evalExpression.ts
  packages/toolpad-app/src/utils/fields.ts
  packages/toolpad-app/src/utils/forms.ts
  packages/toolpad-app/src/utils/fs.ts
  packages/toolpad-app/src/utils/geometry.ts
  packages/toolpad-app/src/utils/har.ts
  packages/toolpad-app/src/utils/immutability.ts
  packages/toolpad-app/src/utils/lazyComponent.tsx
  packages/toolpad-app/src/utils/prettier.ts
  packages/toolpad-app/src/utils/prisma.ts
  packages/toolpad-app/src/utils/react.tsx
  packages/toolpad-app/src/utils/readableDuration.ts
  packages/toolpad-app/src/utils/router.ts
  packages/toolpad-app/src/utils/server.ts
  packages/toolpad-app/src/utils/streams.ts
  packages/toolpad-app/src/utils/strings.ts
  packages/toolpad-app/src/utils/tests.ts
  packages/toolpad-app/src/utils/types.ts
  packages/toolpad-app/src/utils/useBoolean.ts
  packages/toolpad-app/src/utils/useDebounced.ts
  packages/toolpad-app/src/utils/useDebouncedHandler.ts
  packages/toolpad-app/src/utils/useDialog.tsx
  packages/toolpad-app/src/utils/useEvent.ts
  packages/toolpad-app/src/utils/useLatest.ts
  packages/toolpad-app/src/utils/useLocalStorageState.ts
  packages/toolpad-app/src/utils/useMenu.ts
  packages/toolpad-app/src/utils/usePageTitle.ts
  packages/toolpad-app/src/utils/useRisingEdge.ts
  packages/toolpad-app/src/utils/useThottled.ts
  packages/toolpad-app/src/utils/uuid.ts
Labels: core

#1298 Add Text component to merge Typography, Markdown, Link
  packages/toolpad-app/package.json
  packages/toolpad-app/src/appDom/index.ts
  packages/toolpad-app/src/appDom/migrations/index.ts
  packages/toolpad-app/src/appDom/migrations/v4.ts
  packages/toolpad-app/src/components/MarkdownEditor.tsx
  packages/toolpad-app/src/components/MonacoEditor.tsx
  packages/toolpad-app/src/runtime/ToolpadApp.spec.tsx
  packages/toolpad-app/src/runtime/loadCodeComponent.tsx
  packages/toolpad-app/src/toolpad/AppEditor/CodeComponentEditor/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentCatalog/ComponentCatalogItem.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/NodeAttributeEditor.tsx
  packages/toolpad-app/src/toolpad/propertyControls/Markdown.tsx
  packages/toolpad-app/src/toolpad/propertyControls/index.tsx
  packages/toolpad-app/src/toolpadComponents/index.tsx
  packages/toolpad-app/src/toolpadComponents/layoutBox.ts
  packages/toolpad-app/src/types.ts
  packages/toolpad-app/typings/monaco-editor.d.ts
  packages/toolpad-components/package.json
  packages/toolpad-components/src/Link.tsx
  packages/toolpad-components/src/Text.tsx
  packages/toolpad-components/src/Typography.tsx
  packages/toolpad-components/src/index.tsx
  packages/toolpad-core/src/constants.ts
  packages/toolpad-core/src/createComponent.tsx
  packages/toolpad-core/src/types.ts
  yarn.lock
Labels: feature: Components

#1450 v0.0.31
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
Labels: core

#1454 Add visual feedback when query is running
  packages/toolpad-app/src/toolpadDataSources/QueryPreview.tsx
  packages/toolpad-app/src/toolpadDataSources/function/client.tsx
  packages/toolpad-app/src/toolpadDataSources/googleSheets/client.tsx
  packages/toolpad-app/src/toolpadDataSources/postgres/client.tsx
  packages/toolpad-app/src/toolpadDataSources/rest/client.tsx
  packages/toolpad-app/src/toolpadDataSources/useQueryPreview.ts
Labels: design: ux

#1449 Add formatting options to DataGrid columns
  packages/toolpad-app/src/toolpad/propertyControls/GridColumns.tsx
  packages/toolpad-app/src/toolpadDataSources/googleSheets/client.tsx
  packages/toolpad-app/src/toolpadDataSources/postgres/client.tsx
  packages/toolpad-components/src/DataGrid.tsx
  packages/toolpad-components/src/index.tsx
Labels: enhancement

#1459 Debounce text input changes
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/EditorCanvasHost.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/index.tsx
  packages/toolpad-app/src/toolpad/DomLoader.tsx
  test/integration/undo-redo/index.spec.ts
Labels: enhancement

#1455 Replace gridcolumns editor dialog with popover
  packages/toolpad-app/src/toolpad/propertyControls/GridColumns.tsx
Labels: design: ux

#1457 Fix display of errors during loading of data
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  test/integration/appDuplicate.spec.ts
  test/integration/duplication/index.spec.ts
  test/integration/function-basic/index.spec.ts
  test/integration/rest-basic/index.spec.ts
  test/playwright/test.ts
Labels: core, bug 🐛

#1468 Non permanent root redirection
  packages/toolpad-app/pages/index.tsx
Labels: core

#1374 Single-update undo/redo
  packages/toolpad-app/src/appDom/index.ts
  packages/toolpad-app/src/toolpad/AppEditor/ConnectionEditor/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/HierarchyExplorer/CreateCodeComponentNodeDialog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/HierarchyExplorer/CreateConnectionNodeDialog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/HierarchyExplorer/CreatePageNodeDialog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/HierarchyExplorer/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentCatalog/ComponentCatalog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/EditorCanvasHost.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/NodeAttributeEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/PageModuleEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/QueryEditor/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/RenderOverlay.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/RenderPanel.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ThemeEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/UrlQueryEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/index.tsx
  packages/toolpad-app/src/toolpad/DomLoader.tsx
  test/integration/undo-redo/index.spec.ts
Labels: core, enhancement

#1472 Move recaptcha script away from _app
  packages/toolpad-app/pages/_app.tsx
  packages/toolpad-app/src/toolpad/Apps/index.tsx
Labels: core

#1473 Simplify RPC logs
  packages/toolpad-app/pages/api/rpc.ts
  packages/toolpad-app/src/server/config.ts
  packages/toolpad-app/src/server/logs/logInfo.ts
  packages/toolpad-app/src/server/logs/logSerializers.ts
  packages/toolpad-app/src/server/logs/logger.ts
  packages/toolpad-app/src/server/logs/withLogs.ts
Labels: core

#1475 [docs] Banner tweaks
  docs/src/components/landing/Banner.js
Labels: docs

#1480 Add survey dialog
  packages/toolpad-app/src/toolpad/Apps/index.tsx
Labels: feature: App Editor

#1482 Release v0.0.32
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
Labels: core

#1481 Fix flaky rest-basics test
  .circleci/config.yml
  CONTRIBUTING.md
  docker-compose.test.yml
  docker/compose/docker-compose.yml
  packages/toolpad-app/src/server/appTemplateDoms/doms.ts
  test/integration/rest-basic/index.spec.ts
  test/utils/fs.ts
Labels: test, core

#1476 Fix canvas ref timing issues
  packages/toolpad-app/src/canvas/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/EditorCanvasHost.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/RenderOverlay.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/RenderPanel.tsx
  packages/toolpad-core/src/types.ts
  test/integration/rest-basic/index.spec.ts
Labels: core

#1485 Fix: Demo reCaptcha v2 fallback does not work
  packages/toolpad-app/src/toolpad/Apps/index.tsx
  packages/toolpad-app/src/utils/errors.ts
  packages/toolpad-core/src/types.ts
Labels: bug 🐛

#1498 v0.0.33
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
Labels: core

#1499 Date picker component
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/BindableEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentEditor.tsx
  packages/toolpad-app/src/toolpadComponents/index.tsx
  packages/toolpad-components/src/DatePicker.tsx
  packages/toolpad-components/src/index.tsx
Labels: feature: App Editor
