Repository mui/toolpad, pull requests merged in 2023-08, with the labels that each got.

#2381 Avoid running the server in a separate process
  packages/toolpad-app/cli/appBuilder.ts
  packages/toolpad-app/cli/appServer.ts
  packages/toolpad-app/cli/index.ts
  packages/toolpad-app/cli/server.ts
  packages/toolpad-app/jest-environment-jsdom.ts
  packages/toolpad-app/src/config.ts
  packages/toolpad-app/src/server/DataManager.ts
  packages/toolpad-app/src/server/FunctionsManager.ts
  packages/toolpad-app/src/server/config.ts
  packages/toolpad-app/src/server/data.ts
  packages/toolpad-app/src/server/functionsDevWorker.ts
  packages/toolpad-app/src/server/liveProject.ts
  packages/toolpad-app/src/server/localMode.ts
  packages/toolpad-app/src/server/rpc.ts
  packages/toolpad-app/src/server/toolpadAppBuilder.ts
  packages/toolpad-app/src/server/toolpadAppServer.ts
  packages/toolpad-app/src/server/versionInfo.ts
  packages/toolpad-app/src/toolpadDataSources/demo.tsx
  packages/toolpad-app/src/toolpadDataSources/googleSheets/server.ts
  packages/toolpad-app/src/toolpadDataSources/local/server.ts
  packages/toolpad-app/src/toolpadDataSources/rest/client.tsx
  packages/toolpad-app/src/toolpadDataSources/rest/server.ts
  packages/toolpad-app/src/toolpadDataSources/rest/shared.ts
  packages/toolpad-app/src/toolpadDataSources/server.ts
  packages/toolpad-app/src/types.ts
Labels: core

#2171 it will delete old page while adding new page
  .gitignore
  packages/toolpad-app/src/server/localMode.ts
  packages/toolpad-app/src/toolpad/AppEditor/NodeNameEditor.tsx
  test/integration/editor/fixture/toolpad/pages/page23/page.yml
  test/integration/editor/fixture/toolpad/pages/page4/page.yml
  test/integration/editor/index.spec.ts
  test/integration/editor/new.spec.ts
Labels: bug 🐛

#2401 Fix Windows EBUSY error when removing files during tests
  test/playwright/localTest.ts
Labels: test

#2394 Improve docs
  docs/data/pages.ts
  docs/data/toolpad/concepts/connecting-to-data.md
  docs/data/toolpad/concepts/custom-functions.md
  docs/data/toolpad/concepts/http-requests.md
  docs/data/toolpad/concepts/queries.md
  docs/data/toolpad/how-to-guides/custom-components.md
  docs/pages/toolpad/concepts/custom-functions.js
  docs/pages/toolpad/concepts/http-requests.js
  docs/pages/toolpad/concepts/queries.js
Labels: docs

#2397 Components explorer improvements
  packages/toolpad-app/src/toolpad/AppEditor/StructureExplorer/index.tsx
Labels: enhancement

#2405 [website] Add "Book Demo" button
  docs/src/components/landing/GetStartedButtons.js
  docs/src/components/landing/Hero.js
  docs/src/route.ts
Labels: website

#2411 Update monorepo
  yarn.lock
Labels: chore 🧹

#2412 Improve Toolpad startup time
  packages/toolpad-app/cli/appBuilder.ts
  packages/toolpad-app/cli/appServer.ts
  packages/toolpad-app/cli/server.ts
  packages/toolpad-app/src/server/localMode.ts
  packages/toolpad-app/src/server/toolpadAppBuilder.ts
  packages/toolpad-app/src/server/workerRpc.ts
  packages/toolpad-app/tsup.config.ts
Labels: test

#2417 v0.1.22
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/create-toolpad-app/package.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
  packages/toolpad-utils/package.json
Labels: release 🚀

#2416 Increase localApp fixture timeout
  test/playwright/localTest.ts
Labels: test

#2419 Adjust timeout and import node-fetch in create-toolpad-app test (#2414)
  packages/create-toolpad-app/package.json
  packages/create-toolpad-app/tests/index.spec.ts
Labels: test

#2424 [docs] Fix 404s
  docs/public/_redirects
Labels: docs

#2426 Add note about why we need usePolling
  packages/toolpad-app/src/server/localMode.ts
Labels: core

#2418 Clean up worker communication with devserver
  packages/toolpad-app/cli/appBuilder.ts
  packages/toolpad-app/cli/appServer.ts
  packages/toolpad-app/cli/server.ts
  packages/toolpad-app/src/server/localMode.ts
  packages/toolpad-app/src/server/toolpadAppBuilder.ts
Labels: core

#2427 Scope MUI X license to builtin components only
  packages/toolpad-app/src/constants.ts
  packages/toolpad-app/src/server/toolpadAppBuilder.ts
  packages/toolpad-components/package.json
  packages/toolpad-components/src/DataGrid.tsx
  packages/toolpad-components/tsup.config.ts
Labels: core

#2410 Remove logging of RPC errors
  packages/toolpad-app/src/server/rpc.ts
Labels: core

#2436 Bump react-router
  docs/package.json
  packages/toolpad-app/package.json
  packages/toolpad-app/src/utils/router.ts
  renovate.json
  yarn.lock
Labels: dependencies

#2438 Improve rest test flakyness
  test/integration/rest-basic/index.spec.ts
Labels: test

#2437 Remove some Next.js leftovers around monaco-editor
  packages/toolpad-app/src/components/MonacoEditor.tsx
  packages/toolpad-app/src/components/monaco/getWorkerNext.ts
  packages/toolpad-app/tsconfig.json
Labels: core

#2444 Update ensure triage label workflow
  .github/workflows/ensure-triage-label.yml
Labels: core

#2440 [docs] Improve deployment instructions
  docs/data/pages.ts
  docs/data/toolpad/concepts/deployment.md
  docs/data/toolpad/how-to-guides/connect-to-googlesheets.md
  docs/data/toolpad/how-to-guides/render-deploy.md
  docs/pages/toolpad/how-to-guides/render-deploy.js
  docs/public/_redirects
Labels: docs

#2441 Improve prisma example
  examples/with-prisma/README.md
Labels: examples

#2452 Improve setup time of tests
  test/playwright/localTest.ts
Labels: test

#2454 Fix new components not showing up when component folder doesn't exist
  packages/toolpad-app/src/server/localMode.ts
  test/integration/codeComponents/index.spec.ts
  test/integration/editor/index.spec.ts
  test/integration/editor/new.spec.ts
  test/integration/undo-redo/basic.spec.ts
  test/models/ToolpadEditor.ts
Labels: core

#2458 [docs] Follow Docs-infra default design
  docs/data/pages.ts
Labels: docs

#2400 Chart improvements from npm stats example update
  docs/data/toolpad/reference/components/chart.md
  packages/toolpad-app/src/runtime/evalJsBindings.ts
  packages/toolpad-components/src/Chart.tsx
  test/integration/components/chart.spec.ts
  test/integration/components/fixture-chart/toolpad/pages/loadingAndError/page.yml
  test/integration/components/fixture-chart/toolpad/resources/functions.ts
Labels: feature: Components, enhancement

#2462 Remove ses
  packages/toolpad-app/package.json
  yarn.lock
Labels: security

#2442 Fix app not starting in Windows (10)
  packages/toolpad-app/src/server/toolpadAppBuilder.ts
Labels: bug 🐛

#2460 Fix full page error overflow
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ErrorAlert.tsx
  packages/toolpad-app/src/toolpad/Toolpad.tsx
  packages/toolpad-app/src/toolpadDataSources/QueryPreview.tsx
Labels: design: ui

#2461 Clean up env watcher and build contexts on process exit
  packages/toolpad-app/cli/appServer.ts
  packages/toolpad-app/cli/server.ts
  packages/toolpad-app/src/server/EnvManager.ts
  packages/toolpad-app/src/server/FunctionsManager.ts
  packages/toolpad-app/src/server/toolpadAppServer.ts
Labels: core

#2472 Fix cycle of SIGINT disposal event
  packages/toolpad-app/cli/index.ts
Labels: bug 🐛

#2473 v0.1.23
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/create-toolpad-app/package.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
  packages/toolpad-utils/package.json
Labels: release 🚀

#2475 Update monorepo
  yarn.lock
Labels: chore 🧹

#2476 [core] Remove dead code html meta
  packages/toolpad-app/src/toolpad/index.html
Labels: core

#2385 Update npm stats example to use new chart component
  examples/npm-stats/toolpad/components/LineChart.tsx
  examples/npm-stats/toolpad/pages/page/page.yml
Labels: examples

#2480 [Enhancement] Edit page title from page editor
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/PageOptionsPanel.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageTitleEditor.tsx
Labels: new feature

#2491 Support reading cookies in backend functions
  docs/data/toolpad/concepts/custom-functions.md
  docs/data/toolpad/reference/api/get-context.md
  packages/toolpad-app/src/server/DataManager.ts
  packages/toolpad-app/src/server/functionsDevWorker.ts
  packages/toolpad-app/src/server/rpc.ts
  packages/toolpad-core/package.json
  packages/toolpad-core/src/index.tsx
  packages/toolpad-core/src/server.ts
  test/integration/backend-basic/fixture/toolpad/pages/basic/page.yml
  test/integration/backend-basic/fixture/toolpad/resources/functions.ts
  test/integration/backend-basic/index.spec.ts
  test/integration/backend-basic/prod.spec.ts
  test/integration/backend-basic/shared.ts
  yarn.lock
Labels: core

#2493 Chart adjustments
  packages/toolpad-components/src/Chart.tsx
  test/integration/components/chart.spec.ts
Labels: feature: Components, enhancement

#2495 Fix falsy prop updates
  packages/toolpad-app/src/appDom/index.ts
  packages/toolpad-app/src/bindings.ts
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/runtime/evalJsBindings.ts
  packages/toolpad-components/src/Autocomplete.tsx
  packages/toolpad-core/src/jsRuntime.tsx
  test/integration/propControls/basic.spec.ts
  test/integration/propControls/fixture-basic/toolpad/pages/page1/page.yml
Labels: bug 🐛

#2479 [core] Fix confusing component nomenclature
  packages/toolpad-app/src/toolpad/AppEditor/HierarchyExplorer/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/NoPageFound.tsx
  packages/toolpad-app/src/toolpad/AppEditor/NodeNameEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentCatalog/ComponentCatalog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/QueryEditor/QueryEditorDialog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PagePanel.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PagesExplorer/CreateCodeComponentNodeDialog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PagesExplorer/CreatePageNodeDialog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PagesExplorer/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PagesExplorer/validation.ts
  packages/toolpad-app/src/toolpad/AppEditor/StructureExplorer/index.tsx
  test/integration/duplication/index.spec.ts
  test/integration/editor/deleteLast.spec.ts
  test/integration/editor/new.spec.ts
  test/models/ToolpadEditor.ts
Labels: chore 🧹

#2497 [docs] Cleanup
  docs/data/toolpad/reference/api/create-function.md
  docs/src/components/landing/Hero.js
Labels: docs

#2496 [core] Upgrade monorepo
  yarn.lock
Labels: core

#2501 v0.1.24
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/create-toolpad-app/package.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
  packages/toolpad-utils/package.json
Labels: release 🚀

#2388 Avoid single child layout containers
  docs/data/toolpad/reference/components/autocomplete.md
  packages/toolpad-app/src/server/localMode.ts
  packages/toolpad-app/src/toolpad/AppEditor/HierarchyExplorer/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/NodeDropArea.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/NodeHud.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/RenderOverlay.tsx
  packages/toolpad-app/src/toolpad/AppEditor/pageLayout.ts
  packages/toolpad-components/src/Autocomplete.tsx
Labels: feature: App Editor

#2514 Add an explanation on why we use structuredClone in the canvas
  packages/toolpad-app/src/canvas/index.tsx
Labels: core

#2513 Update bug template to ask for specific environment
  .github/ISSUE_TEMPLATE/1.bug.yml
Labels: core

#2471 Add graphQL example
  examples/graphql/.gitignore
  examples/graphql/package.json
  examples/graphql/toolpad/.gitignore
  examples/graphql/toolpad/pages/page/page.yml
  examples/graphql/toolpad/resources/function.ts
Labels: examples

#2524 [docs] Add 'Miscellaneous' section to How-to guides
  docs/data/pages.ts
  examples/stripe-script/.gitignore
  examples/stripe-script/package.json
  examples/stripe-script/toolpad/.gitignore
  examples/stripe-script/toolpad/pages/page/page.yml
  examples/stripe-script/toolpad/resources/functions.ts
Labels: docs

#2521 Fix esbuild warning
  packages/toolpad-app/src/server/FunctionsManager.ts
  packages/toolpad-app/src/server/functionsShared.ts
  packages/toolpad-app/src/server/functionsTypesWorker.ts
Labels: core

#2522 Make module exports compatible with node module resolution in typescript
  packages/toolpad-app/package.json
Labels: core

#2530 [website] Fix typo
  docs/src/components/landing/Hero.js
Labels: website

#2398 React resizable panels
  packages/toolpad-app/package.json
  packages/toolpad-app/src/components/SplitPane.tsx
  packages/toolpad-app/src/components/resizablePanels.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PagePanel.tsx
  packages/toolpad-app/src/toolpadDataSources/googleSheets/client.tsx
  packages/toolpad-app/src/toolpadDataSources/local/client.tsx
  packages/toolpad-app/src/toolpadDataSources/rest/client.tsx
  packages/toolpad-app/src/toolpadDataSources/sql/client.tsx
  test/integration/editor/index.spec.ts
  yarn.lock
Labels: core

#2447 Add more examples page
  docs/data/pages.ts
  docs/data/toolpad/getting-started/examples-overview.md
  docs/pages/toolpad/examples/overview.js
  docs/public/static/toolpad/marketing/custom-datagrid-column.png
  docs/public/static/toolpad/marketing/datagrid-columns.png
  docs/public/static/toolpad/marketing/google-sheet.png
  docs/src/modules/components/ExamplesGrid.js
  docs/src/route.ts
Labels: docs

#2533 Stall package updates for dependencies that require node 18
  renovate.json
Labels: core

#2518 Clean up dist folders on build
  packages/create-toolpad-app/package.json
  packages/toolpad-app/tsconfig.runtime.json
  packages/toolpad-app/tsup.config.ts
  packages/toolpad-components/package.json
  packages/toolpad-components/tsup.config.ts
  packages/toolpad-core/package.json
  packages/toolpad-core/tsup.config.ts
  packages/toolpad-utils/package.json
  packages/toolpad-utils/tsup.config.ts
Labels: core

#2536 v0.1.25
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/create-toolpad-app/package.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
  packages/toolpad-utils/package.json
Labels: release 🚀

#2535 Refactor Toolpad App Navigation
  packages/toolpad-app/src/runtime/AppLayout.tsx
  packages/toolpad-app/src/runtime/AppNavigation.tsx
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/runtime/index.tsx
Labels: core

#2544 Update monorepo
  docs/data/toolpad/getting-started/examples-overview.md
  packages/toolpad-app/src/runtime/AppLayout.tsx
  packages/toolpad-app/src/toolpad/AppEditor/BindingEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/GlobalScopeExplorer.tsx
  packages/toolpad-app/src/toolpad/propertyControls/ChartData.tsx
  packages/toolpad-app/src/toolpad/propertyControls/HorizontalAlign.tsx
  packages/toolpad-app/src/toolpad/propertyControls/VerticalAlign.tsx
  yarn.lock
Labels: chore 🧹

#2545 Remove lodash from @mui/components
  packages/toolpad-components/package.json
  packages/toolpad-components/src/Form.tsx
  packages/toolpad-utils/src/collections.spec.ts
  packages/toolpad-utils/src/collections.ts
Labels: core

#2547 [core] Remove S3 orb from circleci config
  .circleci/config.yml
Labels: core

#2557 Fix query editor panels orientation
  packages/toolpad-app/src/toolpadDataSources/googleSheets/client.tsx
  packages/toolpad-app/src/toolpadDataSources/local/client.tsx
  packages/toolpad-app/src/toolpadDataSources/rest/client.tsx
  packages/toolpad-app/src/toolpadDataSources/sql/client.tsx
  test/integration/backend-basic/index.spec.ts
  test/integration/rest-basic/index.spec.ts
Labels: design: ui

#2371 Auto parse date strings on data grids
  packages/toolpad-components/src/DataGrid.tsx
Labels: enhancement

#2556 Allow theme files to not specify a palette
  docs/schemas/v1/definitions.json
  packages/toolpad-app/src/server/schema.ts
Labels: core, enhancement

#2532 [website] Add GA4 events
  docs/src/components/landing/CardGrid.js
  docs/src/components/landing/DemoVideo.js
  docs/src/components/landing/GithubStars.js
  docs/src/components/landing/SignUp.js
Labels: website

#2540 fix 2467_AutoComplete
  packages/toolpad-app/src/toolpad/propertyControls/string.tsx
  test/integration/propControls/basic.spec.ts
Labels: bug 🐛

#2574 Stabilize visual regression test
  test/integration/rest-basic/index.spec.ts
Labels: test

#2576 [docs] add graphQL to overview page and add 2 readme docs
  docs/public/static/toolpad/marketing/graphql.png
  docs/src/modules/components/ExamplesGrid.js
  examples/google-sheet/README.md
  examples/graphql/README.md
Labels: docs

#2586 Allow using Intl in bindings
  packages/toolpad-core/src/jsBrowserRuntime.tsx
  test/integration/bindings/fixture/toolpad/pages/bindings/page.yml
  test/integration/bindings/fixture/toolpad/pages/encoding/page.yml
  test/integration/bindings/fixture/toolpad/pages/globalScope/page.yml
  test/integration/bindings/index.spec.ts
Labels: core

#2584 Stabilize query editor screenshots
  test/integration/backend-basic/index.spec.ts
  test/integration/rest-basic/index.spec.ts
Labels: test

#2577 Show page parameters in url form and add link to docs
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/UrlQueryEditor.tsx
Labels: design: ux

#2594 Auto-create a theme when the user starts editing
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentPanel.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ThemeEditor.tsx
  test/integration/theme/index.spec.ts
Labels: design: ux

#2593 Add visual regression tests for text component
  packages/toolpad-components/src/Text.tsx
  test/visual/components/fixture/toolpad/pages/components/page.yml
  test/visual/components/fixture/toolpad/pages/rows/page.yml
  test/visual/components/fixture/toolpad/pages/text/page.yml
  test/visual/components/index.spec.ts
Labels: test

#2598 Upgrade monorepo
  yarn.lock
Labels: dependencies

#2597 v0.1.26
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/create-toolpad-app/package.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
  packages/toolpad-utils/package.json
Labels: release 🚀
