Repository mui/toolpad, pull requests merged in 2023-05, with the labels that each got.

#1942 Added dog app arcade to quickstart section of docs
  docs/data/toolpad/getting-started/quickstart.md
Labels: docs

#1956 Fix: Wrapping on Text/Link
  packages/toolpad-components/src/Text.tsx
Labels: bug 🐛, design: ui

#1960 small improvements
  package.json
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentEditor.tsx
  test/playwright.config.ts
  test/playwright/localTest.ts
Labels: core

#1957 Update datagrid example to new filesystem layout
  examples/custom-datagrid-column/toolpad.yaml
  examples/custom-datagrid-column/toolpad/.gitignore
  examples/custom-datagrid-column/toolpad/pages/example/page.yml
Labels: examples

#1967 Pin next.js
  packages/toolpad-app/package.json
  yarn.lock
Labels: core, regression

#1969 version 0.1.10
  CHANGELOG.md
  RELEASE.md
  docs/package.json
  lerna.json
  packages/create-toolpad-app/package.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
  packages/toolpad-utils/package.json
  packages/toolpad/package.json
Labels: release 🚀

#1968 Pin all dependencies
  docs/package.json
  package.json
  packages/create-toolpad-app/package.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
  packages/toolpad-utils/package.json
  packages/toolpad/package.json
  yarn.lock
Labels: core

#1979 Isolate next updates
  renovate.json
Labels: core

#1980 Separate deps updates for docs in renovatebot
  renovate.json
Labels: core, dependencies

#1876 Add page parameters to navigation actions
  docs/data/toolpad/data-binding.md
  docs/public/static/toolpad/docs/data-binding/bind-12.png
  packages/toolpad-app/src/appDom/index.ts
  packages/toolpad-app/src/runtime/CanvasHooksContext.tsx
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/server/localMode.ts
  packages/toolpad-app/src/toolpad/AppEditor/BindingEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/BindableEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/QueryEditor/QueryEditorDialog.tsx
  packages/toolpad-app/src/toolpad/propertyControls/string.tsx
  packages/toolpad-app/src/toolpadDataSources/rest/BodyEditor.tsx
  packages/toolpad-app/src/toolpadDataSources/rest/client.tsx
  packages/toolpad-core/src/types.ts
  test/integration/bindings/fixture-navigation/toolpad/.gitignore
  test/integration/bindings/fixture-navigation/toolpad/pages/page1/page.yml
  test/integration/bindings/fixture-navigation/toolpad/pages/page2/page.yml
  test/integration/bindings/navigation.spec.ts
  test/integration/duplication/fixture/toolpad.yml
  test/integration/mysql-basic/mysqlDom.json
  test/models/ToolpadRuntime.ts
Labels: new feature

#1947 Fix overlay grid spacing
  packages/toolpad-app/src/runtime/AppThemeProvider.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/OverlayGrid.tsx
Labels: bug 🐛

#1970 Change tests structure to use ESM
  jest.config.ts
  package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
  packages/toolpad-utils/jest.config.ts
  packages/toolpad-utils/package.json
  packages/toolpad-utils/tsconfig.json
  test/utils/jest-setup.ts
Labels: core

#1966 Fix console.error being called in tests
  package.json
  packages/toolpad-app/jest.config.ts
  packages/toolpad-app/src/runtime/ToolpadApp.spec.tsx
  packages/toolpad-utils/jest.config.ts
  test/setupJest.ts
  yarn.lock
Labels: test

#1989 Fix broken preview in vite runtime
  packages/toolpad-app/src/server/toolpadAppBuilder.ts
  packages/toolpad-app/tsup.config.ts
Labels: core

#1998 v0.1.11
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/create-toolpad-app/package.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
  packages/toolpad-utils/package.json
  packages/toolpad/package.json
Labels: release 🚀

#1992 Fix: Make code the hero
  docs/src/components/landing/Hero.js
  docs/src/components/landing/Marquee.js
  docs/src/content/marquee.js
Labels: docs

#1965 Add jest tests for `create-toolpad-app`
  packages/create-toolpad-app/jest.config.ts
  packages/create-toolpad-app/package.json
  packages/create-toolpad-app/src/index.ts
  packages/create-toolpad-app/tests/index.spec.ts
  packages/create-toolpad-app/tests/package.json
  packages/create-toolpad-app/tests/tsconfig.json
  packages/create-toolpad-app/tsconfig.json
  packages/create-toolpad-app/tsup.config.ts
Labels: core

#2000 Clean up dead code
  packages/toolpad-app/package.json
  packages/toolpad-app/pages/api/rpc.ts
  packages/toolpad-app/src/api.ts
  packages/toolpad-app/src/compileModule.ts
  packages/toolpad-app/src/createRuntimeState.tsx
  packages/toolpad-app/src/rpcClient.ts
  packages/toolpad-app/src/runtime/ToolpadApp.spec.tsx
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/runtime/loadDomComponents.tsx
  packages/toolpad-app/src/types.ts
  packages/toolpad-app/tsconfig.json
  test/playwright/test.ts
  yarn.lock
Labels: core

#1994 Deprecate typeDef
  docs/data/toolpad/building-ui/custom-components.md
  docs/data/toolpad/connecting-to-datasources/custom-functions.md
  examples/custom-datagrid-column/toolpad/components/AgeColumn.tsx
  examples/custom-datagrid-column/toolpad/components/FullNameColumn.tsx
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/server/localMode.ts
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/BindableEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/NodeAttributeEditor.tsx
  packages/toolpad-app/src/toolpad/propertyControls/index.tsx
  packages/toolpad-app/src/toolpadComponents/layoutBox.ts
  packages/toolpad-app/src/toolpadComponents/template.ts
  packages/toolpad-app/src/toolpadDataSources/local/client.tsx
  packages/toolpad-components/src/Button.tsx
  packages/toolpad-components/src/Container.tsx
  packages/toolpad-components/src/DataGrid.tsx
  packages/toolpad-components/src/DatePicker.tsx
  packages/toolpad-components/src/FilePicker.tsx
  packages/toolpad-components/src/Form.tsx
  packages/toolpad-components/src/Image.tsx
  packages/toolpad-components/src/List.tsx
  packages/toolpad-components/src/PageColumn.tsx
  packages/toolpad-components/src/PageRow.tsx
  packages/toolpad-components/src/Paper.tsx
  packages/toolpad-components/src/Select.tsx
  packages/toolpad-components/src/Stack.tsx
  packages/toolpad-components/src/Tabs.tsx
  packages/toolpad-components/src/Text.tsx
  packages/toolpad-components/src/TextField.tsx
  packages/toolpad-core/src/createComponent.tsx
  packages/toolpad-core/src/createFunction.tsx
  packages/toolpad-core/src/types.ts
  test/integration/backend-basic/fixture/toolpad/queries.ts
  test/integration/codeComponents/index.spec.ts
  test/integration/components/fixture-basic/toolpad/components/MyComponent.tsx
  test/integration/data-grid/fixture-custom/toolpad/components/Other.tsx
  test/integration/data-grid/fixture-custom/toolpad/components/Test.tsx
  test/integration/theme/fixture/toolpad/components/Test.tsx
Labels: core

#2003 Move to zod-to-json-schema
  docs/schemas/v1/definitions.json
  docs/src/modules/components/SchemaReference.tsx
  package.json
  scripts/generateJsonSchemas.mts
  yarn.lock
Labels: core

#2009 [docs] Fix 404 link to fix the page
  docs/data/pages.ts
  docs/pages/toolpad/schema-reference/index.tsx
  docs/src/modules/components/SchemaReference.tsx
Labels: docs, bug 🐛

#2016 Make canvas column spacing the same as in the runtime
  packages/toolpad-app/src/runtime/AppThemeProvider.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/OverlayGrid.tsx
Labels: core

#2008 Remove unused config
  packages/toolpad-app/pages/_app.tsx
  packages/toolpad-app/pages/_document.tsx
  packages/toolpad-app/src/config.ts
  packages/toolpad-app/src/utils/ga.ts
Labels: core

#2020 Correctly set charset for preview html
  packages/toolpad-app/cli/appServer.ts
  packages/toolpad-app/src/server/toolpadAppBuilder.ts
  test/integration/bindings/fixture/toolpad.yml
  test/integration/bindings/fixture/toolpad/.gitignore
  test/integration/bindings/fixture/toolpad/pages/bindings/page.yml
  test/integration/bindings/fixture/toolpad/pages/charset/page.yml
  test/integration/bindings/index.spec.ts
Labels: core

#2017 Remove hideControls and button type
  packages/toolpad-components/src/Button.tsx
  packages/toolpad-components/src/Form.tsx
Labels: core

#2002 Improve types for onChangeProp
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/NodeAttributeEditor.tsx
  packages/toolpad-app/src/toolpadComponents/layoutBox.ts
  packages/toolpad-core/src/createComponent.tsx
  packages/toolpad-core/src/createFunction.tsx
  packages/toolpad-core/src/types.ts
Labels: core

#1993 Add theming to docs
  docs/data/pages.ts
  docs/data/toolpad/building-ui/theming.md
  docs/pages/toolpad/building-ui/theming.js
  docs/public/static/toolpad/docs/building-ui/theme-1.png
  docs/public/static/toolpad/docs/building-ui/theme-2.png
Labels: docs

#1997 Add section about page configuration to docs
  docs/data/pages.ts
  docs/data/toolpad/building-ui/page-configuration.md
  docs/data/toolpad/data-binding.md
  docs/data/toolpad/deployment.md
  docs/pages/toolpad/building-ui/page-configuration.js
  docs/public/static/toolpad/docs/building-ui/display-mode-1.png
  docs/public/static/toolpad/docs/building-ui/page-parameters-1.png
  docs/public/static/toolpad/docs/building-ui/page-parameters-2.png
Labels: docs

#2030 version examples instead of using latest
  examples/custom-datagrid-column/package.json
Labels: core

#2018 Reorganize @mui/toolpad-core exports
  packages/toolpad-core/src/componentsContext.tsx
  packages/toolpad-core/src/createComponent.tsx
  packages/toolpad-core/src/index.tsx
  packages/toolpad-core/src/runtime.tsx
  packages/toolpad-core/src/server.ts
  packages/toolpad-core/src/types.ts
Labels: core

#2007 Replace polling for updates with websocket
  packages/toolpad-app/cli/appServer.ts
  packages/toolpad-app/cli/server.ts
  packages/toolpad-app/package.json
  packages/toolpad-app/src/server/liveProject.ts
  packages/toolpad-app/src/server/localMode.ts
  packages/toolpad-app/src/server/rpc.ts
  packages/toolpad-app/src/toolpad/AppState.tsx
  yarn.lock
Labels: core

#2021 Improve isolation of runtime from editor
  packages/toolpad-app/src/runtime/AppThemeProvider.tsx
  packages/toolpad-app/src/runtime/PreviewHeader.tsx
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/runtime/constants.ts
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/EditorCanvasHost.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/NodeAttributeEditor.tsx
  packages/toolpad-app/src/utils/useBoolean.ts
  packages/toolpad-components/package.json
  packages/toolpad-components/src/Text.tsx
  packages/toolpad-components/tsconfig.json
  packages/toolpad-components/tsup.config.ts
  packages/toolpad-core/package.json
  packages/toolpad-core/tsconfig.json
  packages/toolpad-core/tsup.config.ts
  packages/toolpad-utils/jest.config.js
  packages/toolpad-utils/package.json
  packages/toolpad-utils/src/hooks/index.ts
  packages/toolpad-utils/src/hooks/useBoolean.ts
  packages/toolpad-utils/src/hooks/usePageTitle.ts
  packages/toolpad-utils/tsconfig.json
  packages/toolpad-utils/tsup.config.ts
Labels: core

#2023 Upgrade monorepo
  .eslintrc.js
  yarn.lock
Labels: chore 🧹

#1427 Add Autocomplete component
  packages/toolpad-app/public/schemas/AutocompleteOptions.json
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentCatalog/ComponentCatalogItem.tsx
  packages/toolpad-app/src/toolpadComponents/index.tsx
  packages/toolpad-components/src/Autocomplete.tsx
  packages/toolpad-components/src/index.tsx
Labels: new feature

#2035 Fix race condition with initializing the canvas bridge
  packages/toolpad-app/src/canvas/ToolpadBridge.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/EditorCanvasHost.tsx
Labels: core

#2037 v0.1.12
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/create-toolpad-app/package.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
  packages/toolpad-utils/package.json
  packages/toolpad/package.json
Labels: release 🚀

#1996 Split data binding page in docs
  docs/data/pages.ts
  docs/data/toolpad/building-ui/canvas-and-inspector.md
  docs/data/toolpad/connecting-to-datasources/http-requests.md
  docs/data/toolpad/data-binding.md
  docs/data/toolpad/data-binding/binding-state.md
  docs/data/toolpad/data-binding/event-handling.md
  docs/pages/toolpad/data-binding/binding-state.js
  docs/pages/toolpad/data-binding/event-handling.js
Labels: docs

#2040 Reorganize core exports to ease extracting API docs
  packages/toolpad-core/src/browser.tsx
  packages/toolpad-core/src/createComponent.tsx
  packages/toolpad-core/src/createFunction.tsx
  packages/toolpad-core/src/createQuery.tsx
  packages/toolpad-core/src/index.tsx
  packages/toolpad-core/src/runtime.tsx
  packages/toolpad-core/src/server.ts
Labels: core

#2034 Ignore warning for first-child pseudo selector in Markdown component
  packages/toolpad-app/src/runtime/entrypoint.tsx
  test/integration/components/basic.spec.ts
  test/integration/components/fixture-basic/toolpad.yml
  test/integration/components/fixture-basic/toolpad/.gitignore
  test/integration/components/fixture-basic/toolpad/pages/components/page.yml
  test/integration/components/fixture-basic/toolpad/pages/select/page.yml
Labels: core

#2041 Fix property control tooltips showing over dialogs
  packages/toolpad-app/src/components/PropertyControl.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/NodeAttributeEditor.tsx
  packages/toolpad-app/src/toolpad/propertyControls/GridColumns.tsx
  packages/toolpad-app/src/toolpad/propertyControls/HorizontalAlign.tsx
  packages/toolpad-app/src/toolpad/propertyControls/Markdown.tsx
  packages/toolpad-app/src/toolpad/propertyControls/RowIdFieldSelect.tsx
  packages/toolpad-app/src/toolpad/propertyControls/SelectOptions.tsx
  packages/toolpad-app/src/toolpad/propertyControls/VerticalAlign.tsx
  packages/toolpad-app/src/toolpad/propertyControls/boolean.tsx
  packages/toolpad-app/src/toolpad/propertyControls/event.tsx
  packages/toolpad-app/src/toolpad/propertyControls/json.tsx
  packages/toolpad-app/src/toolpad/propertyControls/number.tsx
  packages/toolpad-app/src/toolpad/propertyControls/select.tsx
  packages/toolpad-app/src/toolpad/propertyControls/string.tsx
  packages/toolpad-app/src/toolpadComponents/layoutBox.ts
  packages/toolpad-components/src/DataGrid.tsx
  packages/toolpad-core/src/types.ts
Labels: core

#2043 [docs] Add product identifier to page context
  docs/pages/_app.js
  yarn.lock
Labels: docs

#2042 Fix orphaned node delete order
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/RenderOverlay.tsx
Labels: bug 🐛

#2054 pin toolpad packages versions again
  examples/custom-datagrid-column/package.json
  package.json
  packages/create-toolpad-app/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
  packages/toolpad/package.json
Labels: core

#2056 Fix function parameters
  packages/toolpad-app/src/api.ts
  packages/toolpad-app/src/toolpadDataSources/local/client.tsx
  packages/toolpad-app/src/toolpadDataSources/local/server.ts
  test/integration/backend-basic/fixture/toolpad.yml
  test/integration/backend-basic/fixture/toolpad/.gitignore
  test/integration/backend-basic/fixture/toolpad/pages/page1/page.yml
  test/integration/backend-basic/fixture/toolpad/resources/functions.ts
  test/integration/backend-basic/index.spec.ts
  test/playwright/localTest.ts
  test/utils/streams.ts
Labels: core

#2036 [refactor] Move toolpad components into the runtime
  .eslintrc.js
  packages/toolpad-app/src/canvas/ToolpadBridge.tsx
  packages/toolpad-app/src/canvas/index.tsx
  packages/toolpad-app/src/runtime/CanvasHooksContext.tsx
  packages/toolpad-app/src/runtime/ToolpadApp.spec.tsx
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/runtime/createRuntimeState.tsx
  packages/toolpad-app/src/runtime/toolpadComponents/index.tsx
  packages/toolpad-app/src/runtime/toolpadComponents/layoutBox.ts
  packages/toolpad-app/src/runtime/toolpadComponents/template.ts
  packages/toolpad-app/src/server/toolpadAppBuilder.ts
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/EditorCanvasHost.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/NodeAttributeEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/NodeDropArea.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/RenderOverlay.tsx
  packages/toolpad-app/src/toolpad/AppEditor/toolpadComponents.tsx
  packages/toolpad-app/src/toolpad/propertyControls/GridColumns.tsx
  packages/toolpad-app/src/types.ts
  packages/toolpad-core/src/runtime.tsx
Labels: core

#2060 Fix manual queries losing parameters when called
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  test/integration/backend-basic/fixture/toolpad/pages/page1/page.yml
  test/integration/backend-basic/fixture/toolpad/resources/functions.ts
  test/integration/backend-basic/index.spec.ts
Labels: bug 🐛

#2064 v0.1.13
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/create-toolpad-app/package.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
  packages/toolpad-utils/package.json
  packages/toolpad/package.json
  yarn.lock
Labels: release 🚀

#2066 Remove dead code from browser queries
  packages/toolpad-app/src/appDom/index.ts
  packages/toolpad-app/src/runtime/useDataQuery.ts
  packages/toolpad-app/src/toolpadDataSources/rest/client.tsx
  packages/toolpad-app/src/toolpadDataSources/rest/runtime.tsx
  packages/toolpad-app/src/toolpadDataSources/runtime.tsx
Labels: core

#2067 Add new example for QR code generator
  examples/qr-generator/README.md
  examples/qr-generator/package.json
  examples/qr-generator/toolpad/.gitignore
  examples/qr-generator/toolpad/pages/qrcode/page.yml
  examples/qr-generator/toolpad/resources/functions.ts
Labels: examples

#2076 Fix broken documentation links
  docs/data/toolpad/reference/api/create-function.md
  docs/data/toolpad/reference/api/index.md
Labels: docs

#2079 Avoid component catalog opening while hovering the snackbar
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentCatalog/ComponentCatalog.tsx
Labels: core

#2077 Add 404 page to application runtime
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  test/integration/pages/index.spec.ts
Labels: core

#2074 Several fixes around local functions
  packages/toolpad-app/cli/server.ts
  packages/toolpad-app/src/canvas/ToolpadBridge.tsx
  packages/toolpad-app/src/canvas/index.tsx
  packages/toolpad-app/src/projectEvents.ts
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/server/EnvManager.ts
  packages/toolpad-app/src/server/localMode.ts
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/EditorCanvasHost.tsx
  packages/toolpad-app/src/toolpad/AppState.tsx
  packages/toolpad-app/src/toolpadDataSources/local/server.ts
  packages/toolpad-app/src/toolpadDataSources/local/types.ts
  packages/toolpad-app/src/toolpadDataSources/rest/server.ts
  packages/toolpad-app/src/types.ts
  packages/toolpad-app/tsconfig.json
  packages/toolpad-core/package.json
  packages/toolpad-core/src/localRuntime.ts
  packages/toolpad-utils/src/events.ts
  packages/toolpad/package.json
  test/integration/backend-basic/index.spec.ts
Labels: core

#2083 [docs] Fix missing redirection for data binding
  docs/data/toolpad/building-ui/page-configuration.md
  docs/public/_redirects
Labels: docs, bug 🐛

#2090 Add redirect for moved file-schema page
  docs/public/_redirects
Labels: docs

#2078 [docs] Add docs update checklist item
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore 🧹

#2080 Allow inlining the proptype jsonschema
  packages/toolpad-app/public/schemas/AutocompleteOptions.json
  packages/toolpad-app/public/schemas/DataGridColumn.json
  packages/toolpad-app/public/schemas/DataGridColumns.json
  packages/toolpad-app/public/schemas/DataGridRows.json
  packages/toolpad-app/public/schemas/DataQuery.json
  packages/toolpad-app/public/schemas/SelectOptions.json
  packages/toolpad-app/src/toolpad/propertyControls/json.tsx
  packages/toolpad-components/src/DataGrid.tsx
  packages/toolpad-components/src/Select.tsx
  packages/toolpad-core/package.json
  packages/toolpad-core/src/types.ts
  yarn.lock
Labels: core

#2100 Fix React function ref warning for the row id selector component
  packages/toolpad-app/src/toolpad/propertyControls/RowIdFieldSelect.tsx
Labels: bug 🐛

#2102 Pin dependencies
  .yarnrc
  docs/package.json
  examples/showcase/package.json
  package.json
  packages/toolpad-app/package.json
  packages/toolpad-core/package.json
  packages/toolpad-utils/package.json
  yarn.lock
Labels: core

#2104 0.1.14
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/create-toolpad-app/package.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
  packages/toolpad-utils/package.json
  packages/toolpad/package.json
Labels: release 🚀
