Repository mui/toolpad, pull requests merged in 2023-04, with the labels that each got.

#1850 Remove obsolete onDelete datagrid property
  packages/toolpad-components/src/DataGrid.tsx
Labels: core

#1727 Try replacing tsc with tsup as build tool
  .eslintignore
  package.json
  packages/create-toolpad-app/package.json
  packages/create-toolpad-app/tsconfig.json
  packages/create-toolpad-app/tsup.config.ts
  packages/toolpad-app/jest.config.ts
  packages/toolpad-app/package.json
  packages/toolpad-app/pages/_document.tsx
  packages/toolpad-app/pages/api/runtime/[[...path]].ts
  packages/toolpad-app/tsconfig.json
  packages/toolpad-app/tsup.config.ts
  packages/toolpad-components/package.json
  packages/toolpad-components/src/DatePicker.tsx
  packages/toolpad-components/tsup.config.ts
  packages/toolpad-core/browser/package.json
  packages/toolpad-core/package.json
  packages/toolpad-core/server/package.json
  packages/toolpad-core/src/server.tsx
  packages/toolpad-core/tsconfig.json
  packages/toolpad-core/tsup.config.ts
  packages/toolpad/browser/package.json
  packages/toolpad/package.json
  packages/toolpad/server/package.json
  packages/toolpad/tsconfig.cjs.json
  packages/toolpad/tsconfig.json
  packages/toolpad/tsup.config.ts
  yarn.lock
Labels: core

#1856 Fix transform regression
  packages/toolpad-app/src/toolpadDataSources/applyTransform.ts
  test/integration/rest-basic/fixture/toolpad.yml
  test/integration/rest-basic/index.spec.ts
Labels: feature: Queries

#1860 Release 0.1.3
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/create-toolpad-app/package.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
  packages/toolpad/package.json
Labels: core

#1858 Clean dist dirs on rebuild
  packages/create-toolpad-app/tsup.config.ts
  packages/toolpad-app/tsup.config.ts
  packages/toolpad-components/tsup.config.ts
  packages/toolpad-core/tsup.config.ts
  packages/toolpad/tsup.config.ts
Labels: core

#1862 Refactor: extract custom components loading logic
  packages/toolpad-app/pages/api/runtime/[[...path]].ts
  packages/toolpad-app/pages/app-canvas/[[...path]].tsx
  packages/toolpad-app/pages/preview/[[...path]].tsx
  packages/toolpad-app/pages/prod/[[...path]].tsx
  packages/toolpad-app/src/canvas/index.tsx
  packages/toolpad-app/src/createRuntimeState.tsx
  packages/toolpad-app/src/runtime/AppModulesProvider.tsx
  packages/toolpad-app/src/runtime/ComponentsContext.tsx
  packages/toolpad-app/src/runtime/ToolpadApp.spec.tsx
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/runtime/loadCodeComponent.tsx
  packages/toolpad-app/src/runtime/loadDomComponents.tsx
  packages/toolpad-app/src/runtime/loadModule.tsx
  packages/toolpad-app/src/server/runtimeBuild.ts
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/PageModuleEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/PageOptionsPanel.tsx
  packages/toolpad-app/src/toolpadComponents/index.tsx
  packages/toolpad-app/src/utils/domView.ts
  packages/toolpad-core/package.json
  packages/toolpad-core/src/componentsContext.tsx
  packages/toolpad-core/src/createComponent.tsx
  packages/toolpad-core/src/utils/promises.ts
  packages/toolpad-core/src/utils/types.ts
Labels: core

#1829 Docs-update
  docs/data/pages.ts
  docs/data/toolpad/data-binding.md
  docs/data/toolpad/deployment.md
  docs/pages/toolpad/deployment.js
  docs/public/static/toolpad/docs/data-binding/bind-10.png
  docs/public/static/toolpad/docs/data-binding/bind-11.png
Labels: docs

#1878 Factor out in-memory toolpad project
  packages/toolpad-app/pages/api/data/[pageName]/[queryName].ts
  packages/toolpad-app/pages/api/rpc.ts
  packages/toolpad-app/scripts/buildRuntime.mts
  packages/toolpad-app/src/server/data.ts
  packages/toolpad-app/src/server/liveProject.ts
  packages/toolpad-app/src/server/localMode.ts
  packages/toolpad-app/src/toolpadDataSources/local/server.ts
  packages/toolpad-app/src/utils/fs.ts
Labels: core

#1879 v0.1.4
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/create-toolpad-app/package.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
  packages/toolpad/package.json
Labels: core

#1880 Update release instructions
  RELEASE.md
Labels: docs

#1884 Update playwright to latest
  .circleci/config.yml
  package.json
  yarn.lock
Labels: dependencies

#1885 Add missing extraneous dependencies
  .eslintrc.js
  packages/toolpad-app/package.json
  yarn.lock
Labels: bug 🐛, regression

#1886 v0.1.5
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/create-toolpad-app/package.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
  packages/toolpad/package.json
Labels: core

#1888 Fix app theming
  .eslintignore
  packages/toolpad-app/pages/_app.tsx
  packages/toolpad-app/src/ThemeContext.tsx
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/toolpad/Toolpad.tsx
  test/integration/theme/fixture/toolpad.yml
  test/integration/theme/fixture/toolpad/.gitignore
  test/integration/theme/fixture/toolpad/components/Test.tsx
  test/integration/theme/fixture/toolpad/pages/Page1/page.yml
  test/integration/theme/index.spec.ts
  test/integration/theme/prod.spec.ts
  test/models/shared.ts
Labels: core, regression

#1889 Release 0 1 6
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/create-toolpad-app/package.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
  packages/toolpad/package.json
Labels: core

#1786 [website] Landing page design tweaks
  docs/pages/toolpad/index.js
  docs/src/components/landing/Banner.js
  docs/src/components/landing/CardGrid.js
  docs/src/components/landing/DemoVideo.js
  docs/src/components/landing/Hero.js
  docs/src/components/landing/Marquee.js
  docs/src/components/landing/PricingTable.js
  docs/src/components/landing/SignUp.js
  docs/src/components/landing/UseCases.js
  docs/src/content/upvote.js
Labels: website

#1893 Update links on contributing guide
  CONTRIBUTING.md
Labels: docs

#1598 Form component
  packages/toolpad-app/src/appDom/index.ts
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/toolpad/AppEditor/NodeNameEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentCatalog/ComponentCatalog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/EditorCanvasHost.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/NodeHud.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/RenderOverlay.tsx
  packages/toolpad-app/src/toolpadComponents/index.tsx
  packages/toolpad-components/src/Button.tsx
  packages/toolpad-components/src/DatePicker.tsx
  packages/toolpad-components/src/FilePicker.tsx
  packages/toolpad-components/src/Form.tsx
  packages/toolpad-components/src/Paper.tsx
  packages/toolpad-components/src/Select.tsx
  packages/toolpad-components/src/Tabs.tsx
  packages/toolpad-components/src/TextField.tsx
  packages/toolpad-components/src/index.tsx
  packages/toolpad-core/src/index.tsx
  packages/toolpad-core/src/runtime.tsx
  packages/toolpad-core/src/types.ts
  test/integration/data-grid/basic.spec.ts
  test/integration/editor/new.spec.ts
  test/integration/pages/index.spec.ts
  test/integration/propControls/basic.spec.ts
Labels: feature: App Editor

#1863 Fix: Better represent the new direction on landing
  docs/src/content/features.js
Labels: website

#1907 Show border on hover in interactive nodes
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/NodeHud.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/RenderOverlay.tsx
Labels: bug 🐛, regression

#1908 Deprecate `createQuery` and replace with `createFunction`
  docs/data/toolpad/connecting-to-datasources/serverside-javascript.md
  packages/toolpad-app/src/toolpadDataSources/local/client.tsx
  packages/toolpad-app/src/toolpadDataSources/local/server.ts
  packages/toolpad-app/src/toolpadDataSources/local/types.ts
  packages/toolpad-components/src/DataGrid.tsx
  packages/toolpad-core/src/constants.ts
  packages/toolpad-core/src/createFunction.tsx
  packages/toolpad-core/src/createQuery.tsx
  packages/toolpad-core/src/index.tsx
  packages/toolpad-core/src/server.ts
  test/integration/backend-basic/fixture/toolpad/queries.ts
Labels: core

#1883 Update MUI monorepo
  SECURITY.md
  docs/next.config.mjs
  yarn.lock
Labels: docs

#1895 Use npm registry to check for new versions
  packages/toolpad-app/package.json
  packages/toolpad-app/pages/api/rpc.ts
  packages/toolpad-app/src/constants.ts
  packages/toolpad-app/src/server/getLatestRelease.ts
  packages/toolpad-app/src/server/versionInfo.ts
  packages/toolpad-app/src/toolpad/ToolpadShell/Header/UserFeedback/index.tsx
  yarn.lock
Labels: core

#1910 Fix Windows issues (WIP)
  packages/toolpad-app/scripts/typings.mts
  packages/toolpad-app/src/toolpadDataSources/local/server.ts
Labels: bug 🐛

#1881 New vite based application runtime
  .circleci/config.yml
  .eslintrc.js
  package.json
  packages/toolpad-app/cli/appBuilder.ts
  packages/toolpad-app/cli/appServer.ts
  packages/toolpad-app/cli/index.ts
  packages/toolpad-app/cli/server.ts
  packages/toolpad-app/package.json
  packages/toolpad-app/src/config.ts
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/runtime/entrypoint.tsx
  packages/toolpad-app/src/server/liveProject.ts
  packages/toolpad-app/src/server/localMode.ts
  packages/toolpad-app/src/server/toolpadAppBuilder.ts
  packages/toolpad-app/src/server/toolpadAppServer.ts
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/EditorCanvasHost.tsx
  packages/toolpad-app/src/toolpad/ToolpadShell/Header/index.tsx
  packages/toolpad-app/src/toolpadDataSources/local/server.ts
  packages/toolpad-app/src/utils/fs.ts
  packages/toolpad-app/src/utils/http.ts
  packages/toolpad-app/src/utils/react.tsx
  packages/toolpad-app/tsup.config.ts
  packages/toolpad-components/src/TextField.tsx
  packages/toolpad-core/src/utils/Emitter.ts
  test/integration/codeComponents/fixture/toolpad/.gitignore
  test/integration/codeComponents/fixture/toolpad/components/MyBarChart.tsx
  test/integration/codeComponents/fixture/toolpad/pages/page/page.yml
  test/integration/codeComponents/index.spec.ts
  test/integration/data-grid/basic.spec.ts
  test/integration/data-grid/fixture-basic/toolpad.yml
  test/integration/duplication/index.spec.ts
  test/integration/playwright.config.ts
  test/integration/rest-basic/index.spec.ts
  test/integration/theme/fixture/toolpad/components/Test.tsx
  test/models/ToolpadEditor.ts
  test/models/ToolpadRuntime.ts
  test/playwright/localTest.ts
  test/playwright/test.ts
  yarn.lock
Labels: core

#1795 Add folder as argument to `create-toolpad-app`
  README.md
  packages/create-toolpad-app/src/index.ts
  packages/create-toolpad-app/tsconfig.json
  test/integration/editor/new.spec.ts
Labels: core

#1923 Fix gitignore file creation log message
  packages/toolpad-app/src/server/localMode.ts
Labels: core

#1916 Form component integration tests
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/RenderOverlay.tsx
  test/integration/components/fixture-form/toolpad/.gitignore
  test/integration/components/fixture-form/toolpad/pages/form/page.yml
  test/integration/components/fixture-form/toolpad/resources/functions.ts
  test/integration/components/form.spec.ts
  test/integration/components/test.txt
Labels: test

#1924 Import correct font in vite runtime
  packages/toolpad-app/src/server/toolpadAppBuilder.ts
Labels: core

#1927 [docs] Polish a bit the docs
  CHANGELOG.md
  docs/data/pages.ts
  docs/data/toolpad/building-ui/canvas-and-inspector.md
  docs/data/toolpad/building-ui/component-library.md
  docs/data/toolpad/building-ui/custom-components.md
  docs/data/toolpad/building-ui/data-grid-component.md
  docs/data/toolpad/connecting-to-datasources/connections.md
  docs/data/toolpad/connecting-to-datasources/function.md
  docs/data/toolpad/connecting-to-datasources/google-sheets.md
  docs/data/toolpad/connecting-to-datasources/postgresql.md
  docs/data/toolpad/connecting-to-datasources/queries.md
  docs/data/toolpad/connecting-to-datasources/serverside-http-request.md
  docs/data/toolpad/connecting-to-datasources/serverside-javascript.md
  docs/data/toolpad/data-binding.md
  docs/data/toolpad/deployment.md
  docs/data/toolpad/getting-started/overview.md
  docs/data/toolpad/getting-started/quickstart.md
  packages/toolpad-app/src/toolpadComponents/index.tsx
  packages/toolpad-components/src/DataGrid.tsx
  packages/toolpad-components/src/DatePicker.tsx
  packages/toolpad-components/src/FilePicker.tsx
  test/integration/editor/new.spec.ts
  test/integration/file-picker/index.spec.ts
  test/integration/propControls/basic.spec.ts
  test/integration/undo-redo/basic.spec.ts
Labels: docs

#1926 Form component
  packages/toolpad-app/src/appDom/index.ts
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/toolpad/AppEditor/NodeNameEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentCatalog/ComponentCatalog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/EditorCanvasHost.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/RenderOverlay.tsx
  packages/toolpad-app/src/toolpadComponents/index.tsx
  packages/toolpad-components/src/Button.tsx
  packages/toolpad-components/src/DatePicker.tsx
  packages/toolpad-components/src/FilePicker.tsx
  packages/toolpad-components/src/Form.tsx
  packages/toolpad-components/src/Paper.tsx
  packages/toolpad-components/src/Select.tsx
  packages/toolpad-components/src/Tabs.tsx
  packages/toolpad-components/src/TextField.tsx
  packages/toolpad-components/src/index.tsx
  packages/toolpad-core/src/runtime.tsx
  packages/toolpad-core/src/types.ts
  test/integration/bindings/fixture-navigation/toolpad/.generated/functions/toolpad_main.js
  test/integration/components/fixture-form/toolpad/.gitignore
  test/integration/components/fixture-form/toolpad/pages/form/page.yml
  test/integration/components/fixture-form/toolpad/resources/functions.ts
  test/integration/components/form.spec.ts
  test/integration/components/test.txt
  test/integration/data-grid/basic.spec.ts
  test/integration/editor/new.spec.ts
  test/integration/pages/index.spec.ts
  test/integration/propControls/basic.spec.ts
Labels: feature: Components

#1912 Fix: Use `nanonid/non-secure` instead of `cuid`
  packages/toolpad-app/package.json
  packages/toolpad-app/src/appDom/index.ts
  packages/toolpad-app/src/components/MonacoEditor.tsx
  packages/toolpad-app/src/server/localMode.ts
  packages/toolpad-app/tsup.config.ts
  yarn.lock
Labels: core

#1932 Fix: Local installation needs new resolution
  CONTRIBUTING.md
Labels: core

#1936 Add link to open example in CodeSandbox
  examples/custom-datagrid-column/README.md
  examples/custom-datagrid-column/package.json
  packages/toolpad-app/next.config.mjs
Labels: docs

#1920 Replace next api routes with express
  packages/toolpad-app/cli/server.ts
  packages/toolpad-app/next.config.mjs
  packages/toolpad-app/pages/api/data/[pageName]/[queryName].ts
  packages/toolpad-app/pages/api/dataSources/[dataSource]/[...path].ts
  packages/toolpad-app/pages/api/health-check.ts
  packages/toolpad-app/pages/preview/[[...path]].tsx
  packages/toolpad-app/pages/prod/[[...path]].tsx
  packages/toolpad-app/src/server/data.ts
  packages/toolpad-app/src/server/rpc.ts
  packages/toolpad-app/src/server/toolpadAppBuilder.ts
  packages/toolpad-app/src/server/toolpadAppServer.ts
  packages/toolpad-app/src/utils/http.ts
  packages/toolpad-app/tsup.config.ts
  test/integration/components/form.spec.ts
  test/integration/editor/new.spec.ts
  test/models/ToolpadEditor.ts
Labels: core

#1925 Add page name as an alias for routing in the runtime
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  test/models/ToolpadHome.ts
  test/models/ToolpadRuntime.ts
Labels: core

#1939 Release 0.1.8
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/create-toolpad-app/package.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
  packages/toolpad-utils/package.json
  packages/toolpad/package.json
Labels: core

#1938 Make vite runtime default
  examples/custom-datagrid-column/package.json
  packages/toolpad-app/cli/index.ts
  packages/toolpad-app/cli/server.ts
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/EditorCanvasHost.tsx
  test/playwright/localTest.ts
Labels: core
