Repository mui/toolpad, pull requests merged in 2023-10, with the labels that each got.

#2746 Move server files to the src folder
  packages/toolpad-app/cli/index.ts
  packages/toolpad-app/src/server/appBuilder.ts
  packages/toolpad-app/src/server/appServer.ts
  packages/toolpad-app/src/server/index.ts
  packages/toolpad-app/tsup.config.ts
Labels: core

#2674 format IDE code
  packages/toolpad-app/src/server/localMode.ts
  packages/toolpad-app/src/server/rpcServer.ts
  packages/toolpad-app/src/toolpad/AppEditor/BindingEditor.tsx
  packages/toolpad-app/src/utils/prettier.ts
Labels: core

#2730 Add global sidebar
  packages/toolpad-app/src/constants.ts
  packages/toolpad-app/src/routes.ts
  packages/toolpad-app/src/runtime/AppLayout.tsx
  packages/toolpad-app/src/toolpad/AppEditor/AppEditorShell.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PagesExplorer/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/index.tsx
  packages/toolpad-app/src/toolpad/AppState.tsx
  packages/toolpad-app/src/toolpad/Toolpad.tsx
  packages/toolpad-app/src/toolpad/ToolpadShell/ToolpadNavigation.tsx
  packages/toolpad-app/src/toolpad/ToolpadShell/index.tsx
  packages/toolpad-app/src/utils/domView.ts
Labels: design: ui, design: ux

#2692 add a search box on the top
  packages/toolpad-app/src/runtime/toolpadComponents/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentCatalog/ComponentCatalog.tsx
Labels: new feature

#2745 Fix editor failing to open
  docs/data/toolpad/how-to-guides/editor-path.md
  packages/toolpad-app/src/components/OpenCodeEditor.tsx
  packages/toolpad-app/src/server/localMode.ts
Labels: core

#2751 v0.1.31
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/create-toolpad-app/package.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
  packages/toolpad-utils/package.json
Labels: release 🚀

#2755 Move the perf cascade css file to the HarViewer component
  packages/toolpad-app/src/components/HarViewer.tsx
  packages/toolpad-app/src/toolpad/main.tsx
Labels: enhancement

#2747 Allow integrating toolpad applications in a custom server
  examples/custom-server/index.mjs
  examples/custom-server/package.json
  examples/custom-server/toolpad/.gitignore
  examples/custom-server/toolpad/pages/page/page.yml
  package.json
  packages/toolpad-app/cli/index.ts
  packages/toolpad-app/package.json
  packages/toolpad-app/scripts/typings.mts
  packages/toolpad-app/src/canvas/index.tsx
  packages/toolpad-app/src/config.ts
  packages/toolpad-app/src/exports/index.ts
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/server/FunctionsManager.ts
  packages/toolpad-app/src/server/appBuilderWorker.ts
  packages/toolpad-app/src/server/appServerWorker.ts
  packages/toolpad-app/src/server/functionsDevWorker.ts
  packages/toolpad-app/src/server/functionsShared.ts
  packages/toolpad-app/src/server/index.ts
  packages/toolpad-app/src/server/localMode.ts
  packages/toolpad-app/src/server/projectRoot.ts
  packages/toolpad-app/src/server/toolpadAppBuilder.ts
  packages/toolpad-app/src/server/toolpadAppServer.ts
  packages/toolpad-app/src/toolpadDataSources/postgres/server.ts
  packages/toolpad-app/src/types.ts
  packages/toolpad-app/src/utils/prettier.ts
  packages/toolpad-app/tsup.config.ts
  packages/toolpad-utils/src/fs.ts
Labels: core, new feature

#2756 Simplify the editor RPC implementation
  packages/toolpad-app/src/components/OpenCodeEditor.tsx
  packages/toolpad-app/src/rpcClient.ts
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/runtime/useDataQuery.ts
  packages/toolpad-app/src/server/rpc.ts
  packages/toolpad-app/src/server/rpcRuntimeServer.ts
  packages/toolpad-app/src/server/rpcServer.ts
  packages/toolpad-app/src/toolpad/AppEditor/NodeNameEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/QueryEditor/QueryEditorDialog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PagesExplorer/CreateCodeComponentNodeDialog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PagesExplorer/index.tsx
  packages/toolpad-app/src/toolpad/AppState.tsx
  packages/toolpad-app/src/toolpad/Toolpad.tsx
  packages/toolpad-app/src/toolpad/index.ts
  packages/toolpad-app/src/toolpad/main.tsx
  packages/toolpad-app/src/toolpadDataSources/useFetchPrivate.ts
Labels: core

#2644 Introduce Data providers
  .eslintrc.js
  docs/data/pages.ts
  docs/data/toolpad/concepts/data-providers.md
  docs/data/toolpad/reference/api/create-data-provider.md
  docs/data/toolpad/reference/api/index.md
  docs/data/toolpad/reference/components/data-grid.md
  docs/pages/toolpad/concepts/data-providers.js
  docs/pages/toolpad/reference/api/create-data-provider.js
  docs/public/static/toolpad/docs/concepts/data-providers/create-data-provider-dialog.png
  docs/public/static/toolpad/docs/concepts/data-providers/create-data-provider.png
  docs/public/static/toolpad/docs/concepts/data-providers/open-editor.png
  docs/public/static/toolpad/docs/concepts/data-providers/rows-source.png
  docs/src/modules/components/DocsImage.tsx
  packages/toolpad-app/src/components/OpenCodeEditor.tsx
  packages/toolpad-app/src/constants.ts
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/runtime/useDataProvider.ts
  packages/toolpad-app/src/server/DataManager.ts
  packages/toolpad-app/src/server/FunctionsManager.ts
  packages/toolpad-app/src/server/appServerWorker.ts
  packages/toolpad-app/src/server/functionsDevWorker.ts
  packages/toolpad-app/src/server/functionsTypesWorker.ts
  packages/toolpad-app/src/server/localMode.ts
  packages/toolpad-app/src/server/rpcRuntimeServer.ts
  packages/toolpad-app/src/server/rpcServer.ts
  packages/toolpad-app/src/server/toolpadAppBuilder.ts
  packages/toolpad-app/src/server/toolpadAppServer.ts
  packages/toolpad-app/src/toolpad/AppEditor/HierarchyExplorer/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentPanel.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/EditorCanvasHost.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/PageEditorProvider.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/RenderPanel.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PagesExplorer/CreateCodeComponentNodeDialog.tsx
  packages/toolpad-app/src/toolpad/AppState.tsx
  packages/toolpad-app/src/toolpad/propertyControls/DataProviderSelector.tsx
  packages/toolpad-app/src/toolpad/propertyControls/GridColumns.tsx
  packages/toolpad-app/src/toolpad/propertyControls/ToggleButtons.tsx
  packages/toolpad-app/src/toolpad/propertyControls/select.tsx
  packages/toolpad-app/src/toolpadDataSources/local/client.tsx
  packages/toolpad-app/src/types.ts
  packages/toolpad-components/package.json
  packages/toolpad-components/src/DataGrid.tsx
  packages/toolpad-core/src/index.tsx
  packages/toolpad-core/src/runtime.tsx
  packages/toolpad-core/src/server.ts
  packages/toolpad-core/src/types.ts
  test/integration/backend-basic/fixture/toolpad/pages/basic/page.yml
  test/integration/backend-basic/fixture/toolpad/pages/dataProviders/page.yml
  test/integration/backend-basic/fixture/toolpad/pages/extractedTypes/page.yml
  test/integration/backend-basic/fixture/toolpad/pages/serialization/page.yml
  test/integration/backend-basic/fixture/toolpad/resources/myCursorData.ts
  test/integration/backend-basic/fixture/toolpad/resources/myIndexData.ts
  test/integration/backend-basic/index.spec.ts
  test/integration/mysql-basic/index.spec.ts
Labels: new feature

#2728 New page creation UX
  packages/toolpad-app/src/components/EditableTreeItem.tsx
  packages/toolpad-app/src/toolpad/AppEditor/ExplorerHeader.tsx
  packages/toolpad-app/src/toolpad/AppEditor/HierarchyExplorer/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/NodeMenu.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PagesExplorer/index.tsx
  packages/toolpad-app/src/utils/dom.ts
  packages/toolpad-utils/src/comparators.spec.ts
  packages/toolpad-utils/src/comparators.ts
  test/integration/duplication/index.spec.ts
  test/integration/editor/deleteLast.spec.ts
  test/integration/editor/index.spec.ts
  test/integration/editor/new.spec.ts
  test/integration/pages/fixture/toolpad/pages/page1/page.yml
  test/integration/pages/fixture/toolpad/pages/page2/page.yml
  test/integration/pages/index.spec.ts
  test/models/ToolpadEditor.ts
Labels: enhancement

#2768 Block next.js from updating
  renovate.json
Labels: dependencies

#2763 Add Markdown and Link components
  packages/toolpad-app/src/runtime/toolpadComponents/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentCatalog/ComponentCatalog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentCatalog/ComponentCatalogItem.tsx
Labels: new feature

#2764 Use toggle buttons for text mode property
  packages/toolpad-components/src/Text.tsx
Labels: enhancement

#2766 Use a context to distribute project API
  packages/toolpad-app/src/api.ts
  packages/toolpad-app/src/projectApi.tsx
  packages/toolpad-app/src/projectEvents.ts
  packages/toolpad-app/src/projectEvents.tsx
  packages/toolpad-app/src/rpcClient.ts
  packages/toolpad-app/src/runtime/ToolpadApp.spec.tsx
  packages/toolpad-app/src/runtime/api.ts
  packages/toolpad-app/src/server/index.ts
  packages/toolpad-app/src/server/projectRpcServer.ts
  packages/toolpad-app/src/server/runtimeRpcServer.ts
  packages/toolpad-app/src/server/toolpadAppServer.ts
  packages/toolpad-app/src/toolpad/AppEditor/BindingEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/NodeNameEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/QueryEditor/QueryEditorDialog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/RenderPanel.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PagesExplorer/CreateCodeComponentNodeDialog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PagesExplorer/index.tsx
  packages/toolpad-app/src/toolpad/AppState.tsx
  packages/toolpad-app/src/toolpad/OpenCodeEditor.tsx
  packages/toolpad-app/src/toolpad/Toolpad.tsx
  packages/toolpad-app/src/toolpad/ToolpadShell/Header/UserFeedback/index.tsx
  packages/toolpad-app/src/toolpad/propertyControls/DataProviderSelector.tsx
  packages/toolpad-app/src/toolpadDataSources/context.tsx
  packages/toolpad-app/src/toolpadDataSources/local/client.tsx
  packages/toolpad-app/src/toolpadDataSources/useFetchPrivate.ts
Labels: core

#2779 Remove container sx default
  docs/data/toolpad/reference/components/container.md
  packages/toolpad-components/src/Container.tsx
Labels: enhancement

#2780 Fix createDataProvider imports in the integration tests
  test/integration/backend-basic/fixture/toolpad/resources/myCursorData.ts
  test/integration/backend-basic/fixture/toolpad/resources/myIndexData.ts
Labels: core

#2778 [core] Smoothen edges on the new Editable Tree component
  packages/toolpad-app/src/components/EditableTreeItem.tsx
  packages/toolpad-app/src/toolpad/AppEditor/NodeMenu.tsx
Labels: core, bug 🐛

#2791 0.1.32
  CHANGELOG.md
  docs/package.json
  lerna.json
  package.json
  packages/create-toolpad-app/package.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
  packages/toolpad-utils/package.json
Labels: release 🚀

#2783 Turn integration tests into a yarn workspace
  test/integration/backend-basic/base.spec.ts
  test/integration/backend-basic/baseProd.spec.ts
  test/integration/backend-basic/index.spec.ts
  test/integration/backend-basic/prod.spec.ts
  test/integration/basic-auth/prod.spec.ts
  test/integration/bindings/index.spec.ts
  test/integration/bindings/navigation.spec.ts
  test/integration/codeComponents/index.spec.ts
  test/integration/components/basic.spec.ts
  test/integration/components/chart.spec.ts
  test/integration/components/form.spec.ts
  test/integration/components/list.spec.ts
  test/integration/data-grid/basic.spec.ts
  test/integration/data-grid/custom.spec.ts
  test/integration/deploy/index.spec.ts
  test/integration/duplication/index.spec.ts
  test/integration/editor/fixture/toolpad/components/FullWidth.tsx
  test/integration/editor/index.spec.ts
  test/integration/file-picker/index.spec.ts
  test/integration/mysql-basic/index.spec.ts
  test/integration/mysql-basic/mysqlDom.json
  test/integration/pages/index.spec.ts
  test/integration/propControls/basic.spec.ts
  test/integration/propControls/defaults.spec.ts
  test/integration/propControls/fixture-defaults/toolpad/components/myComponent.tsx
  test/integration/rest-basic/index.spec.ts
  test/integration/runtime-basic/index.spec.ts
  test/integration/theme/index.spec.ts
  test/integration/theme/prod.spec.ts
  test/integration/undo-redo/basic.spec.ts
  test/integration/undo-redo/multiple-pages.spec.ts
  test/package.json
  test/playwright/localTest.ts
  test/playwright/test.ts
  test/visual/components/index.spec.ts
Labels: core

#2790 Fix creating new page with blur and default name + scroll only below explorer headers
  packages/toolpad-app/src/components/EditableTreeItem.tsx
  packages/toolpad-app/src/toolpad/AppEditor/ExplorerHeader.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PagesExplorer/index.tsx
Labels: feature: App Editor, enhancement

#2786 Remove babel-plugin-transform-rename-import
  docs/babel.config.js
  docs/next.config.mjs
  docs/package.json
  package.json
  yarn.lock
Labels: docs

#2788 Isolate project runtime from editor
  packages/toolpad-app/src/config.ts
  packages/toolpad-app/src/constants.ts
  packages/toolpad-app/src/project.tsx
  packages/toolpad-app/src/projectApi.tsx
  packages/toolpad-app/src/projectEvents.tsx
  packages/toolpad-app/src/rpcClient.ts
  packages/toolpad-app/src/server/DataManager.ts
  packages/toolpad-app/src/server/appServerWorker.ts
  packages/toolpad-app/src/server/index.ts
  packages/toolpad-app/src/server/localMode.ts
  packages/toolpad-app/src/server/projectRpcServer.ts
  packages/toolpad-app/src/server/toolpadAppServer.ts
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/EditorCanvasHost.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/QueryEditor/QueryEditorDialog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PagePanel.tsx
  packages/toolpad-app/src/toolpad/Toolpad.tsx
  packages/toolpad-app/src/toolpad/main.tsx
  packages/toolpad-app/src/toolpadDataSources/googleSheets/server.ts
  packages/toolpad-app/src/toolpadDataSources/rest/client.tsx
  packages/toolpad-app/src/toolpadDataSources/rest/server.ts
  packages/toolpad-app/src/toolpadDataSources/rest/shared.ts
  packages/toolpad-app/src/toolpadDataSources/server.ts
  packages/toolpad-app/src/types.ts
Labels: core

#2794 Improve release docs wording
  RELEASE.md
Labels: enhancement

#2798 Add tests for custom server
  packages/toolpad-app/src/server/EnvManager.ts
  packages/toolpad-app/src/server/FunctionsManager.ts
  test/integration/backend-basic/base.spec.ts
  test/integration/backend-basic/baseProd.spec.ts
  test/integration/backend-basic/index.spec.ts
  test/integration/backend-basic/prod.spec.ts
  test/integration/basic-auth/prod.spec.ts
  test/integration/bindings/index.spec.ts
  test/integration/bindings/navigation.spec.ts
  test/integration/codeComponents/index.spec.ts
  test/integration/components/basic.spec.ts
  test/integration/components/chart.spec.ts
  test/integration/components/form.spec.ts
  test/integration/components/list.spec.ts
  test/integration/custom-server/dev.spec.ts
  test/integration/custom-server/prod.spec.ts
  test/integration/data-grid/basic.spec.ts
  test/integration/data-grid/custom.spec.ts
  test/integration/deploy/index.spec.ts
  test/integration/duplication/index.spec.ts
  test/integration/editor/index.spec.ts
  test/integration/editor/new.spec.ts
  test/integration/file-picker/index.spec.ts
  test/integration/pages/index.spec.ts
  test/integration/propControls/basic.spec.ts
  test/integration/propControls/defaults.spec.ts
  test/integration/rest-basic/index.spec.ts
  test/integration/runtime-basic/index.spec.ts
  test/integration/theme/index.spec.ts
  test/integration/theme/prod.spec.ts
  test/integration/undo-redo/basic.spec.ts
  test/integration/undo-redo/multiple-pages.spec.ts
  test/package.json
  test/playwright/localTest.ts
  test/tsconfig.json
  test/visual/components/index.spec.ts
Labels: test

#2797 Add password option to TextField Component
  docs/data/toolpad/reference/components/text-field.md
  packages/toolpad-app/src/runtime/toolpadComponents/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentCatalog/ComponentCatalog.tsx
  packages/toolpad-components/src/TextField.tsx
Labels: enhancement

#2796 Changed MenuItem to ToggleButton (#2776)
  docs/public/static/toolpad/docs/concepts/display-mode/display-mode.png
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/PageOptionsPanel.tsx
Labels: feature: App Editor, enhancement

#2811 Run prettier on project
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/PageOptionsPanel.tsx
Labels: chore 🧹

#2726 Link WASM example to overview page and improve crud app
  docs/public/static/toolpad/marketing/with-prisma-data-provider.png
  docs/public/static/toolpad/marketing/with-wasm.png
  docs/src/modules/components/ExamplesGrid.js
  examples/basic-crud-app/toolpad/pages/AdminApp/page.yml
  examples/custom-datagrid-column/README.md
  examples/datagrid-columns/README.md
  examples/dog-app/README.md
  examples/google-sheet/README.md
  examples/with-wasm/README.md
Labels: docs

#2632 [docs] Add 'Why Toolpad?'
  docs/data/pages.ts
  docs/data/toolpad/getting-started/why-toolpad.md
  docs/pages/toolpad/getting-started/why-toolpad.js
  docs/public/static/toolpad/docs/getting-started/why-toolpad/why-toolpad.png
Labels: docs

#2807 Add support page
  docs/data/pages.ts
  docs/data/toolpad/getting-started/support.md
  docs/pages/toolpad/support/support.js
Labels: docs

#2813 [docs] Update Data Providers
  docs/data/pages.ts
  docs/data/toolpad/concepts/data-providers.md
  docs/public/static/toolpad/docs/concepts/data-providers/data-provider-1.mp4
  docs/public/static/toolpad/docs/concepts/data-providers/data-provider-2.mp4
Labels: docs

#2814 v0.1.33
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/create-toolpad-app/package.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
  packages/toolpad-utils/package.json
Labels: release 🚀

#2812 Fix flaky tests
  packages/toolpad-components/src/Chart.tsx
  packages/toolpad-components/src/Form.tsx
  test/integration/data-grid/basic.spec.ts
  test/models/ToolpadEditor.ts
  test/utils/clickCenter.ts
Labels: test

#2824 [docs] A few Support page improvements
  docs/data/pages.ts
  docs/data/toolpad/getting-started/support.md
  docs/pages/toolpad/getting-started/support.js
  docs/public/_redirects
  packages/toolpad-app/src/toolpad/ToolpadShell/Header/UserFeedback/index.tsx
Labels: docs

#2825 [core] Monorepo upgrade
  yarn.lock
Labels: core

#2832 Update Support URL in Help menu
  packages/toolpad-app/src/toolpad/ToolpadShell/Header/UserFeedback/index.tsx
Labels: chore 🧹

#2833 [release] v0.1.34
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/create-toolpad-app/package.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
  packages/toolpad-utils/package.json
Labels: release 🚀

#2843 Remove crypto-js
  packages/toolpad-app/package.json
  packages/toolpad-app/src/server/secrets.ts
  yarn.lock
Labels: core
