Repository mui/toolpad, pull requests merged in 2023-06, with the labels that each got.

#2106 Update @mui/monorepo
  yarn.lock
Labels: dependencies

#1934 Set minimum node at 16.14.2
  .circleci/config.yml
  package.json
  packages/create-toolpad-app/package.json
  packages/create-toolpad-app/src/index.ts
  packages/toolpad/package.json
Labels: core

#2111 Add codesandbox CI
  .codesandbox/ci.json
Labels: core

#2116 [core] Avoid PR sandbox notifications
  .codesandbox/ci.json
Labels: core

#2103 Create global functions manager
  packages/toolpad-app/src/server/FunctionsManager.ts
  packages/toolpad-app/src/server/functionsDevWorker.ts
  packages/toolpad-app/src/server/localMode.ts
  packages/toolpad-app/src/toolpadDataSources/local/server.ts
  packages/toolpad-app/src/utils/paths.ts
  packages/toolpad-app/tsconfig.json
  packages/toolpad-app/tsup.config.ts
  packages/toolpad-core/src/localRuntime.ts
  packages/toolpad-core/src/server.ts
  test/integration/backend-basic/fixture/toolpad/pages/page1/page.yml
  test/integration/backend-basic/fixture/toolpad/resources/functions.ts
  test/integration/backend-basic/index.spec.ts
Labels: core

#2129 Restrict node version for renovatebot
  renovate.json
Labels: dependencies

#2073 Improve error handling in image and datagrid
  .eslintrc.js
  packages/toolpad-components/package.json
  packages/toolpad-components/src/DataGrid.tsx
  packages/toolpad-components/src/Image.tsx
  packages/toolpad-components/src/components/ErrorOverlay.tsx
Labels: core

#2123 [docs] Fix docs issues
  docs/data/toolpad/building-ui/theming.md
  docs/pages/toolpad/reference/file-schema/index.tsx
Labels: docs

#2131 Try fixing build on windows
  packages/toolpad-app/src/server/toolpadAppBuilder.ts
Labels: core

#2124 add ts declaration for package and check node version on initial star…
  packages/create-toolpad-app/package.json
  packages/create-toolpad-app/public/.gitignore
  packages/create-toolpad-app/src/index.ts
  packages/create-toolpad-app/src/packageType.ts
  packages/create-toolpad-app/src/util.ts
  packages/create-toolpad-app/tests/index.spec.ts
  packages/create-toolpad-app/tsconfig.json
  packages/create-toolpad-app/tsup.config.ts
  yarn.lock
Labels: create-toolpad-app

#2109 Allow arbitrary env variables in bindings, use process.env
  packages/toolpad-app/src/server/EnvManager.ts
  packages/toolpad-app/src/toolpad/AppEditor/BindingEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/useEvaluateLiveBinding.ts
  packages/toolpad-app/src/toolpadDataSources/rest/server.ts
  packages/toolpad-app/src/toolpadDataSources/rest/shared.ts
  packages/toolpad-core/src/jsRuntime.tsx
  test/integration/rest-basic/fixture/.env
  test/integration/rest-basic/fixture/toolpad/pages/page1/page.yml
  test/integration/rest-basic/index.spec.ts
Labels: bug 🐛, enhancement

#2136 Make sure global variables are retained in between invocations
  packages/toolpad-app/src/server/functionsDevWorker.ts
  test/integration/backend-basic/fixture/toolpad/pages/page1/page.yml
  test/integration/backend-basic/fixture/toolpad/resources/functions.ts
  test/integration/backend-basic/index.spec.ts
Labels: core

#2141 Upgrade monorepo
  yarn.lock
Labels: chore 🧹, release 🚀

#2134 Improve publish process
  package.json
  packages/create-toolpad-app/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
  packages/toolpad-utils/package.json
  packages/toolpad/package.json
Labels: core

#2145 Release: v0.1.15
  CHANGELOG.md
  docs/package.json
  lerna.json
  package.json
  packages/create-toolpad-app/package.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
  packages/toolpad-utils/package.json
  packages/toolpad/package.json
Labels: release 🚀

#2143 Enable sourcemaps for the runtime builds
  packages/toolpad-app/tsup.config.ts
  packages/toolpad-components/tsup.config.ts
  packages/toolpad-core/tsup.config.ts
  packages/toolpad-utils/tsup.config.ts
Labels: core

#2146 Replace ts-node with tsx
  package.json
  packages/create-toolpad-app/jest.config.js
  packages/create-toolpad-app/jest.config.ts
  packages/toolpad-app/jest.config.js
  packages/toolpad-app/package.json
  packages/toolpad-app/scripts/tsconfig.json
  scripts/docs/buildComponentsReference.ts
  scripts/tsconfig.json
  tsconfig.json
  yarn.lock
Labels: core

#2149 Improve contributing guidelines for starting the application
  CONTRIBUTING.md
Labels: core

#2137 Infer the createFunction parameters type for objects from the schema
  packages/toolpad-core/src/types.ts
Labels: core

#2140 Consolidate fs utils into single file
  .eslintrc.js
  packages/create-toolpad-app/package.json
  packages/create-toolpad-app/src/index.ts
  packages/create-toolpad-app/src/util.ts
  packages/toolpad-app/src/server/FunctionsManager.ts
  packages/toolpad-app/src/server/localMode.ts
  packages/toolpad-app/src/server/versionInfo.ts
  packages/toolpad-components/package.json
  packages/toolpad-utils/package.json
  packages/toolpad-utils/src/collections.ts
  packages/toolpad-utils/src/errors.ts
  packages/toolpad-utils/src/fs.ts
  test/integration/backend-basic/index.spec.ts
  test/integration/bindings/fixture-navigation/toolpad/.generated/functions/toolpad_main.js
  test/integration/editor/new.spec.ts
  test/integration/mysql-basic/index.spec.ts
  test/integration/rest-basic/index.spec.ts
  test/utils/fs.ts
Labels: core

#2144 Show error when Toolpad is started on a non-existing folder
  packages/toolpad-app/cli/index.ts
Labels: core

#2155 Fix broken import in cli
  packages/toolpad-app/cli/index.ts
Labels: core

#2024 [docs] Move the label from "Alpha" to "Beta"
  README.md
  docs/data/toolpad/landing/marquee.js
  docs/src/components/landing/Hero.js
  packages/toolpad-app/src/toolpad/ToolpadShell/Header/index.tsx
Labels: docs, website

#2156 Fix autocomplete for page parameters
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/JsExpressionEditor.tsx
Labels: core, bug 🐛

#2142 Avoid too many binding evaluations in the runtime
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/runtime/toolpadComponents/template.ts
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/NodeAttributeEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/PageEditorProvider.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/RenderPanel.tsx
  packages/toolpad-components/src/List.tsx
  packages/toolpad-core/src/constants.ts
  packages/toolpad-core/src/types.ts
  packages/toolpad-utils/src/collections.ts
  packages/toolpad-utils/src/react.tsx
  test/integration/components/fixture-list/toolpad.yml
  test/integration/components/fixture-list/toolpad/.gitignore
  test/integration/components/fixture-list/toolpad/pages/list/page.yml
  test/integration/components/list.spec.ts
Labels: core

#2165 Fix passing double dollars in the inlined DOM
  packages/toolpad-app/src/server/toolpadAppBuilder.ts
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/JsExpressionEditor.tsx
  packages/toolpad-utils/src/fs.spec.ts
  packages/toolpad-utils/src/fs.ts
  test/integration/backend-basic/fixture/toolpad/pages/page/page.yml
  test/integration/backend-basic/index.spec.ts
  test/integration/bindings/fixture/toolpad/pages/encoding/page.yml
  test/integration/bindings/index.spec.ts
Labels: core

#2160 Increase amount of playwright workers
  test/playwright.config.ts
  test/playwright/localTest.ts
Labels: test

#2169 Fix create-toolpad-app missing gitignore file
  RELEASE.md
  packages/create-toolpad-app/public/gitignoreTemplate
  packages/create-toolpad-app/src/index.ts
Labels: core

#2154 [core] Remove @mui/x-data-grid-generator dependency
  packages/toolpad-app/package.json
  packages/toolpad-app/scripts/typings.mts
  packages/toolpad-app/src/runtime/muiExports.tsx
  yarn.lock
Labels: core

#2167 Send dom diffs to the server to avoid overly large payloads
  package.json
  packages/toolpad-app/src/appDom/index.ts
  packages/toolpad-app/src/server/liveProject.ts
  packages/toolpad-app/src/server/localMode.ts
  packages/toolpad-app/src/server/rpc.ts
  packages/toolpad-app/src/toolpad/AppState.tsx
  test/playwright.config.ts
Labels: core

#2163 Fix invalid serializations in queries
  packages/toolpad-app/src/server/FunctionsManager.ts
  packages/toolpad-app/src/server/functionsDevWorker.ts
  packages/toolpad-utils/src/errors.ts
  test/integration/backend-basic/fixture/toolpad/pages/basic/page.yml
  test/integration/backend-basic/fixture/toolpad/pages/serialization/page.yml
  test/integration/backend-basic/fixture/toolpad/resources/functions.ts
  test/integration/backend-basic/index.spec.ts
  test/integration/backend-basic/prod.spec.ts
Labels: bug 🐛

#2173 v0.1.16
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/create-toolpad-app/package.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
  packages/toolpad-utils/package.json
  packages/toolpad/package.json
Labels: release 🚀

#1839 Remove pino for rpc logging
  packages/toolpad-app/package.json
  packages/toolpad-app/src/server/logs/logSerializers.ts
  packages/toolpad-app/src/server/logs/logger.ts
  packages/toolpad-app/src/server/logs/withLogs.ts
  packages/toolpad-app/src/server/rpc.ts
  yarn.lock
Labels: core

#2114 Allow nested bindings
  docs/data/toolpad/reference/components/form.md
  docs/schemas/v1/definitions.json
  packages/toolpad-app/src/appDom/index.ts
  packages/toolpad-app/src/appDom/migrations/index.ts
  packages/toolpad-app/src/appDom/migrations/types/v7Legacy.ts
  packages/toolpad-app/src/appDom/migrations/v1.ts
  packages/toolpad-app/src/appDom/migrations/v2.ts
  packages/toolpad-app/src/appDom/migrations/v3.ts
  packages/toolpad-app/src/appDom/migrations/v4.ts
  packages/toolpad-app/src/appDom/migrations/v5.ts
  packages/toolpad-app/src/appDom/migrations/v6.ts
  packages/toolpad-app/src/appDom/migrations/v7.ts
  packages/toolpad-app/src/bindings.ts
  packages/toolpad-app/src/runtime/ToolpadApp.spec.tsx
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/runtime/evalJsBindings.ts
  packages/toolpad-app/src/runtime/toolpadComponents/index.tsx
  packages/toolpad-app/src/server/data.ts
  packages/toolpad-app/src/server/localMode.ts
  packages/toolpad-app/src/server/schema.ts
  packages/toolpad-app/src/toolpad/AppEditor/BindingEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/ConnectionEditor/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/HierarchyExplorer/CreatePageNodeDialog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/BindableEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ConnectionSelect.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/PageOptionsPanel.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ParametersEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/QueryEditor/QueryEditorDialog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/QueryEditor/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/RenderOverlay.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/RenderPanel.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ThemeEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/UrlQueryEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/index.tsx
  packages/toolpad-app/src/toolpadDataSources/googleSheets/client.tsx
  packages/toolpad-app/src/toolpadDataSources/local/client.tsx
  packages/toolpad-app/src/toolpadDataSources/rest/BodyEditor.tsx
  packages/toolpad-app/src/toolpadDataSources/rest/client.tsx
  packages/toolpad-app/src/toolpadDataSources/rest/shared.ts
  packages/toolpad-app/src/toolpadDataSources/rest/types.ts
  packages/toolpad-app/src/toolpadDataSources/sql/client.tsx
  packages/toolpad-app/src/utils/immutability.ts
  packages/toolpad-components/src/Form.tsx
  packages/toolpad-core/src/jsRuntime.tsx
  packages/toolpad-core/src/types.ts
  test/integration/bindings/fixture-navigation/toolpad/pages/page2/page.yml
Labels: new feature

#2172 Update monorepo dependency
  yarn.lock
Labels: core

#2176 Update contributing guide for local development
  CONTRIBUTING.md
Labels: docs

#2198 Add contributing docs for codesandbox CI
  CONTRIBUTING.md
  contributing/codesandbox-ci-package-link.png
Labels: docs

#2197 Disable a query as long as its input is still loading
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  test/integration/backend-basic/fixture/toolpad/pages/basic/page.yml
  test/integration/backend-basic/fixture/toolpad/resources/functions.ts
  test/integration/backend-basic/index.spec.ts
Labels: bug 🐛

#2192 Add contributor guide for running integration tests
  CONTRIBUTING.md
Labels: docs

#2199 Fix wrong environment variable in contributing guide
  CONTRIBUTING.md
Labels: docs

#2205 Version 0.1.17
  CHANGELOG.md
  RELEASE.md
  docs/package.json
  lerna.json
  packages/create-toolpad-app/package.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
  packages/toolpad-utils/package.json
  packages/toolpad/package.json
Labels: release 🚀

#2133 Extract parameters from ts types in function files
  docs/data/toolpad/concepts/connecting-to-data.md
  docs/public/static/toolpad/docs/concepts/connecting-to-data/custom-function-params.png
  package.json
  packages/toolpad-app/cli.js
  packages/toolpad-app/package.json
  packages/toolpad-app/src/rpcClient.ts
  packages/toolpad-app/src/server/FunctionsManager.ts
  packages/toolpad-app/src/server/functionsDevWorker.ts
  packages/toolpad-app/src/server/functionsTypesWorker.ts
  packages/toolpad-app/src/server/localMode.ts
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ErrorAlert.tsx
  packages/toolpad-app/src/toolpadDataSources/QueryInputPanel.tsx
  packages/toolpad-app/src/toolpadDataSources/QueryPreview.tsx
  packages/toolpad-app/src/toolpadDataSources/local/client.tsx
  packages/toolpad-app/src/toolpadDataSources/local/server.ts
  packages/toolpad-app/src/toolpadDataSources/local/types.ts
  packages/toolpad-app/src/toolpadDataSources/useQueryPreview.ts
  packages/toolpad-app/tsup.config.ts
  packages/toolpad-utils/src/errors.ts
  packages/toolpad/index.cjs
  test/integration/backend-basic/fixture/toolpad/pages/extractedTypes/page.yml
  test/integration/backend-basic/fixture/toolpad/pages/page/page.yml
  test/integration/backend-basic/fixture/toolpad/resources/functions.ts
  test/integration/backend-basic/index.spec.ts
  test/playwright.config.ts
  yarn.lock
Labels: core

#2190 Add no-op serviceworker
  docs/pages/_app.js
  docs/scripts/buildServiceWorker.js
  docs/src/sw.js
Labels: docs

#2203 Add error mode to the text component
  docs/data/toolpad/reference/api/create-component.md
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/server/toolpadAppBuilder.ts
  packages/toolpad-components/src/Text.tsx
  packages/toolpad-core/src/types.ts
  test/integration/backend-basic/fixture/toolpad/pages/basic/page.yml
  test/integration/backend-basic/fixture/toolpad/resources/functions.ts
  test/integration/backend-basic/index.spec.ts
  test/integration/backend-basic/prod.spec.ts
  test/integration/backend-basic/shared.ts
Labels: enhancement

#2201 Explore banning any types
  .eslintrc.js
  packages/create-toolpad-app/package.json
  packages/create-toolpad-app/src/index.ts
  packages/toolpad-app/src/utils/useLocalStorageState.ts
  packages/toolpad-utils/src/events.ts
  packages/toolpad-utils/src/fs.ts
Labels: core

#2212 Upgrade @mui/monorepo
  docs/pages/_app.js
  docs/pages/toolpad/index.js
  docs/src/components/landing/Hero.js
  yarn.lock
Labels: dependencies, chore 🧹

#2096 Example-1: admin app
  examples/admin-app/package.json
  examples/admin-app/toolpad/.gitignore
  examples/admin-app/toolpad/pages/AdminApp/page.yml
  examples/admin-app/toolpad/resources/functions.ts
Labels: examples

#2151 Example-4: NPM stats
  examples/npm-stats/package.json
  examples/npm-stats/toolpad/.gitignore
  examples/npm-stats/toolpad/components/LineChart.tsx
  examples/npm-stats/toolpad/pages/page/page.yml
Labels: examples

#2214 Reload queries when env changes
  packages/toolpad-app/src/api.ts
  packages/toolpad-app/src/server/EnvManager.ts
  packages/toolpad-app/src/server/FunctionsManager.ts
  packages/toolpad-app/src/server/localMode.ts
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/EditorCanvasHost.tsx
  packages/toolpad-app/src/toolpadDataSources/rest/server.ts
  packages/toolpad-app/src/toolpadDataSources/rest/shared.ts
  packages/toolpad-app/src/types.ts
  packages/toolpad-core/src/jsBrowserRuntime.tsx
  packages/toolpad-core/src/jsRuntime.tsx
  packages/toolpad-core/src/jsServerRuntime.tsx
  packages/toolpad-core/src/types.ts
  test/integration/backend-basic/fixture/toolpad/resources/functions.ts
  test/integration/backend-basic/index.spec.ts
  test/integration/rest-basic/index.spec.ts
  test/playwright/localTest.ts
  test/utils/page.ts
Labels: core

#2221 Add needs triage action
  .github/workflows/ensure-triage-label.yml
Labels: core, scope: code-infra

#2225 Fix github rest call in truage label actio
  .github/workflows/ensure-triage-label.yml
Labels: core

#2222 Increase timeout when running integration tests in dev mode
  test/playwright.config.ts
Labels: test

#2231 Fix broken query editor when env vars are defined
  packages/toolpad-app/src/server/data.ts
  packages/toolpad-core/src/jsServerRuntime.tsx
  test/integration/rest-basic/index.spec.ts
Labels: regression

#2232 [core] Upgrade monorepo
  docs/next.config.mjs
  package.json
  yarn.lock
Labels: core

#2239 v0.1.18
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/create-toolpad-app/package.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
  packages/toolpad-utils/package.json
  packages/toolpad/package.json
Labels: release 🚀

#2228 Add a warning when required environment variables are missing
  packages/toolpad-app/src/appDom/index.ts
  packages/toolpad-app/src/server/localMode.ts
  packages/toolpad-utils/src/errors.ts
Labels: core

#2243 Create update monorepo workflow
  .github/workflows/update-monorepo.yml
Labels: core

#2241 Move monaco-editor to devDependencies
  .eslintrc.js
  packages/toolpad-app/package.json
  packages/toolpad-app/src/canvas/getPageViewState.ts
Labels: core

#2245 Export canvas and runtime from @mui/toolpad
  packages/toolpad-app/canvas/package.json
  packages/toolpad-app/package.json
  packages/toolpad-app/runtime/package.json
  packages/toolpad-app/server/package.json
  packages/toolpad-app/src/server/toolpadAppBuilder.ts
  packages/toolpad-app/tsconfig.cli.json
  packages/toolpad-app/tsconfig.esbuild.json
  packages/toolpad-app/tsconfig.runtime.json
  packages/toolpad-app/tsup.config.ts
  packages/toolpad-components/tsup.config.ts
  packages/toolpad-core/tsup.config.ts
  packages/toolpad-utils/tsup.config.ts
  packages/toolpad/canvas/package.json
  packages/toolpad/package.json
  packages/toolpad/runtime/package.json
  packages/toolpad/src/canvas.ts
  packages/toolpad/src/runtime.ts
  packages/toolpad/tsup.config.ts
Labels: core

#2248 Move license key logic into the components
  packages/toolpad-app/src/server/toolpadAppBuilder.ts
  packages/toolpad-components/src/DataGrid.tsx
Labels: core
