Repository mui/toolpad, pull requests merged in 2023-11, with the labels that each got.

#2477 [docs] Add Stripe script example
  examples/stripe-script/package.json
  examples/stripe-script/toolpad/pages/page/page.yml
  examples/stripe-script/toolpad/resources/functions.ts
  examples/stripe-script/toolpad/resources/stripe.ts
Labels: docs

#2852 Update monorepo
  yarn.lock
Labels: chore 🧹

#2845 Add preview header to custom server
  .eslintrc.js
  packages/toolpad-app/src/constants.ts
  packages/toolpad-app/src/runtime/AppLayout.tsx
  packages/toolpad-app/src/runtime/CanvasHooksContext.tsx
  packages/toolpad-app/src/runtime/PreviewHeader.tsx
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/runtime/api.ts
  packages/toolpad-app/src/runtime/bindings.ts
  packages/toolpad-app/src/runtime/constants.ts
  packages/toolpad-app/src/runtime/createRuntimeState.tsx
  packages/toolpad-app/src/runtime/evalJsBindings.ts
  packages/toolpad-app/src/runtime/index.tsx
  packages/toolpad-app/src/runtime/types.ts
  packages/toolpad-app/src/server/toolpadAppServer.ts
  packages/toolpad-app/src/toolpad/AppEditor/BindingEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/BindableEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/EditorCanvasHost.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/RenderPanel.tsx
  packages/toolpad-app/src/toolpad/AppState.tsx
  packages/toolpad-app/src/types.ts
  packages/toolpad-app/src/utils/immutability.ts
  packages/toolpad-core/src/types.ts
Labels: core

#2847 Fix port option alias
  packages/toolpad-app/cli/index.ts
Labels: enhancement

#2500 Migrate Chart component to X charts library
  examples/npm-stats/package.json
  package.json
  packages/toolpad-app/package.json
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/NodeAttributeEditor.tsx
  packages/toolpad-app/src/toolpad/propertyControls/ChartData.tsx
  packages/toolpad-components/package.json
  packages/toolpad-components/src/Chart.tsx
  test/integration/codeComponents/fixture/toolpad/components/MyBarChart.tsx
  test/integration/components/chart.spec.ts
  test/integration/components/fixture-chart/toolpad/pages/chart/page.yml
  test/integration/components/fixture-chart/toolpad/pages/loadingAndError/page.yml
  test/integration/components/fixture-chart/toolpad/resources/barChartData.ts
  yarn.lock
Labels: feature: Components

#2851 Add supabase example showcasing list component
  docs/public/static/toolpad/marketing/supabase.png
  docs/src/modules/components/ExamplesGrid.js
  examples/basic-crud-app/toolpad/pages/AdminApp/page.yml
  examples/supabase/.gitignore
  examples/supabase/README.md
  examples/supabase/package.json
  examples/supabase/toolpad/.gitignore
  examples/supabase/toolpad/pages/page/page.yml
  examples/supabase/toolpad/resources/supabase.ts
  examples/with-prisma-data-provider/README.md
Labels: examples

#2857 v0.1.35
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/create-toolpad-app/package.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
  packages/toolpad-utils/package.json
Labels: release 🚀

#2861 Fix ESM charts issues in production
  packages/toolpad-app/src/server/toolpadAppBuilder.ts
Labels: bug 🐛

#2863 v0.1.36
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/create-toolpad-app/package.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
  packages/toolpad-utils/package.json
Labels: release 🚀

#2787 Add Switch component as a variant to Checkbox
  docs/data/toolpad/reference/components/checkbox.md
  packages/toolpad-app/src/runtime/toolpadComponents/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentCatalog/ComponentCatalog.tsx
  packages/toolpad-components/src/Checkbox.tsx
  test/visual/components/fixture/toolpad/pages/components/page.yml
  test/visual/components/fixture/toolpad/pages/rows/page.yml
Labels: new feature

#2874 [docs] Fix images width overflow on Firefox
  docs/src/modules/components/DocsImage.tsx
Labels: docs, bug 🐛

#2876 Fix a deprecation message in the tests
  packages/toolpad-core/src/browser.tsx
  packages/toolpad-utils/src/react.tsx
  test/visual/components/fixture/toolpad/components/MyComponent.tsx
Labels: test

#2877 Close the editor vite devserver when the program exits
  packages/toolpad-app/src/server/index.ts
Labels: core

#2777 Allow binding query parameters to environment variables
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/runtime/evalJsBindings.ts
  packages/toolpad-app/src/toolpad/AppEditor/BindingEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/GlobalScopeExplorer.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/BindableEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ParametersEditor.tsx
  packages/toolpad-app/src/toolpadDataSources/rest/client.tsx
  packages/toolpad-app/src/toolpadDataSources/rest/server.ts
  packages/toolpad-app/src/toolpadDataSources/rest/types.ts
Labels: feature: Queries

#2800 Add Toolpad editor command for connecting to custom servers
  packages/toolpad-app/cli/index.ts
  packages/toolpad-app/src/server/appServerWorker.ts
  packages/toolpad-app/src/server/index.ts
  packages/toolpad-app/src/server/toolpadAppBuilder.ts
  packages/toolpad-app/src/toolpad/ToolpadShell/Header/index.tsx
  test/integration/backend-basic/base.spec.ts
  test/integration/backend-basic/baseProd.spec.ts
  test/integration/backend-basic/index.spec.ts
  test/integration/backend-basic/prod.spec.ts
  test/integration/backend-basic/shared.ts
  test/integration/custom-server/dev.spec.ts
  test/integration/custom-server/prod.spec.ts
  test/integration/editor/new.spec.ts
  test/integration/pages/index.spec.ts
  test/integration/rest-basic/index.spec.ts
  test/integration/rest-basic/testServer.ts
  test/playwright/localTest.ts
  test/utils/resources.ts
Labels: new feature

#2878 Add instructions to start the editor for custom servers
  packages/toolpad-app/src/runtime/PreviewHeader.tsx
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
Labels: enhancement

#2880 charts example
  docs/public/static/toolpad/marketing/charts.png
  examples/charts/.gitignore
  examples/charts/README.md
  examples/charts/package.json
  examples/charts/toolpad/.gitignore
  examples/charts/toolpad/pages/page/page.yml
Labels: examples

#2882 Support running multiple handlers side-by-side in a custom server
  packages/toolpad-app/cli/index.ts
  packages/toolpad-app/src/server/EnvManager.ts
  packages/toolpad-app/src/server/FunctionsManager.ts
  packages/toolpad-app/src/server/index.ts
  packages/toolpad-app/src/server/localMode.ts
  packages/toolpad-app/src/server/toolpadAppBuilder.ts
  test/integration/backend-basic/fixture/server.mjs
  test/integration/editor/deleteLast.spec.ts
  test/integration/editor/new.spec.ts
  test/playwright/localTest.ts
Labels: core

#2890 Link issues in docs
  docs/data/toolpad/concepts/data-providers.md
Labels: docs

#2879 Add custom server documentation
  docs/data/pages.ts
  docs/data/toolpad/concepts/custom-server.md
  docs/data/toolpad/reference/api/create-handler.md
  docs/data/toolpad/reference/api/index.md
  docs/pages/toolpad/concepts/custom-server.js
  docs/pages/toolpad/reference/api/create-handler.js
  examples/custom-server/README.md
  examples/custom-server/index.mjs
  examples/custom-server/package.json
  examples/custom-server/toolpad/pages/page/page.yml
  packages/toolpad-app/src/exports/index.ts
  test/integration/backend-basic/fixture/server.mjs
Labels: docs

#2884 Support create-toolpad-app --example argument
  packages/create-toolpad-app/package.json
  packages/create-toolpad-app/src/examples.ts
  packages/create-toolpad-app/src/index.ts
  test/playwright/localTest.ts
  yarn.lock
Labels: create-toolpad-app

#2893 v0.1.37
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/create-toolpad-app/package.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
  packages/toolpad-utils/package.json
Labels: release 🚀

#2892 [docs] Add README to Stripe example
  examples/stripe-script/README.md
  examples/stripe-script/package.json
  examples/stripe-script/toolpad/resources/stripe.ts
Labels: docs, examples

#2894 Update instructions for smoke testing the release
  RELEASE.md
Labels: docs

#2900 Fix failing CTA test
  packages/create-toolpad-app/tests/index.spec.ts
Labels: core

#2905 Isolate tsx in renovate.json
  renovate.json
Labels: core

#2899 Remove --create option from toolpad CLI
  packages/create-toolpad-app/tests/index.spec.ts
  packages/toolpad-app/cli/index.ts
  packages/toolpad-app/src/server/index.ts
  test/integration/editor/deleteLast.spec.ts
  test/integration/editor/new.spec.ts
  test/playwright/localTest.ts
Labels: core

#2891 [experiment] Support custom code files for pages
  docs/schemas/v1/definitions.json
  packages/toolpad-app/src/appDom/index.ts
  packages/toolpad-app/src/canvas/index.tsx
  packages/toolpad-app/src/runtime/ToolpadApp.spec.tsx
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/runtime/index.tsx
  packages/toolpad-app/src/server/appBuilderWorker.ts
  packages/toolpad-app/src/server/appServerWorker.ts
  packages/toolpad-app/src/server/localMode.ts
  packages/toolpad-app/src/server/schema.ts
  packages/toolpad-app/src/server/toolpadAppBuilder.ts
  packages/toolpad-utils/src/react.tsx
  test/models/ToolpadRuntime.ts
Labels: core

#2898 Improve custom server documentation
  .eslintrc.js
  docs/data/toolpad/concepts/custom-server.md
  examples/custom-server/index.mjs
  packages/toolpad-app/src/server/index.ts
Labels: docs

#2885 Update README of examples with new CTA instructions
  examples/basic-crud-app/README.md
  examples/charts/README.md
  examples/custom-datagrid-column/README.md
  examples/custom-server/README.md
  examples/datagrid-columns/README.md
  examples/dog-app/README.md
  examples/google-sheet/README.md
  examples/graphql/README.md
  examples/npm-stats/README.md
  examples/qr-generator/README.md
  examples/stripe-script/README.md
  examples/supabase/README.md
  examples/with-prisma-data-provider/README.md
  examples/with-prisma/README.md
  examples/with-wasm/README.md
Labels: docs, examples

#2895 Try out circleci parallelism
  .circleci/config.yml
  packages/toolpad-app/src/utils/paths.ts
  test/playwright.config.ts
Labels: core

#2921 Fix reactDevtools build location for dev mode
  packages/toolpad-app/src/server/index.ts
  packages/toolpad-app/tsup.config.ts
Labels: core

#2926 [core] Upgrade monorepo
  yarn.lock
Labels: chore 🧹

#2927 v0.1.38
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/create-toolpad-app/package.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
  packages/toolpad-utils/package.json
Labels: release 🚀

#2933 Link the latest 3 examples to the overview page
  docs/public/static/toolpad/marketing/custom-server.png
  docs/public/static/toolpad/marketing/stripe-script.png
  docs/src/modules/components/ExamplesGrid.js
  examples/custom-server/README.md
Labels: docs, examples

#2942 Fix Date serialization in serverless functions
  packages/toolpad-app/src/runtime/evalJsBindings.ts
  packages/toolpad-app/src/server/functionsDevWorker.ts
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/JsExpressionEditor.tsx
  test/integration/backend-basic/fixture/toolpad/pages/serialization/page.yml
  test/integration/backend-basic/fixture/toolpad/resources/functions.ts
  test/integration/backend-basic/index.spec.ts
Labels: core

#2941 Fix crash when function result type contains a constructor property
  packages/toolpad-app/package.json
  packages/toolpad-app/src/rpcClient.ts
  packages/toolpad-app/src/server/rpc.ts
  renovate.json
  test/integration/backend-basic/fixture/toolpad/resources/functions.ts
  yarn.lock
Labels: regression

#2940 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: docs

#2939 [docs] Fix 404 regressions in the docs
  docs/data/pages.ts
  docs/data/toolpad/components/button/ButtonSize.js
  docs/data/toolpad/components/datagrid/datagrid.md
  docs/data/toolpad/concepts/event-handling.md
  docs/data/toolpad/concepts/queries.md
  docs/data/toolpad/how-to-guides/embed-pages.md
  docs/public/_redirects
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/PageOptionsPanel.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/UrlQueryEditor.tsx
Labels: docs, bug 🐛, regression

#2948 Make page title optional in the yml files
  packages/toolpad-app/src/appDom/index.ts
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/server/localMode.ts
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageTitleEditor.tsx
  packages/toolpad-app/src/utils/usePageTitle.ts
Labels: core
