Repository mui/toolpad, pull requests merged in 2023-09, with the labels that each got.

#2605 Fix typo in the code snippet of createComponent API
  docs/data/toolpad/reference/api/create-component.md
Labels: docs

#2609 [docs] Official URL
  docs/data/toolpad/concepts/display-mode.md
  docs/data/toolpad/how-to-guides/embed-pages.md
Labels: docs

#2606 Exclude esm folder from icons alias
  packages/toolpad-app/src/server/toolpadAppBuilder.ts
  packages/toolpad-app/src/toolpad/propertyControls/NumberFormat.tsx
Labels: core

#2600 Disallow binding to event handlers and list templates
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  test/integration/bindings/fixture/toolpad/pages/globalScope/page.yml
  test/integration/bindings/index.spec.ts
Labels: core

#2610 Improve visual test for resizing columns
  test/visual/components/fixture/toolpad/pages/rows/page.yml
  test/visual/components/index.spec.ts
Labels: test, regression

#2611 [docs] Clean-up examples
  CHANGELOG.md
  docs/data/pages.ts
  docs/pages/toolpad/examples/index.js
  docs/public/_redirects
  docs/src/modules/components/ExamplesGrid.js
  examples/custom-datagrid-column/README.md
  examples/datagrid-columns/README.md
  examples/google-sheet/README.md
  examples/qr-generator/README.md
  examples/with-prisma/README.md
Labels: docs, examples

#2587 [Toolpad Editor] Fix : text component alignment rendering
  packages/toolpad-components/src/Text.tsx
  test/visual/components/fixture/toolpad/pages/components/page.yml
Labels: bug 🐛

#2591 [Toolpad Editor] Fix Markdown text alignment issue
  packages/toolpad-components/src/Text.tsx
  test/visual/components/fixture/toolpad/pages/components/page.yml
Labels: bug 🐛

#2612 [Toolpad Editor] Add tooltip to custom component subtitle
  packages/toolpad-app/src/components/HelpTooltipIcon.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentCatalog/ComponentCatalog.tsx
Labels: docs

#2634 Fix TreeView types after core update
  packages/toolpad-app/src/toolpad/AppEditor/HierarchyExplorer/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PagesExplorer/index.tsx
  packages/toolpad-app/src/toolpadDataSources/local/client.tsx
Labels: core

#2628 [docs] Rename Examples group
  docs/data/pages.ts
Labels: docs

#2639 Replace @mui/lab with @mui/x-tree-view
  packages/toolpad-app/package.json
  packages/toolpad-app/src/toolpad/AppEditor/HierarchyExplorer/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PagesExplorer/index.tsx
  packages/toolpad-app/src/toolpadDataSources/local/client.tsx
  yarn.lock
Labels: core

#2633 [docs] Add live apps link to the homepage examples
  examples/basic-crud-app/README.md
  examples/npm-stats/README.md
  examples/qr-generator/README.md
Labels: docs

#2640 [website] Fix `NpmCopyButton` placement
  docs/src/components/landing/Hero.js
Labels: website

#2641 Fix stackblitz issues with setCookie
  packages/toolpad-app/src/server/functionsDevWorker.ts
Labels: regression

#2642 v0.1.27
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/create-toolpad-app/package.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
  packages/toolpad-utils/package.json
Labels: release 🚀

#2646 [examples] Migrate to railsway
  examples/basic-crud-app/README.md
  examples/npm-stats/README.md
  examples/qr-generator/README.md
Labels: examples

#2505 Upgrade to Node 18
  .circleci/config.yml
  .codesandbox/ci.json
  .github/workflows/update-monorepo.yml
  docs/data/toolpad/how-to-guides/render-deploy.md
  netlify.toml
  package.json
  packages/create-toolpad-app/package.json
  render.yaml
  renovate.json
Labels: core

#2635 Fix container components
  packages/toolpad-app/src/canvas/getPageViewState.ts
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/server/localMode.ts
  packages/toolpad-app/src/toolpad/AppEditor/HierarchyExplorer/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/NodeDropArea.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/RenderOverlay.tsx
  packages/toolpad-app/src/toolpad/AppEditor/pageLayout.ts
  packages/toolpad-core/src/runtime.tsx
  test/integration/bindings/fixture/toolpad/pages/bindings/page.yml
  test/integration/bindings/fixture/toolpad/pages/encoding/page.yml
  test/integration/bindings/fixture/toolpad/pages/globalScope/page.yml
  test/integration/editor/fixture/toolpad/pages/container/page.yml
  test/integration/editor/fixture/toolpad/pages/page23/page.yml
  test/integration/editor/fixture/toolpad/pages/page3/page.yml
  test/integration/editor/fixture/toolpad/pages/page4/page.yml
  test/integration/editor/index.spec.ts
  test/visual/components/fixture/toolpad/pages/components/page.yml
  test/visual/components/fixture/toolpad/pages/rows/page.yml
  test/visual/components/fixture/toolpad/pages/text/page.yml
Labels: bug 🐛, regression, feature: App Editor

#2645 [refactor] Refactor worker rpc
  packages/toolpad-app/cli/appServer.ts
  packages/toolpad-app/cli/server.ts
  packages/toolpad-app/src/server/functionsDevWorker.ts
  packages/toolpad-app/src/server/workerRpc.ts
  packages/toolpad-core/src/serverRuntime.ts
  packages/toolpad-utils/src/json.ts
  packages/toolpad-utils/src/types.ts
  packages/toolpad-utils/src/workerRpc.ts
Labels: core

#2652 [docs] Sync prism with docs-infra
  docs/public/static/styles/prism-okaidia.css
Labels: docs

#2654 Allow execa update
  renovate.json
Labels: core

#2638 respect the user's prettier config when writing yml files
  packages/toolpad-utils/package.json
  packages/toolpad-utils/src/fs.ts
Labels: core

#2656 [docs] Fix /toolpad/reference/api/get-context/ 404
  docs/data/toolpad/reference/api/create-component.md
  docs/data/toolpad/reference/api/create-function.md
  docs/data/toolpad/reference/api/get-context.md
  docs/data/toolpad/reference/api/index.md
  docs/pages/toolpad/reference/api/get-context.js
  packages/toolpad-core/src/serverRuntime.ts
  packages/toolpad-core/src/types.ts
Labels: docs, bug 🐛

#2651 Remove fetch polyfills for node 18
  packages/create-toolpad-app/package.json
  packages/create-toolpad-app/tests/index.spec.ts
  packages/toolpad-app/jest-environment-jsdom.ts
  packages/toolpad-app/jest.config.js
  packages/toolpad-app/scripts/waitForApp.mts
  packages/toolpad-app/src/server/functionsDevWorker.ts
  packages/toolpad-app/src/server/har.ts
  test/integration/rest-basic/fixture/toolpad/pages/page1/page.yml
  test/integration/rest-basic/testServer.ts
  test/playwright/test.ts
  test/utils/fetchPolyfill.ts
Labels: core

#2647 Upgrade react-inspector
  package.json
  packages/toolpad-app/package.json
  packages/toolpad-app/src/components/ObjectInspector.tsx
  renovate.json
  yarn.lock
Labels: core

#2663 Remove monaco-editor special case in renovatebot
  renovate.json
Labels: dependencies

#2589 Support date/dateTime formatting
  packages/toolpad-app/src/toolpad/propertyControls/GridColumns.tsx
  packages/toolpad-components/src/DataGrid.tsx
  packages/toolpad-core/src/dateFormat.tsx
  packages/toolpad-core/src/numberFormat.tsx
  scripts/tsconfig.json
Labels: new feature, feature: Components

#2667 Simplify component loading
  packages/toolpad-app/src/appDom/index.ts
  packages/toolpad-app/src/canvas/index.tsx
  packages/toolpad-app/src/runtime/ToolpadApp.spec.tsx
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/runtime/index.tsx
Labels: core

#2669 v0.1.28
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/create-toolpad-app/package.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
  packages/toolpad-utils/package.json
Labels: release 🚀

#2671 Remove unused hook
  packages/toolpad-app/src/utils/useRisingEdge.ts
Labels: core

#2636 [docs] Add file structure concepts page
  docs/data/pages.ts
  docs/data/toolpad/concepts/file-structure.md
  docs/pages/toolpad/concepts/file-structure.js
  docs/public/static/toolpad/docs/concepts/file-structure/after.png
  docs/public/static/toolpad/docs/concepts/file-structure/fresh.png
Labels: docs

#2673 Explicit dependencies
  docs/package.json
  lerna.json
  package.json
  packages/create-toolpad-app/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
  packages/toolpad-utils/package.json
  yarn.lock
Labels: core

#2675 Avoid reloading queries twice on changes
  packages/toolpad-app/cli/appBuilder.ts
  packages/toolpad-app/cli/appServer.ts
  packages/toolpad-app/cli/server.ts
  packages/toolpad-app/src/runtime/useDataQuery.ts
  packages/toolpad-app/src/server/localMode.ts
  packages/toolpad-app/src/server/toolpadAppBuilder.ts
  packages/toolpad-app/src/server/toolpadAppServer.ts
Labels: core

#2677 Unify useDom, useDomLoader and useAppState
  packages/toolpad-app/src/toolpad/AppEditor/AppEditorShell.tsx
  packages/toolpad-app/src/toolpad/AppEditor/BindingEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/ConnectionEditor/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/HierarchyExplorer/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/NodeMenu.tsx
  packages/toolpad-app/src/toolpad/AppEditor/NodeNameEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentCatalog/ComponentCatalog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentPanel.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ConnectionSelect.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/PageOptionsPanel.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/QueryEditor/QueryEditorDialog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/QueryEditor/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/NodeDropArea.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/OverlayGrid.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/RenderOverlay.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/RenderPanel.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ThemeEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/UrlQueryEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PagePanel.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PagesExplorer/CreateCodeComponentNodeDialog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PagesExplorer/CreatePageNodeDialog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PagesExplorer/index.tsx
  packages/toolpad-app/src/toolpad/AppState.tsx
  packages/toolpad-app/src/toolpad/propertyControls/ChartData.tsx
  packages/toolpad-app/src/toolpad/propertyControls/GridColumns.tsx
Labels: core

#2688 Remove unused eslint-plugin-prettier
  package.json
  yarn.lock
Labels: core

#2687 Bring in some fixes from #2546
  docs/src/modules/components/SchemaReference.tsx
  packages/toolpad-app/src/server/DataManager.ts
  packages/toolpad-app/src/server/functionsTypesWorker.ts
  packages/toolpad-app/src/toolpad/vite.config.ts
  packages/toolpad-core/src/numberFormat.tsx
  packages/toolpad-core/src/runtime.tsx
  packages/toolpad-core/src/types.ts
Labels: core

#2672 Update theming docs
  docs/data/toolpad/concepts/theming.md
Labels: docs, enhancement

#2702 Remove useEvent in favor for @mui/utils useEventCallback
  packages/toolpad-app/src/projectEvents.ts
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/server/toolpadAppBuilder.ts
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/EditorCanvasHost.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/QueryEditor/QueryEditorDialog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/RenderPanel.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PagesExplorer/CreateCodeComponentNodeDialog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PagesExplorer/CreatePageNodeDialog.tsx
  packages/toolpad-app/src/toolpad/AppState.tsx
  packages/toolpad-app/src/utils/useEvent.ts
  packages/toolpad-utils/package.json
Labels: core

#2689 Memory optimizations
  packages/toolpad-app/cli.js
  packages/toolpad-app/cli/appServer.ts
  packages/toolpad-app/src/server/FunctionsManager.ts
  packages/toolpad-app/src/server/toolpadAppBuilder.ts
  packages/toolpad-app/src/server/toolpadAppServer.ts
Labels: core

#2701 hoist documentation dependencies again
  docs/next.config.mjs
  package.json
Labels: docs

#2700 Add with-wasm example
  examples/with-wasm/.gitignore
  examples/with-wasm/README.md
  examples/with-wasm/my-wasm-module.ts
  examples/with-wasm/package.json
  examples/with-wasm/toolpad/.gitignore
  examples/with-wasm/toolpad/pages/wasm/page.yml
  examples/with-wasm/toolpad/resources/functions.ts
Labels: examples

#2693 fix it will be reset the value and fix 404
  packages/toolpad-app/cli/server.ts
  packages/toolpad-app/src/server/localMode.ts
  packages/toolpad-app/src/toolpadDataSources/rest/client.tsx
  packages/toolpad-app/src/types.ts
Labels: core

#2706 Fix DataGrid date inferencing
  packages/toolpad-components/src/DataGrid.tsx
Labels: core

#2682 Fix create-toolpad-app for absolute paths
  packages/create-toolpad-app/package.json
  packages/create-toolpad-app/src/index.ts
  packages/create-toolpad-app/tests/index.spec.ts
  yarn.lock
Labels: core

#2708 Update package.json
  package.json
Labels: core

#2710 v0.1.29
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/create-toolpad-app/package.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
  packages/toolpad-utils/package.json
Labels: release 🚀

#2712 Update monorepo
  docs/next.config.mjs
  yarn.lock
Labels: dependencies

#2714 Fix typo in docs description
  docs/data/toolpad/concepts/custom-functions.md
Labels: docs

#2715 Improve docs language consistency
  docs/data/toolpad/concepts/queries.md
  docs/data/toolpad/getting-started/first-app.md
  docs/data/toolpad/getting-started/overview.md
  docs/data/toolpad/how-to-guides/connect-to-googlesheets.md
  docs/data/toolpad/reference/components/data-grid.md
  packages/toolpad-components/src/DataGrid.tsx
Labels: docs

#2713 Run full prettier in CI
  .circleci/config.yml
  docs/src/components/landing/Hero.js
Labels: core

#2709 Move to vitest
  .eslintrc.js
  package.json
  packages/create-toolpad-app/jest.config.js
  packages/create-toolpad-app/package.json
  packages/create-toolpad-app/tests/index.spec.ts
  packages/create-toolpad-app/vitest.config.ts
  packages/toolpad-app/jest.config.js
  packages/toolpad-app/package.json
  packages/toolpad-app/src/runtime/ToolpadApp.spec.tsx
  packages/toolpad-app/src/server/evalExpression.spec.ts
  packages/toolpad-app/src/server/functionsDevWorker.ts
  packages/toolpad-app/src/server/har.spec.ts
  packages/toolpad-app/src/server/projectRoot.ts
  packages/toolpad-app/vitest.config.ts
  packages/toolpad-components/src/DatePicker.tsx
  packages/toolpad-utils/jest.config.js
  packages/toolpad-utils/package.json
  packages/toolpad-utils/src/collections.spec.ts
  packages/toolpad-utils/src/errors.spec.ts
  packages/toolpad-utils/src/events.spec.ts
  packages/toolpad-utils/src/fs.spec.ts
  packages/toolpad-utils/src/objectKey.spec.ts
  packages/toolpad-utils/src/path.spec.ts
  packages/toolpad-utils/src/promises.spec.ts
  packages/toolpad-utils/src/react.spec.tsx
  packages/toolpad-utils/src/strings.spec.ts
  packages/toolpad-utils/vitest.config.ts
  test/setupJest.ts
  test/setupVitest.ts
  yarn.lock
Labels: test

#2723 Remove unused address dependency
  docs/package.json
  yarn.lock
Labels: docs

#2722 Fix prettier changes script
  .circleci/config.yml
  package.json
Labels: core

#2725 fix 2704
  packages/create-toolpad-app/src/index.ts
  packages/toolpad-utils/src/path.spec.ts
  packages/toolpad-utils/src/path.ts
Labels: core

#2731 v0.1.30
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/create-toolpad-app/package.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
  packages/toolpad-utils/package.json
Labels: release 🚀

#2729 Refactor cli interface
  packages/toolpad-app/cli/appBuilder.ts
  packages/toolpad-app/cli/index.ts
  packages/toolpad-app/cli/server.ts
  packages/toolpad-app/src/config.ts
  packages/toolpad-app/src/server/FunctionsManager.ts
  packages/toolpad-app/src/server/localMode.ts
  packages/toolpad-app/src/types.ts
Labels: core

#2734 Run required PR label action on synchronize event
  .github/workflows/check-if-pr-has-label.yml
Labels: core

#2736 Correct types of component labels
  packages/toolpad-components/src/Autocomplete.tsx
  packages/toolpad-components/src/Checkbox.tsx
  packages/toolpad-components/src/DatePicker.tsx
  packages/toolpad-components/src/FilePicker.tsx
  packages/toolpad-components/src/Select.tsx
  packages/toolpad-components/src/TextField.tsx
Labels: core

#2735 Isolate the Toolpad router from Toolpad server
  packages/create-toolpad-app/src/index.ts
  packages/toolpad-app/cli/appBuilder.ts
  packages/toolpad-app/cli/server.ts
  packages/toolpad-app/src/config.ts
  packages/toolpad-app/src/projectEvents.ts
  packages/toolpad-app/src/server/DataManager.ts
  packages/toolpad-app/src/server/localMode.ts
  packages/toolpad-app/src/types.ts
  packages/toolpad-utils/src/cli.spec.ts
  packages/toolpad-utils/src/cli.ts
  packages/toolpad-utils/src/path.spec.ts
  packages/toolpad-utils/src/path.ts
Labels: core

#2738 Remove Chart as future component
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentCatalog/ComponentCatalog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentCatalog/ComponentCatalogItem.tsx
Labels: core

#2739 [docs] Fix docs title regression
  docs/package.json
  yarn.lock
Labels: docs, dependencies, bug 🐛

#2740 Support --base option to set a custom base path
  docs/data/toolpad/concepts/deployment.md
  packages/toolpad-app/cli/appBuilder.ts
  packages/toolpad-app/cli/index.ts
  packages/toolpad-app/cli/server.ts
  packages/toolpad-app/src/config.ts
  packages/toolpad-app/src/routes.ts
  packages/toolpad-app/src/server/localMode.ts
  packages/toolpad-app/src/toolpad/AppEditor/AppEditorShell.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/EditorCanvasHost.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/RenderPanel.tsx
  packages/toolpad-app/src/toolpad/AppState.tsx
  packages/toolpad-app/src/types.ts
  test/integration/backend-basic/base.spec.ts
  test/integration/backend-basic/baseProd.spec.ts
  test/integration/pages/index.spec.ts
  test/models/ToolpadRuntime.ts
  test/playwright/localTest.ts
Labels: new feature
