Repository mui/toolpad, pull requests merged in 2023-07, with the labels that each got.

#2252 Avoid double submit when function file is created
  packages/toolpad-app/src/toolpadDataSources/local/client.tsx
Labels: bug 🐛

#2251 [fix] disable auto formatting `_redirects`
  .vscode/settings.json
Labels: core, chore 🧹

#2247 Use links for the runtime navigation bar
  packages/toolpad-app/src/runtime/AppNavigation.tsx
Labels: core

#2260 Lay foundation for new and improved theme editor
  docs/schemas/v1/definitions.json
  docs/src/modules/components/SchemaReference.tsx
  packages/toolpad-app/src/appDom/index.ts
  packages/toolpad-app/src/canvas/index.tsx
  packages/toolpad-app/src/components/ColorTool.tsx
  packages/toolpad-app/src/components/MuiThemeEditor.tsx
  packages/toolpad-app/src/runtime/AppThemeProvider.tsx
  packages/toolpad-app/src/server/localMode.ts
  packages/toolpad-app/src/server/schema.ts
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ThemeEditor.tsx
Labels: core

#2250 Support loading raw text for .txt files and .sql files
  packages/toolpad-app/src/server/FunctionsManager.ts
  packages/toolpad-core/src/server.ts
  packages/toolpad-core/src/serverModules.d.ts
  test/integration/backend-basic/fixture/toolpad/pages/basic/page.yml
  test/integration/backend-basic/fixture/toolpad/resources/functions.ts
  test/integration/backend-basic/fixture/toolpad/resources/raw.sql
  test/integration/backend-basic/fixture/toolpad/resources/raw.txt
  test/integration/backend-basic/shared.ts
Labels: new feature

#2115 Connect Autocomplete to forms and refactor form logic
  docs/data/toolpad/reference/components/autocomplete.md
  docs/data/toolpad/reference/components/date-picker.md
  docs/data/toolpad/reference/components/file-picker.md
  docs/data/toolpad/reference/components/select.md
  docs/data/toolpad/reference/components/text-field.md
  packages/toolpad-components/src/Autocomplete.tsx
  packages/toolpad-components/src/DatePicker.tsx
  packages/toolpad-components/src/FilePicker.tsx
  packages/toolpad-components/src/Form.tsx
  packages/toolpad-components/src/Select.tsx
  packages/toolpad-components/src/TextField.tsx
  test/integration/components/fixture-form/toolpad/pages/form/page.yml
  test/integration/components/form.spec.ts
Labels: feature: Components, enhancement

#2268 Add some documentation about screenshot sizes
  docs/README.md
  docs/public/static/toolpad/docs/whatismyviewport.png
Labels: docs

#2269 qrcode-example-folder-change
  docs/pages/toolpad/examples/qr-generator.js
  examples/qrcode-generator/README.md
  examples/qrcode-generator/package.json
  examples/qrcode-generator/toolpad/.gitignore
  examples/qrcode-generator/toolpad/pages/qrcode/page.yml
  examples/qrcode-generator/toolpad/resources/functions.ts
Labels: examples

#2265 Fix missing typography variant
  packages/toolpad-components/src/Text.tsx
  test/integration/components/basic.spec.ts
  test/integration/components/fixture-basic/toolpad/pages/components/page.yml
Labels: regression

#2272 v0.1.19
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/create-toolpad-app/package.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
  packages/toolpad-utils/package.json
  packages/toolpad/package.json
Labels: release 🚀

#2270 Allow loading partial theme
  docs/schemas/v1/definitions.json
  packages/toolpad-app/src/components/ColorTool.tsx
  packages/toolpad-app/src/components/MuiThemeEditor.tsx
  packages/toolpad-app/src/server/liveProject.ts
  packages/toolpad-app/src/server/localMode.ts
  packages/toolpad-app/src/server/schema.ts
Labels: core

#2181 Fix Windows issues
  package.json
  packages/create-toolpad-app/package.json
  packages/toolpad-app/package.json
  packages/toolpad-app/src/server/FunctionsManager.ts
  packages/toolpad-app/src/server/functionsTypesWorker.ts
  packages/toolpad-app/src/server/localMode.ts
  packages/toolpad-app/src/utils/paths.ts
  packages/toolpad-components/tsup.config.ts
  packages/toolpad-core/tsup.config.ts
  packages/toolpad-utils/tsup.config.ts
  test/integration/components/form.spec.ts
  test/integration/components/test.txt
  test/integration/file-picker/index.spec.ts
  test/playwright/localTest.ts
Labels: bug 🐛

#2271 Update MUI monorepo
  CONTRIBUTING.md
  README.md
  RELEASE.md
  docs/README.md
  docs/data/toolpad/concepts/connecting-to-data.md
  docs/data/toolpad/concepts/deployment.md
  docs/data/toolpad/getting-started/first-app.md
  docs/data/toolpad/getting-started/installation.md
  docs/data/toolpad/how-to-guides/cube-component.md
  docs/data/toolpad/tutorials/render-deploy.md
  packages/toolpad-app/README.md
  packages/toolpad-components/README.md
  packages/toolpad-core/README.md
  packages/toolpad-utils/README.md
  yarn.lock
Labels: chore 🧹

#2262 Add prisma example
  docs/public/static/toolpad/marketing/with-prisma.png
  examples/with-prisma/.gitignore
  examples/with-prisma/README.md
  examples/with-prisma/package.json
  examples/with-prisma/prisma/dev.db
  examples/with-prisma/prisma/migrations/20230704094414_init/migration.sql
  examples/with-prisma/prisma/migrations/migration_lock.toml
  examples/with-prisma/prisma/schema.prisma
  examples/with-prisma/toolpad/.gitignore
  examples/with-prisma/toolpad/pages/users/page.yml
  examples/with-prisma/toolpad/resources/functions.ts
  examples/with-prisma/tsconfig.json
Labels: examples

#2276 [docs] Fix MUI reference
  docs/data/toolpad/reference/components/autocomplete.md
  docs/data/toolpad/reference/components/button.md
  docs/data/toolpad/reference/components/container.md
  docs/data/toolpad/reference/components/data-grid.md
  docs/data/toolpad/reference/components/date-picker.md
  docs/data/toolpad/reference/components/form.md
  docs/data/toolpad/reference/components/image.md
  docs/data/toolpad/reference/components/list.md
  docs/data/toolpad/reference/components/paper.md
  docs/data/toolpad/reference/components/select.md
  docs/data/toolpad/reference/components/stack.md
  docs/data/toolpad/reference/components/text-field.md
  docs/data/toolpad/reference/components/text.md
  packages/toolpad-components/src/Button.tsx
  packages/toolpad-components/src/constants.tsx
Labels: docs

#2282 Hardcode prisma db in with-prisma example
  examples/with-prisma/prisma/schema.prisma
Labels: examples

#2283 Add note about light theme
  docs/README.md
Labels: docs

#1999 Use vite for Toolpad editor
  packages/toolpad-app/cli/index.ts
  packages/toolpad-app/cli/server.ts
  packages/toolpad-app/package.json
  packages/toolpad-app/src/ThemeContext.tsx
  packages/toolpad-app/src/components/Link.tsx
  packages/toolpad-app/src/components/MonacoEditor.tsx
  packages/toolpad-app/src/components/monaco/getWorkerNext.ts
  packages/toolpad-app/src/components/monaco/getWorkerVite.ts
  packages/toolpad-app/src/toolpad/Toolpad.tsx
  packages/toolpad-app/src/toolpad/ToolpadShell/Header/UserFeedback/index.tsx
  packages/toolpad-app/src/toolpad/index.html
  packages/toolpad-app/src/toolpad/main.tsx
  packages/toolpad-app/src/toolpad/propertyControls/json.tsx
  packages/toolpad-app/src/toolpad/vite.config.ts
  packages/toolpad-app/src/toolpadDataSources/demo.tsx
  packages/toolpad-app/src/toolpadDataSources/googleSheets/server.ts
  packages/toolpad-app/src/types.ts
  packages/toolpad-app/tsconfig.json
  packages/toolpad-app/typings/monaco-editor.d.ts
  test/playwright.config.ts
  yarn.lock
Labels: enhancement

#2280 Resolve components from source for docs:build:api
  .circleci/config.yml
  package.json
  packages/toolpad-app/src/toolpadDataSources/googleSheets/client.tsx
  packages/toolpad-app/src/toolpadDataSources/sql/client.tsx
  packages/toolpad-app/tsconfig.json
  packages/toolpad-components/src/Autocomplete.tsx
  packages/toolpad-components/src/Button.tsx
  packages/toolpad-components/src/Container.tsx
  packages/toolpad-components/src/DataGrid.tsx
  packages/toolpad-components/src/DatePicker.tsx
  packages/toolpad-components/src/FilePicker.tsx
  packages/toolpad-components/src/Form.tsx
  packages/toolpad-components/src/Image.tsx
  packages/toolpad-components/src/List.tsx
  packages/toolpad-components/src/Paper.tsx
  packages/toolpad-components/src/Select.tsx
  packages/toolpad-components/src/Stack.tsx
  packages/toolpad-components/src/Text.tsx
  packages/toolpad-components/src/TextField.tsx
  packages/toolpad-components/src/index.tsx
  packages/toolpad-core/src/browser.tsx
  packages/toolpad-core/src/componentsContext.tsx
  packages/toolpad-core/src/index.tsx
  packages/toolpad-core/src/jsBrowserRuntime.tsx
  packages/toolpad-core/src/jsRuntime.tsx
  packages/toolpad-core/src/jsServerRuntime.tsx
  packages/toolpad-core/src/path.ts
  packages/toolpad-core/src/runtime.tsx
  packages/toolpad-core/src/server.ts
  packages/toolpad-core/src/types.ts
  packages/toolpad-utils/src/objectKey.spec.ts
  packages/toolpad-utils/src/objectKey.ts
  packages/toolpad-utils/src/path.spec.ts
  packages/toolpad-utils/src/path.ts
  scripts/docs/buildCoreReference.ts
  scripts/tsconfig.json
Labels: core

#2284 Provide all exports of @mui/toolpad on @mui/toolpad-app
  packages/toolpad-app/browser/package.json
  packages/toolpad-app/canvas/package.json
  packages/toolpad-app/package.json
  packages/toolpad-app/runtime/package.json
  packages/toolpad-app/server/package.json
  packages/toolpad-app/src/canvas/index.tsx
  packages/toolpad-app/src/exports/browser.ts
  packages/toolpad-app/src/exports/canvas.ts
  packages/toolpad-app/src/exports/runtime.ts
  packages/toolpad-app/src/exports/server.ts
  packages/toolpad-app/src/runtime/index.ts
  packages/toolpad-app/src/runtime/index.tsx
  packages/toolpad-app/tsup.config.ts
Labels: core

#2285 [core] Polish imports to React
  packages/toolpad-app/src/runtime/index.tsx
  packages/toolpad-app/src/toolpad/hooks/useUnsavedChangesConfirm.ts
Labels: core

#2295 Isolate prettier in renovatebot
  renovate.json
Labels: dependencies

#2296 Clarify the rules around documentation screenshots
  docs/README.md
Labels: docs

#1991 Disallow access to DOM globals in bindings
  packages/toolpad-core/src/jsBrowserRuntime.tsx
  test/integration/bindings/fixture/toolpad/pages/globalScope/page.yml
  test/integration/bindings/index.spec.ts
Labels: core

#2300 Add extra note about aspect ratio of screenshots
  docs/README.md
Labels: docs

#2298 Remove createFunction from examples
  examples/admin-app/README.md
  examples/admin-app/toolpad/resources/functions.ts
  examples/datagrid-columns/toolpad/resources/functions.ts
  examples/qr-generator/README.md
  examples/qr-generator/toolpad/resources/functions.ts
  examples/qrcode-generator/README.md
  examples/qrcode-generator/toolpad/resources/functions.ts
Labels: examples

#2305 [website] use `theme.applyDarkStyles` on marketing website
  docs/src/components/landing/CardGrid.js
  docs/src/components/landing/DemoVideo.js
  docs/src/components/landing/Hero.js
  docs/src/components/landing/Marquee.js
  docs/src/components/landing/PricingTable.js
  docs/src/components/landing/SignUp.js
  docs/src/components/landing/SignUpToast.js
  docs/src/components/landing/UseCases.js
Labels: website

#2306 v0.0.20
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/create-toolpad-app/package.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
  packages/toolpad-utils/package.json
  packages/toolpad/package.json
Labels: release 🚀

#2307 Switch to stackblitz links for examples
  CHANGELOG.md
  examples/admin-app/README.md
  examples/custom-datagrid-column/README.md
  examples/datagrid-columns/README.md
  examples/dog-app/README.md
  examples/npm-stats/README.md
  examples/qr-generator/README.md
  examples/qrcode-generator/README.md
  examples/with-prisma/README.md
Labels: docs

#2202 Add Metric component
  docs/data/toolpad/reference/components/index.md
  docs/data/toolpad/reference/components/manifest.json
  docs/data/toolpad/reference/components/metric.md
  docs/pages/toolpad/reference/components/metric.js
  packages/toolpad-app/src/components/ColorPicker.tsx
  packages/toolpad-app/src/runtime/toolpadComponents/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentCatalog/ComponentCatalogItem.tsx
  packages/toolpad-app/src/toolpad/propertyControls/ColorScale.tsx
  packages/toolpad-app/src/toolpad/propertyControls/GridColumns.tsx
  packages/toolpad-app/src/toolpad/propertyControls/NumberFormat.tsx
  packages/toolpad-app/src/toolpad/propertyControls/index.tsx
  packages/toolpad-app/src/toolpad/propertyControls/number.tsx
  packages/toolpad-app/tsconfig.json
  packages/toolpad-components/src/DataGrid.tsx
  packages/toolpad-components/src/Metric.tsx
  packages/toolpad-components/src/index.tsx
  packages/toolpad-core/package.json
  packages/toolpad-core/src/numberFormat.tsx
  packages/toolpad-core/src/types.ts
  scripts/tsconfig.json
  test/integration/pages/fixture/toolpad/pages/page1/page.yml
Labels: feature: Components

#1959 Add some visual regression tests
  .circleci/config.yml
  .eslintignore
  .gitignore
  package.json
  scripts/pushArgos.mjs
  test/playwright/localTest.ts
  test/visual/components/fixture/toolpad/.gitignore
  test/visual/components/fixture/toolpad/components/MyComponent.tsx
  test/visual/components/fixture/toolpad/pages/components/page.yml
  test/visual/components/index.spec.ts
  yarn.lock
Labels: test

#1270 Codify lodash usage in eslint
  .eslintrc.js
  packages/toolpad-app/src/constants.ts
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/runtime/evalJsBindings.ts
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentEditor.tsx
  packages/toolpad-app/src/toolpad/AppState.tsx
  packages/toolpad-app/src/toolpadDataSources/client.tsx
  packages/toolpad-app/src/toolpadDataSources/server.ts
  packages/toolpad-app/src/utils/immutability.ts
  packages/toolpad-components/src/Form.tsx
Labels: core

#2287 Remove packages/toolpad
  .codesandbox/ci.json
  CONTRIBUTING.md
  docs/pages/_app.js
  package.json
  packages/toolpad-app/README.md
  packages/toolpad-app/package.json
  packages/toolpad/browser/package.json
  packages/toolpad/canvas/package.json
  packages/toolpad/index.cjs
  packages/toolpad/package.json
  packages/toolpad/runtime/package.json
  packages/toolpad/server/package.json
  packages/toolpad/src/browser.ts
  packages/toolpad/src/canvas.ts
  packages/toolpad/src/runtime.ts
  packages/toolpad/src/server.ts
  packages/toolpad/tsconfig.json
  packages/toolpad/tsup.config.ts
Labels: core

#2288 Remove Next.js
  .eslintrc.js
  packages/create-toolpad-app/jest.config.js
  packages/toolpad-app/cli/index.ts
  packages/toolpad-app/cli/server.ts
  packages/toolpad-app/jest.config.js
  packages/toolpad-app/middleware.ts
  packages/toolpad-app/next-env.d.ts
  packages/toolpad-app/next.config.mjs
  packages/toolpad-app/package.json
  packages/toolpad-app/pages/_app.tsx
  packages/toolpad-app/pages/_document.tsx
  packages/toolpad-app/pages/_toolpad/[[...index]].tsx
  packages/toolpad-app/src/runtime/ToolpadApp.spec.tsx
  packages/toolpad-app/src/server/FunctionsManager.ts
  packages/toolpad-app/src/server/initMiddleware.ts
  packages/toolpad-app/tsconfig.json
  test/playwright/localTest.ts
  yarn.lock
Labels: core

#2081 Chart component
  docs/data/toolpad/reference/components/chart.md
  docs/data/toolpad/reference/components/index.md
  docs/data/toolpad/reference/components/manifest.json
  docs/pages/toolpad/reference/components/chart.js
  packages/toolpad-app/package.json
  packages/toolpad-app/src/constants.ts
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/runtime/constants.ts
  packages/toolpad-app/src/runtime/evalJsBindings.ts
  packages/toolpad-app/src/runtime/toolpadComponents/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/BindingEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/BindableEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/NodeAttributeEditor.tsx
  packages/toolpad-app/src/toolpad/propertyControls/ChartData.tsx
  packages/toolpad-app/src/toolpad/propertyControls/index.tsx
  packages/toolpad-app/src/toolpadDataSources/local/client.tsx
  packages/toolpad-components/package.json
  packages/toolpad-components/src/Chart.tsx
  packages/toolpad-components/src/DataGrid.tsx
  packages/toolpad-components/src/index.tsx
  packages/toolpad-core/src/types.ts
  test/integration/components/chart.spec.ts
  test/integration/components/fixture-chart/toolpad/.gitignore
  test/integration/components/fixture-chart/toolpad/pages/chart/page.yml
  test/integration/components/fixture-chart/toolpad/resources/barChartData.ts
Labels: feature: Components

#2312 Default vertical alignment to top instead of center
  packages/toolpad-app/src/runtime/toolpadComponents/layoutBox.ts
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/NodeAttributeEditor.tsx
  packages/toolpad-app/src/toolpad/propertyControls/HorizontalAlign.tsx
  packages/toolpad-app/src/toolpad/propertyControls/VerticalAlign.tsx
  packages/toolpad-core/src/types.ts
Labels: enhancement

#2311 Add Page tab to right-side panel
  packages/toolpad-app/src/toolpad/AppEditor/HierarchyExplorer/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/NodeMenu.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentPanel.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/PageOptionsPanel.tsx
  packages/toolpad-app/src/toolpad/AppState.tsx
  packages/toolpad-app/src/utils/domView.ts
  test/integration/backend-basic/index.spec.ts
  test/integration/rest-basic/index.spec.ts
  test/models/ToolpadEditor.ts
Labels: design: ux, enhancement

#2329 Fix some flakyness in the visual regression testing
  packages/toolpad-app/src/runtime/index.tsx
  packages/toolpad-app/src/server/toolpadAppBuilder.ts
  test/integration/bindings/navigation.spec.ts
  test/models/ToolpadRuntime.ts
  test/playwright/localTest.ts
  test/visual/components/index.spec.ts
Labels: test

#2333 Upgrade monorepo
  yarn.lock
Labels: core

#2238 Fix: Improve missing editor scenario
  docs/data/pages.ts
  docs/data/toolpad/how-to-guides/editor-path.md
  docs/pages/toolpad/how-to-guides/editor-path.js
  docs/public/static/toolpad/docs/how-to-guides/editor-path/code-install.png
  docs/public/static/toolpad/docs/how-to-guides/editor-path/command-palette.png
  docs/public/static/toolpad/docs/how-to-guides/editor-path/missing-editor.png
  packages/toolpad-app/src/components/OpenCodeEditor.tsx
  packages/toolpad-app/src/server/FunctionsManager.ts
  packages/toolpad-app/src/server/liveProject.ts
  packages/toolpad-app/src/server/localMode.ts
  packages/toolpad-app/src/server/rpc.ts
  packages/toolpad-app/src/toolpad/AppEditor/HierarchyExplorer/CreateCodeComponentNodeDialog.tsx
  packages/toolpad-app/src/toolpadDataSources/local/client.tsx
  packages/toolpad-app/src/toolpadDataSources/local/server.ts
  packages/toolpad-app/src/toolpadDataSources/local/types.ts
Labels: enhancement

#2327 Fix the datagrid remounting when columns change
  packages/toolpad-components/src/DataGrid.tsx
Labels: feature: Components

#2337 Add visual regression test for resize grid
  test/visual/components/fixture/toolpad/pages/rows/page.yml
  test/visual/components/index.spec.ts
Labels: test

#2334 [docs] [cli] Add `createFunction` deprecation notices
  docs/data/toolpad/concepts/connecting-to-data.md
  docs/data/toolpad/how-to-guides/connect-to-databases.md
  docs/data/toolpad/reference/api/create-function.md
  packages/toolpad-app/src/server/functionsTypesWorker.ts
  packages/toolpad-core/src/server.ts
Labels: docs, dx

#2246 [feat] Add page structure explorer
  packages/toolpad-app/src/appDom/index.ts
  packages/toolpad-app/src/components/EditableText.tsx
  packages/toolpad-app/src/toolpad/AppEditor/HierarchyExplorer/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentCatalog/ComponentCatalogItem.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/NodeHud.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/RenderOverlay.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PagePanel.tsx
  packages/toolpad-app/src/toolpad/AppEditor/StructureExplorer/index.tsx
  packages/toolpad-app/src/toolpad/AppState.tsx
  packages/toolpad-app/src/utils/domView.ts
Labels: design: ui, design: ux, feature: App Editor

#2352 Move more APIs to utils package
  packages/toolpad-app/cli/server.ts
  packages/toolpad-app/src/server/data.ts
  packages/toolpad-app/src/server/har.spec.ts
  packages/toolpad-app/src/server/rpc.ts
  packages/toolpad-app/src/server/toolpadAppServer.ts
  packages/toolpad-app/src/toolpad/AppEditor/BindingEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/index.tsx
  packages/toolpad-app/src/toolpad/AppState.tsx
  packages/toolpad-app/src/toolpadDataSources/googleSheets/client.tsx
  packages/toolpad-app/src/utils/express.ts
  packages/toolpad-app/src/utils/http.ts
  packages/toolpad-app/src/utils/useLocalStorageState.ts
  packages/toolpad-utils/src/hooks/useDebounced.ts
  packages/toolpad-utils/src/hooks/useDebouncedHandler.ts
  packages/toolpad-utils/src/hooks/useStorageState.ts
  packages/toolpad-utils/src/http.ts
  packages/toolpad-utils/src/strings.ts
  test/integration/rest-basic/index.spec.ts
  test/visual/components/index.spec.ts
Labels: core

#2344 [website] Fix CLS on hero icon
  docs/src/components/landing/Hero.js
Labels: bug 🐛, website

#2345 [docs] Fix Connecting to databases page
  docs/data/toolpad/how-to-guides/connect-to-databases.md
Labels: docs, bug 🐛

#2346 [docs] Fix npx folder confusion
  README.md
  docs/data/toolpad/getting-started/installation.md
  docs/src/components/landing/Hero.js
  packages/create-toolpad-app/README.md
Labels: docs

#2341 [docs] Add link to live demo to KPI example
  docs/data/pages.ts
  docs/data/toolpad/getting-started/first-app.md
  docs/pages/toolpad/examples/basic-crud-app.js
  docs/pages/toolpad/examples/qr-generator.js
  docs/public/_redirects
  docs/public/static/toolpad/docs/examples/basic-crud-app.png
  docs/public/static/toolpad/docs/examples/npm-stats.png
  docs/public/static/toolpad/docs/examples/qr-generator.png
  examples/admin-app/README.md
  examples/basic-crud-app/README.md
  examples/basic-crud-app/package.json
  examples/basic-crud-app/toolpad/.gitignore
  examples/basic-crud-app/toolpad/pages/AdminApp/page.yml
  examples/basic-crud-app/toolpad/resources/functions.ts
  examples/npm-stats/README.md
  examples/npm-stats/toolpad/pages/page/page.yml
  examples/qr-generator/README.md
  examples/qrcode-generator/README.md
  examples/qrcode-generator/package.json
  examples/qrcode-generator/toolpad/.gitignore
  examples/qrcode-generator/toolpad/pages/qrcode/page.yml
  examples/qrcode-generator/toolpad/resources/functions.ts
  examples/with-prisma/README.md
Labels: docs

#2357 v0.1.21
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/create-toolpad-app/package.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
  packages/toolpad-utils/package.json
Labels: release 🚀

#2359 [website] Update image paths on landing page
  docs/src/components/landing/UseCases.js
Labels: website

#2364 Automerge Toolpad updates in the examples
  renovate.json
Labels: core

#2356 [docs] Fine for production
  README.md
Labels: docs

#2363 Fix rest tests flakyness around env reloading
  packages/toolpad-app/src/server/EnvManager.ts
  test/integration/backend-basic/index.spec.ts
  test/integration/rest-basic/index.spec.ts
  test/utils/fs.ts
Labels: core

#2366 [docs] Improve the docs
  docs/data/toolpad/landing/useCases.js
  docs/src/components/landing/CodeBlock.js
  docs/src/components/landing/GithubStars.js
  docs/src/components/landing/Hero.js
  docs/src/components/landing/UseCases.js
  docs/src/route.ts
  examples/basic-crud-app/README.md
  examples/npm-stats/README.md
  examples/qr-generator/README.md
Labels: docs

#2375 Fix examples order in home page
  docs/data/toolpad/getting-started/installation.md
  docs/src/components/landing/UseCases.js
Labels: docs

#2380 [website] Add a social preview
  docs/pages/toolpad/index.js
  docs/public/static/toolpad/marketing/social-preview.jpg
Labels: website

#2354 Decrease memory usage of functions in production mode
  packages/toolpad-app/cli/appBuilder.ts
  packages/toolpad-app/cli/server.ts
  packages/toolpad-app/src/server/EnvManager.ts
  packages/toolpad-app/src/server/FunctionsManager.ts
  packages/toolpad-app/src/server/functionsShared.ts
  packages/toolpad-app/src/server/functionsTypesWorker.ts
  packages/toolpad-app/src/server/localMode.ts
Labels: core

#2382 Upgrade monorepo
  docs/scripts/i18n.js
  yarn.lock
Labels: chore 🧹

#2383 Remove redundant integration tests section from contribution docs
  CONTRIBUTING.md
Labels: docs

#2322 Refactor deleting nodes
  packages/toolpad-app/src/appDom/index.ts
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/RenderOverlay.tsx
  packages/toolpad-app/src/toolpad/AppEditor/StructureExplorer/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/pageLayout.ts
  test/integration/codeComponents/index.spec.ts
  test/integration/editor/fixture/toolpad/.gitignore
  test/integration/editor/fixture/toolpad/components/FullWidth.tsx
  test/integration/editor/fixture/toolpad/pages/page1/page.yml
  test/integration/editor/fixture/toolpad/pages/page3/page.yml
  test/integration/editor/index.spec.ts
  test/integration/editor/new.spec.ts
  test/integration/undo-redo/basic.spec.ts
  test/models/ToolpadEditor.ts
Labels: core

#2343 Chart component improvements
  packages/toolpad-app/src/toolpad/propertyControls/ChartData.tsx
  packages/toolpad-components/src/Chart.tsx
Labels: feature: Components, enhancement
