Repository mui/toolpad, pull requests merged in 2023-02, with the labels that each got.

#1617 Dual build toolpad-core for esm and cjs
  packages/toolpad-app/src/toolpadDataSources/function/execFunction.ts
  packages/toolpad-app/src/toolpadDataSources/rest/shared.ts
  packages/toolpad-app/tsconfig.json
  packages/toolpad-components/tsconfig.json
  packages/toolpad-core/package.json
  packages/toolpad-core/src/componentsContext.tsx
  packages/toolpad-core/src/createComponent.tsx
  packages/toolpad-core/src/index.tsx
  packages/toolpad-core/src/jsBrowserRuntime.tsx
  packages/toolpad-core/src/jsRuntime.tsx
  packages/toolpad-core/src/jsServerRuntime.tsx
  packages/toolpad-core/src/path.ts
  packages/toolpad-core/src/runtime.tsx
  packages/toolpad-core/src/types.ts
  packages/toolpad-core/src/utils/errors.ts
Labels: core

#1621 v0.0.38
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
Labels: core

#1521 Prototype direction 13
  package.json
  packages/toolpad-app/jest-environment-jsdom.ts
  packages/toolpad-app/package.json
  packages/toolpad-app/pages/_document.tsx
  packages/toolpad-app/pages/_toolpad/[[...index]].tsx
  packages/toolpad-app/pages/api/rpc.ts
  packages/toolpad-app/pages/api/runtime/[[...path]].ts
  packages/toolpad-app/pages/app/[appId]/[version]/[[...path]].tsx
  packages/toolpad-app/pages/deploy/[appId]/[[...path]].tsx
  packages/toolpad-app/pages/index.tsx
  packages/toolpad-app/pages/preview/[[...path]].tsx
  packages/toolpad-app/pages/prod/[[...path]].tsx
  packages/toolpad-app/scripts/buildRuntime.mts
  packages/toolpad-app/src/config.ts
  packages/toolpad-app/src/constants.ts
  packages/toolpad-app/src/server/data.ts
  packages/toolpad-app/src/server/handleDataRequest.ts
  packages/toolpad-app/src/server/localMode.ts
  packages/toolpad-app/src/server/runtimeBuild.ts
  packages/toolpad-app/src/toolpad/AppEditor/AppEditorShell.tsx
  packages/toolpad-app/src/toolpad/AppEditor/CodeComponentEditor/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/HierarchyExplorer/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/QueryEditor/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/RenderPanel.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PagePanel.tsx
  packages/toolpad-app/src/toolpad/AppOptions/index.tsx
  packages/toolpad-app/src/toolpad/DomLoader.tsx
  packages/toolpad-app/src/toolpad/ToolpadLocal.tsx
  packages/toolpad-app/src/toolpadDataSources/client.tsx
  packages/toolpad-app/src/toolpadDataSources/local/client.tsx
  packages/toolpad-app/src/toolpadDataSources/local/server.ts
  packages/toolpad-app/src/toolpadDataSources/local/types.ts
  packages/toolpad-app/src/toolpadDataSources/server.ts
  packages/toolpad-app/tsconfig.esbuild.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
  packages/toolpad-core/src/constants.ts
  packages/toolpad-core/src/createQuery.tsx
  packages/toolpad-core/src/index.tsx
  packages/toolpad-core/src/utils/strings.ts
  packages/toolpad/index.mjs
  packages/toolpad/package.json
  packages/toolpad/src/index.mts
  packages/toolpad/tsconfig.json
  yarn.lock
Labels: core

#1604 Be more accepting of select options
  packages/toolpad-components/src/Select.tsx
  test/integration/components/componentsDom.json
  test/integration/components/index.spec.ts
Labels: enhancement

#1620 Remove firefox specific branch in tests
  test/integration/codeComponents/index.spec.ts
  test/integration/components/index.spec.ts
  test/integration/data-grid/index.spec.ts
  test/integration/duplication/index.spec.ts
  test/integration/editor/index.spec.ts
  test/integration/file-picker/index.spec.ts
  test/integration/function-basic/index.spec.ts
  test/integration/pages/index.spec.ts
  test/integration/propControls/index.spec.ts
  test/integration/rest-basic/index.spec.ts
  test/integration/undo-redo/index.spec.ts
  test/models/ToolpadEditor.ts
Labels: test

#1622 Improve deploy in iframe tests
  test/integration/deploy.spec.ts
  test/integration/deploy/dom.json
  test/integration/deploy/index.spec.ts
Labels: test

#1630 Remove - from select options
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/toolpad/AppEditor/CodeComponentEditor/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/HierarchyExplorer/CreateCodeComponentNodeDialog.tsx
  packages/toolpad-app/src/toolpad/propertyControls/select.tsx
  packages/toolpad-app/src/toolpadComponents/layoutBox.ts
  packages/toolpad-components/src/Button.tsx
  packages/toolpad-components/src/Container.tsx
  packages/toolpad-components/src/DataGrid.tsx
  packages/toolpad-components/src/DatePicker.tsx
  packages/toolpad-components/src/FilePicker.tsx
  packages/toolpad-components/src/Image.tsx
  packages/toolpad-components/src/PageColumn.tsx
  packages/toolpad-components/src/PageRow.tsx
  packages/toolpad-components/src/Paper.tsx
  packages/toolpad-components/src/Select.tsx
  packages/toolpad-components/src/Stack.tsx
  packages/toolpad-components/src/Tabs.tsx
  packages/toolpad-components/src/Text.tsx
  packages/toolpad-components/src/TextField.tsx
  packages/toolpad-core/src/types.ts
Labels: feature: Components

#1631 Add some new future components
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentCatalog/ComponentCatalog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentCatalog/ComponentCatalogItem.tsx
Labels: feature: Components

#1553 Improve drag & drop / canvas UI
  packages/toolpad-app/src/theme.ts
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/NodeDropArea.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/NodeHud.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/OverlayGrid.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/RenderOverlay.tsx
  packages/toolpad-app/src/toolpad/ToolpadShell/DemoBar.tsx
Labels: design: ui, enhancement

#1637 Improve behavior of image columns
  packages/toolpad-components/src/DataGrid.tsx
Labels: core

#1642 v0.0.39
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
  packages/toolpad/package.json
Labels: core

#1640 Fix HMR issues with the canvas bridge
  packages/toolpad-app/src/canvas/BridgeContext.ts
  packages/toolpad-app/src/canvas/ToolpadBridge.tsx
  packages/toolpad-app/src/canvas/index.tsx
  packages/toolpad-app/src/constants.ts
  packages/toolpad-app/src/runtime/ToolpadApp.spec.tsx
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/toolpad/AppEditor/CodeComponentEditor/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/EditorCanvasHost.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/RenderOverlay.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/RenderPanel.tsx
  packages/toolpad-core/src/createComponent.tsx
  packages/toolpad-core/src/index.tsx
Labels: core

#1675 Fix dog images template
  packages/toolpad-app/src/server/appTemplateDoms/images.json
Labels: bug 🐛

#1627 Align headers and typography in the theme
  packages/toolpad-app/src/runtime/AppThemeProvider.tsx
  packages/toolpad-components/src/Text.tsx
Labels: feature: Components

#1681 Fix: Disable "Remove" on draft nodes
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/QueryEditor/QueryEditorDialog.tsx
Labels: bug 🐛

#1583 Fix: Column changes dropped on prop update
  test/integration/data-grid/columnPropUpdate.json
  test/integration/data-grid/index.spec.ts
Labels: bug 🐛

#1527 Add List component
  packages/toolpad-app/src/canvas/getPageViewState.ts
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/toolpad/AppEditor/BindingEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/GlobalScopeExplorer.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/BindableEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentCatalog/ComponentCatalogItem.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/JsExpressionEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/NodeAttributeEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/PageEditorProvider.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ParametersEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/RenderOverlay.tsx
  packages/toolpad-app/src/toolpadComponents/index.tsx
  packages/toolpad-app/src/toolpadComponents/template.ts
  packages/toolpad-app/src/toolpadDataSources/rest/BodyEditor.tsx
  packages/toolpad-app/src/toolpadDataSources/rest/client.tsx
  packages/toolpad-app/src/types.ts
  packages/toolpad-components/src/List.tsx
  packages/toolpad-components/src/index.tsx
  packages/toolpad-core/src/constants.ts
  packages/toolpad-core/src/types.ts
  packages/toolpad-core/src/utils/collections.ts
  test/integration/components/componentsDom.json
  test/integration/components/index.spec.ts
  test/integration/components/listDom.json
Labels: feature: Components

#1628 Confirm unsaved code component changes
  packages/toolpad-app/src/toolpad/AppEditor/AppEditorShell.tsx
  packages/toolpad-app/src/toolpad/AppEditor/BindingEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/CodeComponentEditor/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/ConnectionEditor/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/HierarchyExplorer/CreateCodeComponentNodeDialog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/HierarchyExplorer/CreateConnectionNodeDialog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/HierarchyExplorer/CreatePageNodeDialog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/HierarchyExplorer/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/NodeMenu.tsx
  packages/toolpad-app/src/toolpad/AppEditor/NodeNameEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentCatalog/ComponentCatalog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentPanel.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ConnectionSelect.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/EditorCanvasHost.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/NodeAttributeEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/PageModuleEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/PageOptionsPanel.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/QueryEditor/QueryEditorDialog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/QueryEditor/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/NodeDropArea.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/NodeHud.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/RenderOverlay.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/RenderPanel.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ThemeEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/UrlQueryEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PagePanel.tsx
  packages/toolpad-app/src/toolpad/AppEditor/index.tsx
  packages/toolpad-app/src/toolpad/AppState.tsx
  packages/toolpad-app/src/toolpad/hooks/useUndoRedo.ts
  packages/toolpad-app/src/toolpad/propertyControls/GridColumns.tsx
Labels: bug 🐛, regression, enhancement

#1477 Polish Markdown component
  packages/toolpad-app/package.json
  packages/toolpad-app/src/server/appTemplateDoms/images-demo.json
  packages/toolpad-components/package.json
  packages/toolpad-components/src/Text.tsx
  test/playwright/test.ts
  yarn.lock
Labels: design: ux, enhancement

#1639 Fix resizing after drag & drop UI changes
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/NodeHud.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/OverlayGrid.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/RenderOverlay.tsx
  packages/toolpad-components/src/PageRow.tsx
Labels: bug 🐛

#1618 Show confirmation dialog when there are unsaved changes
  packages/toolpad-app/src/toolpad/AppEditor/BindingEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/CodeComponentEditor/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/PageModuleEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/QueryEditor/QueryEditorDialog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/UrlQueryEditor.tsx
  packages/toolpad-app/src/toolpad/hooks/useUnsavedChangesConfirm.ts
Labels: bug 🐛, regression, enhancement

#1691 Add feedback for mutating queries
  packages/toolpad-app/src/toolpadDataSources/mysql/server.ts
  packages/toolpad-app/src/toolpadDataSources/mysql/types.tsx
  packages/toolpad-app/src/toolpadDataSources/postgres/server.ts
  packages/toolpad-app/src/toolpadDataSources/postgres/types.ts
  packages/toolpad-app/src/toolpadDataSources/sql/client.tsx
  packages/toolpad-app/src/toolpadDataSources/sql/types.ts
Labels: feature: Queries

#1626 Fix DataGrid number formats for non-numerical values
  packages/toolpad-app/pages/api/data/[appId]/[version]/[queryId].ts
  packages/toolpad-components/src/DataGrid.tsx
Labels: feature: Components

#1679 Move selected node state to page view only
  packages/toolpad-app/src/toolpad/AppEditor/HierarchyExplorer/CreateCodeComponentNodeDialog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/HierarchyExplorer/CreateConnectionNodeDialog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/HierarchyExplorer/CreatePageNodeDialog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/HierarchyExplorer/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentPanel.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/QueryEditor/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/RenderOverlay.tsx
  packages/toolpad-app/src/toolpad/AppState.tsx
  packages/toolpad-app/src/utils/domView.ts
Labels: core, enhancement

#1693 Open code editor after creating a code component
  packages/toolpad-app/src/toolpad/AppEditor/HierarchyExplorer/CreateCodeComponentNodeDialog.tsx
  packages/toolpad-app/src/toolpad/AppState.tsx
Labels: core

#1641 Hide resizable height prop controls
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/NodeAttributeEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/NodeHud.tsx
  packages/toolpad-components/src/DataGrid.tsx
Labels: bug 🐛

#1694 Make text component editable in the canvas
  packages/toolpad-app/src/runtime/ToolpadApp.spec.tsx
  packages/toolpad-components/src/Text.tsx
Labels: core

#1699 Remove deprecated waitForNavigation playwright API
  test/integration/appTemplates.spec.ts
  test/integration/duplication/index.spec.ts
Labels: test

#1690 Adjust margins for Markdown component
  packages/toolpad-components/src/Text.tsx
Labels: design: ui, feature: Components

#1695 Fix binding editor confirm on unsaved changes
  packages/toolpad-app/src/toolpad/AppEditor/BindingEditor.tsx
Labels: bug 🐛

#1704 v0.0.41
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
  packages/toolpad/package.json
Labels: core

#1706 Create projects directories as needed
  packages/toolpad-app/src/server/localMode.ts
  packages/toolpad-app/src/toolpadDataSources/local/server.ts
Labels: core

#1709 New create component flow
  packages/toolpad-app/src/toolpad/AppEditor/HierarchyExplorer/CreateCodeComponentNodeDialog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentCatalog/ComponentCatalog.tsx
Labels: core

#1710 Make Toolpad work offline
  packages/toolpad-app/src/api.ts
  test/playwright/test.ts
Labels: core

#1716 Improve createQuery types
  packages/toolpad-core/src/createQuery.tsx
  packages/toolpad-core/src/types.ts
Labels: core, feature: Queries
