Repository mui/toolpad, pull requests merged in 2023-12, with the labels that each got.

#2951 Update documentation for HTTP requests secret handling
  docs/data/toolpad/concepts/data-providers.md
  docs/data/toolpad/concepts/http-requests.md
  docs/public/static/toolpad/docs/concepts/connecting-to-data/bound-secret.png
  docs/public/static/toolpad/docs/concepts/connecting-to-data/secrets.mp4
Labels: docs

#2920 Use ESM for CLI
  package.json
  packages/toolpad-app/cli.js
  packages/toolpad-app/cli.mjs
  packages/toolpad-app/cli/index.ts
  packages/toolpad-app/package.json
  packages/toolpad-app/src/server/FunctionsManager.ts
  packages/toolpad-app/src/server/appServerWorker.ts
  packages/toolpad-app/src/server/functionsDevWorker.ts
  packages/toolpad-app/src/server/functionsTypesWorker.ts
  packages/toolpad-app/src/server/index.ts
  packages/toolpad-app/src/server/localMode.ts
  packages/toolpad-app/src/server/toolpadAppBuilder.ts
  packages/toolpad-app/src/toolpad/vite.config.mts
  packages/toolpad-app/tsup.config.ts
  packages/toolpad-core/src/serverRuntime.ts
  test/playwright/localTest.ts
Labels: core

#2947 Allow omitting page.yml for code pages
  packages/toolpad-app/src/server/localMode.ts
Labels: core

#2954 Tweak titles to improve SERP results
  docs/data/pages.ts
  docs/data/toolpad/getting-started/examples-overview.md
  docs/data/toolpad/how-to-guides/embed-pages.md
Labels: docs

#2949 Make routing page name based
  docs/data/toolpad/concepts/page-properties.md
  docs/schemas/v1/definitions.json
  packages/toolpad-app/src/appDom/index.ts
  packages/toolpad-app/src/routes.ts
  packages/toolpad-app/src/runtime/CanvasHooksContext.tsx
  packages/toolpad-app/src/runtime/ToolpadApp.spec.tsx
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/server/localMode.ts
  packages/toolpad-app/src/server/schema.ts
  packages/toolpad-app/src/toolpad/AppEditor/BindingEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/HierarchyExplorer/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/EditorCanvasHost.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/QueryEditor/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/RenderPanel.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/UrlQueryEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PagesExplorer/CreatePageNodeDialog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PagesExplorer/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/index.tsx
  packages/toolpad-app/src/toolpad/AppState.tsx
  packages/toolpad-app/src/toolpad/Toolpad.tsx
  packages/toolpad-app/src/utils/domView.ts
  packages/toolpad-core/src/types.ts
  test/integration/backend-basic/base.spec.ts
  test/integration/backend-basic/baseProd.spec.ts
  test/integration/backend-basic/index.spec.ts
  test/integration/backend-basic/prod.spec.ts
  test/integration/bindings/index.spec.ts
  test/integration/bindings/navigation.spec.ts
  test/integration/codeComponents/index.spec.ts
  test/integration/components/basic.spec.ts
  test/integration/components/chart.spec.ts
  test/integration/components/form.spec.ts
  test/integration/components/list.spec.ts
  test/integration/data-grid/basic.spec.ts
  test/integration/editor/index.spec.ts
  test/integration/pages/index.spec.ts
  test/integration/rest-basic/index.spec.ts
  test/integration/runtime-basic/index.spec.ts
  test/integration/undo-redo/multiple-pages.spec.ts
  test/models/ToolpadEditor.ts
  test/models/ToolpadRuntime.ts
  test/visual/components/index.spec.ts
Labels: core

#2918 [Example] Run Next.js and Toolpad together
  examples/custom-server-nextjs/README.md
  examples/custom-server-nextjs/index.mjs
  examples/custom-server-nextjs/next-env.d.ts
  examples/custom-server-nextjs/next.config.mjs
  examples/custom-server-nextjs/package.json
  examples/custom-server-nextjs/pages/index.tsx
  examples/custom-server-nextjs/toolpad/.gitignore
  examples/custom-server-nextjs/toolpad/pages/page/page.yml
  examples/custom-server-nextjs/tsconfig.json
Labels: examples

#2957 Release 0.1.39
  CHANGELOG.md
  docs/package.json
  examples/custom-server-nextjs/package.json
  lerna.json
  packages/create-toolpad-app/package.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
  packages/toolpad-utils/package.json
  test/package.json
Labels: release 🚀

#2953 [WIP] Allow importing server functions in custom pages
  examples/react-pages/README.md
  examples/react-pages/data.json
  examples/react-pages/package.json
  examples/react-pages/toolpad/.gitignore
  examples/react-pages/toolpad/pages/qrcode/page.tsx
  examples/react-pages/toolpad/pages/qrcode/page.yml
  examples/react-pages/toolpad/resources/functions.ts
  packages/toolpad-app/src/runtime/index.tsx
  packages/toolpad-app/src/server/FunctionsManager.ts
  packages/toolpad-app/src/server/runtimeRpcServer.ts
  packages/toolpad-app/src/server/toolpadAppBuilder.ts
Labels: core

#2961 Unclutter UI for code pages
  packages/toolpad-app/src/appDom/index.ts
  packages/toolpad-app/src/toolpad/AppEditor/HierarchyExplorer/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentPanel.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/PageOptionsPanel.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/RenderPanel.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PagePanel.tsx
Labels: core

#2962 [examples] Polish examples
  examples/basic-crud-app/README.md
  examples/charts/README.md
  examples/custom-datagrid-column/README.md
  examples/custom-server-nextjs/README.md
  examples/custom-server/README.md
  examples/datagrid-columns/README.md
  examples/dog-app/README.md
  examples/google-sheet/README.md
  examples/graphql/README.md
  examples/npm-stats/README.md
  examples/qr-generator/README.md
  examples/react-pages/README.md
  examples/stripe-script/README.md
  examples/supabase/README.md
  examples/with-prisma-data-provider/README.md
  examples/with-prisma/README.md
  examples/with-wasm/README.md
Labels: examples

#2854 [docs] Why Toolpad? iteration
  docs/data/toolpad/getting-started/why-toolpad.md
Labels: docs

#2922 add a new feature as default Value
  docs/data/toolpad/reference/components/autocomplete.md
  packages/toolpad-app/src/toolpad/propertyControls/SelectOptions.tsx
  packages/toolpad-components/src/Autocomplete.tsx
  yarn.lock
Labels: enhancement

#2972 Move custom server documentation to concepts section
  docs/data/pages.ts
Labels: docs

#2975 Fix crash when a query name is the same as a page name
  packages/toolpad-app/src/appDom/index.ts
  packages/toolpad-app/src/toolpad/AppEditor/BindingEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/HierarchyExplorer/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PagePanel.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PagesExplorer/index.tsx
  test/integration/backend-basic/fixture/toolpad/pages/dataProviders/page.yml
Labels: regression

#2974 Fix sizing of page container
  examples/react-pages/toolpad/pages/foo/page.tsx
  examples/react-pages/toolpad/pages/foo/page.yml
  packages/toolpad-app/src/runtime/AppLayout.tsx
Labels: enhancement

#2979 [core] Upgrade monorepo
  yarn.lock
Labels: chore 🧹

#2980 v0.1.40
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/create-toolpad-app/package.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
  packages/toolpad-utils/package.json
Labels: release 🚀

#2977 Update custom server nextjs README.md
  examples/custom-server-nextjs/README.md
Labels: examples

#2931 Initial authorization implementation
  docs/schemas/v1/definitions.json
  packages/toolpad-app/src/appDom/index.ts
  packages/toolpad-app/src/constants.ts
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/runtime/auth.tsx
  packages/toolpad-app/src/server/localMode.ts
  packages/toolpad-app/src/server/schema.ts
  packages/toolpad-app/src/toolpad/AppEditor/AppAuthorizationEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/PageOptionsPanel.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/UrlQueryEditor.tsx
  packages/toolpad-app/src/toolpad/Toolpad.tsx
  packages/toolpad-app/src/toolpad/ToolpadShell/Header/index.tsx
  packages/toolpad-app/src/toolpad/ToolpadShell/index.tsx
Labels: core

#2983 Open links in the same tab unless configured otherwise
  docs/data/toolpad/reference/components/text.md
  examples/custom-server-nextjs/toolpad/pages/page/page.yml
  packages/toolpad-components/src/Text.tsx
Labels: new feature

#2984 Fix formatting for Date objects in the grid
  packages/toolpad-components/src/DataGrid.tsx
  packages/toolpad-core/src/jsBrowserRuntime.tsx
  test/integration/data-grid/basic.spec.ts
  test/integration/data-grid/fixture-basic/toolpad/application.yml
  test/integration/data-grid/fixture-basic/toolpad/pages/dateColumns/page.yml
  test/integration/data-grid/fixture-basic/toolpad/pages/page1/page.yml
Labels: bug 🐛

#2989 [core] Update `no-response` workflow
  .github/workflows/no-response.yml
Labels: core

#2992 [core] Update workflows and issue templates to reflect the updated label
  .github/ISSUE_TEMPLATE/1.bug.yml
  .github/ISSUE_TEMPLATE/2.feature.yml
  .github/ISSUE_TEMPLATE/3.rfc.yml
  .github/workflows/ensure-triage-label.yml
  .github/workflows/mark-duplicate.yml
Labels: core

#2990 improve vite omptimizeDeps after recent dataSource updates
  packages/toolpad-app/src/runtime/useDataProvider.ts
  packages/toolpad-app/src/server/FunctionsManager.ts
  packages/toolpad-app/src/server/functionsDevWorker.ts
  packages/toolpad-app/src/server/toolpadAppBuilder.ts
Labels: enhancement

#2994 v0.1.41
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/create-toolpad-app/package.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
  packages/toolpad-utils/package.json
Labels: release 🚀

#2995 Fix changelog
  CHANGELOG.md
Labels: chore 🧹

#2850 fix 2527, customize page name
  docs/data/toolpad/concepts/page-properties.md
  docs/public/static/toolpad/docs/concepts/page-properties/display-mode.png
  docs/schemas/v1/definitions.json
  packages/toolpad-app/src/appDom/index.ts
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/server/localMode.ts
  packages/toolpad-app/src/server/schema.ts
  packages/toolpad-app/src/toolpad/AppEditor/PageDisplayNameEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/PageOptionsPanel.tsx
Labels: new feature

#2998 Update monorepo
  docs/next.config.mjs
  yarn.lock
Labels: chore 🧹

#3008 Update yarn.lock
  yarn.lock
Labels: bug 🐛

#3010 Bring in some fixes from pnpm migration branch
  docs/package.json
  package.json
  packages/toolpad-app/package.json
  packages/toolpad-app/src/components/Devtools.tsx
  packages/toolpad-app/src/components/HarViewer.tsx
  packages/toolpad-app/src/server/functionsDevWorker.ts
  packages/toolpad-app/src/toolpadDataSources/rest/types.ts
  packages/toolpad-app/src/utils/har.ts
  packages/toolpad-app/typings/node-fetch-har.d.ts
  packages/toolpad-components/package.json
  packages/toolpad-components/src/components/ErrorOverlay.tsx
  packages/toolpad-core/src/server.ts
  packages/toolpad-core/src/serverRuntime.ts
  packages/toolpad-utils/src/hooks/index.ts
  test/package.json
  yarn.lock
Labels: core

#2993 Improve styling of the application navigation
  packages/toolpad-app/src/runtime/AppLayout.tsx
Labels: design: ui

#3001 Support updating rows in the data provider
  docs/data/toolpad/concepts/data-providers.md
  docs/public/static/toolpad/docs/concepts/data-providers/disable-editable.png
  docs/public/static/toolpad/docs/concepts/data-providers/editing.mp4
  examples/with-prisma-data-provider/toolpad/resources/crud.ts
  packages/toolpad-app/src/runtime/useDataProvider.ts
  packages/toolpad-app/src/server/FunctionsManager.ts
  packages/toolpad-app/src/server/functionsDevWorker.ts
  packages/toolpad-app/src/server/runtimeRpcServer.ts
  packages/toolpad-app/src/toolpad/propertyControls/GridColumns.tsx
  packages/toolpad-components/src/DataGrid.tsx
  packages/toolpad-core/src/runtime.tsx
  packages/toolpad-core/src/server.ts
  packages/toolpad-core/src/types.ts
  test/integration/backend-basic/fixture/toolpad/resources/myCrudData.ts
  test/integration/backend-basic/index.spec.ts
  test/integration/data-grid/basic.spec.ts
  test/utils/locators.ts
Labels: new feature

#2393 Add a new query panel
  packages/toolpad-app/src/appDom/index.ts
  packages/toolpad-app/src/components/Devtools.tsx
  packages/toolpad-app/src/components/EditableText.tsx
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/toolpad/AppEditor/AppEditorShell.tsx
  packages/toolpad-app/src/toolpad/AppEditor/BindingEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/ExplorerHeader.tsx
  packages/toolpad-app/src/toolpad/AppEditor/GlobalScopeExplorer.tsx
  packages/toolpad-app/src/toolpad/AppEditor/NodeMenu.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/BindableEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentCatalog/ComponentCatalog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentPanel.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ConnectionSelect.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/PageOptionsPanel.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ParametersEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/QueriesExplorer/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/QueryEditor/QueryEditorDialog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/QueryEditor/QueryEditorPanel.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/QueryEditor/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/RenderOverlay.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/UrlQueryEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PagePanel.tsx
  packages/toolpad-app/src/toolpad/AppEditor/QueryIcon.tsx
  packages/toolpad-app/src/toolpad/AppState.tsx
  packages/toolpad-app/src/toolpad/propertyControls/json.tsx
  packages/toolpad-app/src/toolpadDataSources/QueryInputPanel.tsx
  packages/toolpad-app/src/toolpadDataSources/TranformInput.tsx
  packages/toolpad-app/src/toolpadDataSources/client.tsx
  packages/toolpad-app/src/toolpadDataSources/googleSheets/client.tsx
  packages/toolpad-app/src/toolpadDataSources/local/FunctionSelector.tsx
  packages/toolpad-app/src/toolpadDataSources/local/client.tsx
  packages/toolpad-app/src/toolpadDataSources/local/shared.tsx
  packages/toolpad-app/src/toolpadDataSources/local/types.ts
  packages/toolpad-app/src/toolpadDataSources/rest/BodyEditor.tsx
  packages/toolpad-app/src/toolpadDataSources/rest/client.tsx
  packages/toolpad-app/src/toolpadDataSources/sql/client.tsx
  packages/toolpad-app/src/toolpadDataSources/useQueryPreview.ts
  packages/toolpad-app/src/types.ts
  packages/toolpad-app/src/utils/domView.ts
  packages/toolpad-app/src/utils/platform.tsx
  packages/toolpad-core/src/types.ts
  test/integration/backend-basic/fixture/toolpad/pages/basic/page.yml
  test/integration/backend-basic/index.spec.ts
  test/integration/editor/new.spec.ts
  test/integration/propControls/basic.spec.ts
  test/integration/rest-basic/index.spec.ts
  test/models/ToolpadEditor.ts
Labels: design: ui, design: ux, feature: Queries, feature: App Editor

#3013 Remove functions worker
  packages/toolpad-app/src/server/FunctionsManager.ts
  packages/toolpad-app/src/server/functionsDevWorker.ts
  packages/toolpad-app/src/server/functionsRuntime.ts
  packages/toolpad-app/tsup.config.ts
  packages/toolpad-core/package.json
  packages/toolpad-core/src/serverRuntime.ts
Labels: core

#3014 Guess proper default page titles based on page name
  packages/toolpad-app/src/appDom/index.ts
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageDisplayNameEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PagesExplorer/index.tsx
  packages/toolpad-app/src/toolpad/ToolpadHomeShell.tsx
  packages/toolpad-utils/package.json
  packages/toolpad-utils/src/strings.spec.ts
  packages/toolpad-utils/src/strings.ts
  test/integration/duplication/index.spec.ts
  test/integration/editor/new.spec.ts
  test/integration/pages/index.spec.ts
  test/integration/undo-redo/multiple-pages.spec.ts
  yarn.lock
Labels: enhancement

#3015 Add labels to form validation properties
  docs/data/toolpad/reference/components/autocomplete.md
  packages/toolpad-components/src/Autocomplete.tsx
  packages/toolpad-components/src/Form.tsx
Labels: enhancement

#3016 Introduce pagesManifest
  docs/schemas/v1/definitions.json
  packages/toolpad-app/src/appDom/index.ts
  packages/toolpad-app/src/server/appBuilderWorker.ts
  packages/toolpad-app/src/server/appServerWorker.ts
  packages/toolpad-app/src/server/index.ts
  packages/toolpad-app/src/server/localMode.ts
  packages/toolpad-app/src/server/schema.ts
  packages/toolpad-app/src/server/toolpadAppBuilder.ts
  packages/toolpad-app/src/types.ts
  packages/toolpad-utils/src/fs.ts
Labels: core

#3017 Remove components from appDom
  packages/toolpad-app/src/appDom/index.ts
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/runtime/toolpadComponents/index.tsx
  packages/toolpad-app/src/server/appBuilderWorker.ts
  packages/toolpad-app/src/server/index.ts
  packages/toolpad-app/src/server/localMode.ts
  packages/toolpad-app/src/server/projectRpcServer.ts
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentCatalog/ComponentCatalog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PagesExplorer/CreateCodeComponentNodeDialog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/toolpadComponents.tsx
  packages/toolpad-app/src/toolpad/propertyControls/GridColumns.tsx
Labels: core

#3018 v0.1.42
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/create-toolpad-app/package.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-app/src/server/toolpadAppBuilder.ts
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
  packages/toolpad-utils/package.json
Labels: release 🚀

#3025 [core] Delete strange issue template
  .github/ISSUE_TEMPLATE/4.design.yml
Labels: core

#3026 [docs] Fix missing issue template
  .github/ISSUE_TEMPLATE/4.docs-feedback.yml
  docs/next.config.mjs
Labels: docs

#3028 [docs] Flatten the getting-started folder
  README.md
  docs/README.md
  docs/data/pages.ts
  docs/pages/toolpad/getting-started/index.js
  docs/public/_redirects
  packages/toolpad-app/src/constants.ts
Labels: docs

#3031 [website] Update the social preview image
  docs/pages/toolpad/index.js
  docs/public/static/toolpad/marketing/social-preview.jpg
  docs/public/static/toolpad/marketing/toolpad-og.jpg
Labels: website

#3029 [code-infra] Sync bug issue template
  .github/ISSUE_TEMPLATE/1.bug.yml
  .github/workflows/issue-cleanup.yml
Labels: enhancement, scope: code-infra

#3032 [docs] Fix typo
  docs/data/toolpad/concepts/data-providers.md
Labels: docs

#3033 [chore] Upgrade monorepo 5.15.2
  docs/babel.config.js
  yarn.lock
Labels: chore 🧹

#3035 v0.1.43
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/create-toolpad-app/package.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
  packages/toolpad-utils/package.json
Labels: release 🚀

#3027 [docs] Lint next.config.mjs
  docs/next.config.mjs
  docs/tsconfig.json
Labels: enhancement, scope: docs-infra
