Repository mui/toolpad, pull requests merged in 2023-01, with the labels that each got.

#1502 Make sure npm package is splitted out correctly
  renovate.json
Labels: core

#1417 Undo/redo through different views
  .gitignore
  packages/toolpad-app/src/toolpad/AppEditor/CodeComponentEditor/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/ConnectionEditor/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/HierarchyExplorer/CreateCodeComponentNodeDialog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/HierarchyExplorer/CreateConnectionNodeDialog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/HierarchyExplorer/CreatePageNodeDialog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/HierarchyExplorer/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentPanel.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/PageEditorProvider.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/PageModuleEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/QueryEditor/QueryEditorDialog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/QueryEditor/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/RenderOverlay.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/RenderPanel.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/UrlQueryEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/index.tsx
  packages/toolpad-app/src/toolpad/DomLoader.tsx
  packages/toolpad-app/src/toolpad/hooks/useUndoRedo.ts
  packages/toolpad-app/src/utils/useShortcut.ts
  test/integration/undo-redo/2pages.json
  test/integration/undo-redo/index.spec.ts
  test/models/ToolpadEditor.ts
Labels: core, enhancement

#1504 Datepicker format handling changes
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/BindableEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentCatalog/ComponentCatalog.tsx
  packages/toolpad-components/src/DatePicker.tsx
Labels: feature: App Editor

#1508 Just re-export the prettier config
  prettier.config.js
Labels: core

#1509 Do not rename nodes when migrating Typography components
  packages/toolpad-app/src/appDom/migrations/v4.ts
  packages/toolpad-app/src/appDom/migrations/v5.ts
Labels: core

#1507 Fix function editor save
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/QueryEditor/QueryEditorDialog.tsx
  packages/toolpad-app/src/toolpadDataSources/function/client.tsx
  packages/toolpad-app/src/utils/react.tsx
  test/integration/function-basic/functionDom.json
  test/integration/function-basic/index.spec.ts
Labels: core

#1513 Don't import from dist folders
  packages/toolpad-app/src/toolpadDataSources/rest/BodyEditor.tsx
Labels: core

#1512 Fix dependabot vulnerabilities
  yarn.lock
Labels: core

#1514 v0.0.34
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
Labels: core

#1511 Restructure installation docs
  docs/data/toolpad/getting-started/installation.md
Labels: docs

#1462 Custom column types
  packages/toolpad-app/src/runtime/AppContext.tsx
  packages/toolpad-app/src/runtime/AppModulesProvider.tsx
  packages/toolpad-app/src/runtime/ComponentsContext.tsx
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/toolpad/AppEditor/BindingEditor.tsx
  packages/toolpad-app/src/toolpad/DomLoader.tsx
  packages/toolpad-app/src/toolpad/propertyControls/GridColumns.tsx
  packages/toolpad-app/src/toolpadDataSources/context.tsx
  packages/toolpad-app/src/utils/react.tsx
  packages/toolpad-components/src/DataGrid.tsx
  packages/toolpad-core/src/componentsContext.tsx
  packages/toolpad-core/src/index.tsx
  packages/toolpad-core/src/runtime.tsx
  packages/toolpad-core/src/utils/index.ts
  packages/toolpad-core/src/utils/misc.ts
  packages/toolpad-core/src/utils/react.tsx
  test/integration/data-grid/codeComponentCell.json
  test/integration/data-grid/index.spec.ts
Labels: feature: App Editor

#1515 Promote previously experimental config
  packages/toolpad-app/next.config.mjs
  packages/toolpad-app/prisma/schema.prisma
Labels: core

#1517 Correct types in Datepicker
  packages/toolpad-components/src/DatePicker.tsx
Labels: core

#1518 Add inline documentation to components and properties
  packages/toolpad-app/package.json
  packages/toolpad-app/src/components/MarkdownTooltip.tsx
  packages/toolpad-app/src/theme.ts
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/NodeAttributeEditor.tsx
  packages/toolpad-components/src/Button.tsx
  packages/toolpad-components/src/DataGrid.tsx
  packages/toolpad-components/src/DatePicker.tsx
  packages/toolpad-components/src/Image.tsx
  packages/toolpad-components/src/Paper.tsx
  packages/toolpad-components/src/Select.tsx
  packages/toolpad-components/src/Stack.tsx
  packages/toolpad-components/src/Text.tsx
  packages/toolpad-components/src/TextField.tsx
  packages/toolpad-components/src/constants.tsx
  packages/toolpad-core/src/types.ts
Labels: feature: Components

#1526 Some component library tweaks
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentCatalog/ComponentCatalog.tsx
  test/models/ToolpadEditor.ts
Labels: design: ux

#1541 Remove obsolete dom reducer actions
  packages/toolpad-app/src/appDom/index.ts
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/NodeDropArea.tsx
  packages/toolpad-app/src/toolpad/DomLoader.tsx
Labels: core

#1544 Fix templates after dog API changed
  packages/toolpad-app/src/server/appTemplateDoms/images-demo.json
  packages/toolpad-app/src/server/appTemplateDoms/images.json
Labels: test, bug 🐛

#1545 v0.0.35
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
Labels: core

#1550 New canvas bridge implementation
  packages/toolpad-app/src/canvas/ToolpadBridge.tsx
  packages/toolpad-app/src/canvas/index.tsx
  packages/toolpad-app/src/runtime/ToolpadApp.spec.tsx
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/runtime/evalJsBindings.ts
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/EditorCanvasHost.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/RenderOverlay.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/RenderPanel.tsx
  packages/toolpad-core/package.json
  packages/toolpad-core/src/runtime.tsx
  packages/toolpad-core/src/types.ts
Labels: core

#1548 Reorganize js evaluation across project
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/runtime/evalJsBindings.ts
  packages/toolpad-app/src/server/evalExpression.spec.ts
  packages/toolpad-app/src/server/evalExpression.ts
  packages/toolpad-app/src/server/evaluateBindable.ts
  packages/toolpad-app/src/toolpad/AppEditor/BindingEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/BindableEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/NodeAttributeEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ParametersEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/QueryEditor/QueryEditorDialog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/useEvaluateLiveBinding.ts
  packages/toolpad-app/src/toolpad/propertyControls/RowIdFieldSelect.tsx
  packages/toolpad-app/src/toolpadDataSources/function/client.tsx
  packages/toolpad-app/src/toolpadDataSources/postgres/client.tsx
  packages/toolpad-app/src/toolpadDataSources/rest/BodyEditor.tsx
  packages/toolpad-app/src/toolpadDataSources/rest/client.tsx
  packages/toolpad-app/src/toolpadDataSources/rest/runtime.tsx
  packages/toolpad-app/src/toolpadDataSources/rest/server.ts
  packages/toolpad-app/src/toolpadDataSources/rest/shared.ts
  packages/toolpad-app/src/utils/collections.ts
  packages/toolpad-app/src/utils/errors.ts
  packages/toolpad-app/src/utils/strings.ts
  packages/toolpad-core/src/jsRuntime.tsx
  packages/toolpad-core/src/types.ts
  packages/toolpad-core/src/utils/collections.ts
  packages/toolpad-core/src/utils/errors.ts
  packages/toolpad-core/src/utils/strings.ts
Labels: core

#1549 Add tabs and container components
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentCatalog/ComponentCatalog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentCatalog/ComponentCatalogItem.tsx
  packages/toolpad-app/src/toolpadComponents/index.tsx
  packages/toolpad-components/src/Container.tsx
  packages/toolpad-components/src/Tabs.tsx
  packages/toolpad-components/src/index.tsx
Labels: feature: App Editor

#1568 Rename Tabs main prop
  packages/toolpad-components/src/Tabs.tsx
Labels: feature: App Editor

#1554 Avoid resubscribing in useSyncExternalStore on every render
  packages/toolpad-app/src/components/NoSsr.tsx
  packages/toolpad-app/src/utils/react.tsx
  packages/toolpad-app/src/utils/useLocalStorageState.ts
Labels: core

#1575 Fix DatePicker localization issues
  packages/toolpad-components/package.json
  packages/toolpad-components/src/DatePicker.tsx
  yarn.lock
Labels: bug 🐛

#1581 Release v0.0.36
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
Labels: core

#1576 Remove onChangeHandler from Select and TextField
  packages/toolpad-components/src/Select.tsx
  packages/toolpad-components/src/TextField.tsx
Labels: enhancement

#1580 Upgrade monorepo dependency
  docs/next.config.mjs
  docs/pages/_app.js
  yarn.lock
Labels: core

#1577 Recreate yarn.lock
  packages/toolpad-components/src/DatePicker.tsx
  yarn.lock
Labels: core

#1585 Make applyTransform runtime agnostic
  packages/toolpad-app/src/server/applyTransform.ts
  packages/toolpad-app/src/server/data.ts
  packages/toolpad-app/src/server/evalExpression.spec.ts
  packages/toolpad-app/src/server/evalExpression.ts
  packages/toolpad-app/src/toolpadDataSources/applyTransform.ts
  packages/toolpad-app/src/toolpadDataSources/rest/shared.ts
Labels: core

#1584 Split browser and server js runtimes
  packages/toolpad-app/next.config.mjs
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/server/data.ts
  packages/toolpad-app/src/server/evalExpression.spec.ts
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/NodeAttributeEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/QueryEditor/QueryEditorDialog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/index.tsx
  packages/toolpad-app/src/toolpadDataSources/function/client.tsx
  packages/toolpad-app/src/toolpadDataSources/postgres/client.tsx
  packages/toolpad-app/src/toolpadDataSources/rest/BodyEditor.tsx
  packages/toolpad-app/src/toolpadDataSources/rest/client.tsx
  packages/toolpad-app/src/toolpadDataSources/rest/runtime.tsx
  packages/toolpad-app/src/toolpadDataSources/rest/server.ts
  packages/toolpad-app/tsconfig.json
  packages/toolpad-core/package.json
  packages/toolpad-core/src/jsBrowserRuntime.tsx
  packages/toolpad-core/src/jsRuntime.tsx
  packages/toolpad-core/src/jsServerRuntime.tsx
Labels: core

#1537 Add FilePicker component
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentCatalog/ComponentCatalogItem.tsx
  packages/toolpad-app/src/toolpadComponents/index.tsx
  packages/toolpad-components/src/FilePicker.tsx
  packages/toolpad-components/src/index.tsx
  test/integration/file-picker/dom.json
  test/integration/file-picker/index.spec.ts
  test/integration/file-picker/test.txt
Labels: feature: App Editor

#1565 Fix navigation through DOM views with pages
  packages/toolpad-app/src/routes.ts
  packages/toolpad-app/src/toolpad/AppEditor/AppEditorShell.tsx
  packages/toolpad-app/src/toolpad/AppEditor/CodeComponentEditor/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/ConnectionEditor/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/HierarchyExplorer/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/PageModuleEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/QueryEditor/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/UrlQueryEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/index.tsx
  packages/toolpad-app/src/toolpad/DomLoader.tsx
  packages/toolpad-app/src/toolpad/hooks/useUndoRedo.ts
  packages/toolpad-app/src/utils/domView.ts
  test/integration/pages/2pages.json
  test/integration/pages/index.spec.ts
  test/integration/undo-redo/index.spec.ts
Labels: bug 🐛, regression

#1600 v0.0.37
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
Labels: core

#1588 Add new custom GA events to demo
  packages/toolpad-app/src/toolpad/Apps/index.tsx
  packages/toolpad-app/src/toolpad/ToolpadShell/DemoBar.tsx
  packages/toolpad-app/src/toolpadDataSources/QueryInputPanel.tsx
  packages/toolpad-app/src/utils/ga.ts
Labels: core
