Repository mui/toolpad, pull requests merged in 2023-03, with the labels that each got.

#1697 Turn off preview environments
  render.yaml
Labels: core

#1707 Open browser to app as part of of `dev` script
  packages/toolpad-app/cli/index.ts
  packages/toolpad-app/cli/openBrowser.ts
Labels: core

#1725 Fix config file being deleted
  packages/toolpad-app/cli/index.ts
  packages/toolpad-app/pages/api/runtime/[[...path]].ts
  packages/toolpad-app/src/server/localMode.ts
Labels: core, bug 🐛

#1726 Updates to `toolpad-app/cli`
  packages/toolpad-app/cli/index.ts
  packages/toolpad-app/cli/openBrowser.ts
  packages/toolpad-app/package.json
  yarn.lock
Labels: core

#1735 Allow direction13 embedding in iframes
  packages/toolpad-app/next.config.mjs
  packages/toolpad-app/pages/prod/[[...path]].tsx
Labels: core

#1750 Fix dragged element corners
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentCatalog/ComponentCatalogItem.tsx
Labels: enhancement

#1757 Fix toolpad process output disappearing
  packages/toolpad-app/cli/index.ts
Labels: core

#1700 Add create-toolpad-app CLI
  .circleci/config.yml
  docker/images/toolpad/Dockerfile
  packages/create-toolpad-app/README.md
  packages/create-toolpad-app/package.json
  packages/create-toolpad-app/src/index.ts
  packages/create-toolpad-app/tsconfig.json
  yarn.lock
Labels: core

#1761 V0.1.0
  CHANGELOG.md
  RELEASE.md
  docs/package.json
  lerna.json
  package.json
  packages/create-toolpad-app/package.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
  packages/toolpad/package.json
Labels: core

#1766 Rename dev13 script to dev
  CONTRIBUTING.md
  package.json
  packages/create-toolpad-app/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
  packages/toolpad/package.json
Labels: core

#1767 Add Toolpad to cspell config for the workspace
  .vscode/settings.json
  CONTRIBUTING.md
Labels: core

#1779 Add docs contributing instructions
  CONTRIBUTING.md
Labels: docs

#1780 Update moduleresolution for core and components
  .vscode/settings.json
  packages/toolpad-app/package.json
  packages/toolpad-app/src/canvas/ToolpadBridge.tsx
  packages/toolpad-app/src/server/localMode.ts
  packages/toolpad-app/src/utils/react.tsx
  packages/toolpad-app/src/utils/useLocalStorageState.ts
  packages/toolpad-components/src/Button.tsx
  packages/toolpad-components/src/Container.tsx
  packages/toolpad-components/src/DataGrid.tsx
  packages/toolpad-components/src/DatePicker.tsx
  packages/toolpad-components/src/Image.tsx
  packages/toolpad-components/src/List.tsx
  packages/toolpad-components/src/Paper.tsx
  packages/toolpad-components/src/Select.tsx
  packages/toolpad-components/src/Stack.tsx
  packages/toolpad-components/src/Text.tsx
  packages/toolpad-components/src/TextField.tsx
  packages/toolpad-components/src/index.tsx
  packages/toolpad-components/tsconfig.json
  packages/toolpad-core/package.json
  packages/toolpad-core/src/index.tsx
  packages/toolpad-core/src/runtime.tsx
  packages/toolpad-core/src/utils/Emitter.ts
  packages/toolpad-core/tsconfig.json
  yarn.lock
Labels: core

#1788 Update release instructions
  RELEASE.md
Labels: docs

#1787 Remove Prisma, isolated-vm and dead code
  .circleci/config.yml
  .dockerignore
  .eslintignore
  .github/workflows/release-docker.yml
  .gitignore
  .vscode/extensions.json
  CONTRIBUTING.md
  package.json
  packages/toolpad-app/package.json
  packages/toolpad-app/pages/api/rpc.ts
  packages/toolpad-app/prisma/migrations/20220304091607_init/migration.sql
  packages/toolpad-app/prisma/migrations/20220309160452_multi_apps/migration.sql
  packages/toolpad-app/prisma/migrations/20220315165604_latest/migration.sql
  packages/toolpad-app/prisma/migrations/20220325150443_secrets/migration.sql
  packages/toolpad-app/prisma/migrations/20220407140255_app_created_at/migration.sql
  packages/toolpad-app/prisma/migrations/20220511155305_add_query/migration.sql
  packages/toolpad-app/prisma/migrations/20220608160038_/migration.sql
  packages/toolpad-app/prisma/migrations/20220616175854_navigate/migration.sql
  packages/toolpad-app/prisma/migrations/20220728084413_mutation/migration.sql
  packages/toolpad-app/prisma/migrations/20220811171726_add_dom/migration.sql
  packages/toolpad-app/prisma/migrations/20220915154400_publics/migration.sql
  packages/toolpad-app/prisma/migrations/migration_lock.toml
  packages/toolpad-app/prisma/schema.prisma
  packages/toolpad-app/src/server/data.ts
  packages/toolpad-app/src/toolpad/AppOptions/AppDeleteDialog.tsx
  packages/toolpad-app/src/toolpad/AppOptions/AppDuplicateDialog.tsx
  packages/toolpad-app/src/toolpad/AppOptions/AppNameEditable.tsx
  packages/toolpad-app/src/toolpad/AppOptions/AppSettingsDialog.tsx
  packages/toolpad-app/src/toolpadDataSources/client.tsx
  packages/toolpad-app/src/toolpadDataSources/function/client.tsx
  packages/toolpad-app/src/toolpadDataSources/function/execFunction.spec.ts
  packages/toolpad-app/src/toolpadDataSources/function/execFunction.ts
  packages/toolpad-app/src/toolpadDataSources/function/runtime.tsx
  packages/toolpad-app/src/toolpadDataSources/function/runtime/abortController.ts
  packages/toolpad-app/src/toolpadDataSources/function/runtime/console.ts
  packages/toolpad-app/src/toolpadDataSources/function/runtime/domException.ts
  packages/toolpad-app/src/toolpadDataSources/function/runtime/fetch.ts
  packages/toolpad-app/src/toolpadDataSources/function/runtime/formData.ts
  packages/toolpad-app/src/toolpadDataSources/function/runtime/headers.ts
  packages/toolpad-app/src/toolpadDataSources/function/runtime/index.ts
  packages/toolpad-app/src/toolpadDataSources/function/runtime/textEncoding.ts
  packages/toolpad-app/src/toolpadDataSources/function/runtime/timers.ts
  packages/toolpad-app/src/toolpadDataSources/function/runtime/types.ts
  packages/toolpad-app/src/toolpadDataSources/function/runtime/url.ts
  packages/toolpad-app/src/toolpadDataSources/function/runtime/web-streams.ts
  packages/toolpad-app/src/toolpadDataSources/function/server.ts
  packages/toolpad-app/src/toolpadDataSources/function/types.ts
  packages/toolpad-app/src/toolpadDataSources/runtime.tsx
  packages/toolpad-app/src/toolpadDataSources/server.ts
  scripts/releaseDocker.mjs
  test/integration/data-grid/fixture-basic/toolpad.yml
  test/integration/data-grid/fixture-basic/toolpad/queries.ts
  yarn.lock
Labels: core

#1789 Fixes on the dev pipeline
  package.json
  packages/create-toolpad-app/package.json
  packages/create-toolpad-app/tsconfig.json
  packages/toolpad-app/package.json
  packages/toolpad-app/tsconfig.json
  packages/toolpad-components/package.json
  packages/toolpad-components/tsconfig.json
  packages/toolpad-core/package.json
  packages/toolpad-core/tsconfig.json
  packages/toolpad/package.json
  packages/toolpad/tsconfig.json
Labels: core

#1791 Dependency cleanup
  .circleci/config.yml
  packages/toolpad-app/package.json
  yarn.lock
Labels: core

#1790 Improve dataGrid.selection types
  packages/toolpad-app/src/components/MonacoEditor.tsx
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/JsExpressionEditor.tsx
  packages/toolpad-app/tsconfig.json
  packages/toolpad-components/src/DataGrid.tsx
  packages/toolpad-core/src/types.ts
Labels: core

#1784 Fix changing tabs closing query editor
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/QueryEditor/index.tsx
  packages/toolpad-app/src/utils/geometry.ts
  test/integration/rest-basic/index.spec.ts
Labels: bug 🐛

#1796 Fix errors when running the project the first time
  packages/toolpad-app/cli/index.ts
  packages/toolpad-app/cli/projectFiles/toolpad-generated-gitignore
  packages/toolpad-app/pages/api/runtime/[[...path]].ts
  packages/toolpad-app/src/server/localMode.ts
  packages/toolpad-app/src/toolpadDataSources/local/server.ts
  packages/toolpad-app/src/utils/fs.ts
Labels: core

#1797 Clean up more obsolete things in the repo
  docker-compose.dev.yml
  docker-compose.legacy-test.yml
  docker-compose.test.yml
  package.json
  render.yaml
  renovate.json
Labels: core

#1798 Remove example and docker files
  docker/compose/docker-compose.yml
  docker/images/toolpad/Dockerfile
  examples/README.md
  examples/bundleSize/.gitignore
  examples/bundleSize/package.json
  examples/bundleSize/toolpad.yml
  examples/bundleSize/toolpad/components/diff.tsx
  examples/bundleSize/toolpad/components/percent.tsx
  examples/bundleSize/toolpad/queries.ts
  packages/create-toolpad-app/package.json
  packages/toolpad/package.json
  renovate.json
Labels: core

#1799 Remove postgres
  .circleci/config.yml
Labels: core

#1723 Use next.js custom server
  packages/toolpad-app/cli/index.ts
  packages/toolpad-app/cli/server.ts
  packages/toolpad-app/src/config.ts
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/JsExpressionEditor.tsx
  packages/toolpad-app/src/toolpad/ToolpadShell/Header/UserFeedback/index.tsx
  packages/toolpad-app/src/utils/har.ts
Labels: core

#1809 Disable property control for controlled properties
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/NodeAttributeEditor.tsx
  test/integration/propControls/index.spec.ts
Labels: core

#1808 Improve UX around integration testing
  .gitignore
  CONTRIBUTING.md
  package.json
  packages/toolpad-app/cli/index.ts
  packages/toolpad-app/cli/server.ts
  test/playwright/localTest.ts
Labels: test

#1818 Use node name in the canvas HUD
  packages/toolpad-app/cli/index.ts
  packages/toolpad-app/src/toolpad/AppEditor/BindingEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/NodeHud.tsx
  test/integration/editor/index.spec.ts
  test/models/ToolpadEditor.ts
Labels: core

#1822 Start a guide on how to locally run PRs
  CONTRIBUTING.md
Labels: docs

#1823 v0.1.1
  CHANGELOG.md
  RELEASE.md
  docs/package.json
  lerna.json
  packages/create-toolpad-app/package.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
  packages/toolpad/package.json
Labels: core

#1794 Rewrite argument handling in `@mui/toolpad` CLI with `yargs`
  packages/toolpad-app/cli/index.ts
Labels: core

#1820 Remove quickjs-emscripten
  packages/toolpad-app/next.config.mjs
  packages/toolpad-app/package.json
  packages/toolpad-app/src/toolpad/AppEditor/index.tsx
  packages/toolpad-app/src/toolpadDataSources/rest/shared.ts
  packages/toolpad-core/src/jsServerRuntime.tsx
Labels: core

#1813 Use worker scoped fixtures for integration tests
  .gitignore
  test/integration/components/basic.spec.ts
  test/integration/components/index.spec.ts
  test/integration/components/list.spec.ts
  test/integration/data-grid/basic.spec.ts
  test/integration/data-grid/custom.spec.ts
  test/integration/data-grid/index.spec.ts
  test/integration/editor/index.spec.ts
  test/integration/editor/new.spec.ts
  test/integration/propControls/basic.spec.ts
  test/integration/propControls/defaults.spec.ts
  test/integration/propControls/index.spec.ts
  test/integration/undo-redo/basic.spec.ts
  test/integration/undo-redo/index.spec.ts
  test/integration/undo-redo/multiple-pages.spec.ts
  test/models/shared.ts
  test/playwright/localTest.ts
Labels: test

#1827 Remove deprecated scope query
  packages/toolpad-app/src/toolpadDataSources/rest/client.tsx
  packages/toolpad-app/src/toolpadDataSources/rest/shared.ts
Labels: core

#1834 Fix broken theming
  packages/toolpad-app/src/runtime/AppThemeProvider.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ThemeEditor.tsx
  test/integration/theme/fixture/toolpad.yml
  test/integration/theme/index.spec.ts
  test/models/ToolpadEditor.ts
Labels: bug 🐛, regression

#1840 Fix issues around custom datagrid columns
  examples/custom-datagrid-column/README.md
  examples/custom-datagrid-column/package.json
  examples/custom-datagrid-column/toolpad.yaml
  examples/custom-datagrid-column/toolpad/components/AgeColumn.tsx
  examples/custom-datagrid-column/toolpad/components/FullNameColumn.tsx
  packages/toolpad-app/src/toolpad/propertyControls/GridColumns.tsx
  test/integration/data-grid/custom.spec.ts
  test/integration/data-grid/fixture-custom/toolpad/components/Other.tsx
Labels: bug 🐛, regression

#1842 Load queries by name instead of id
  packages/toolpad-app/middleware.ts
  packages/toolpad-app/pages/api/data/[pageName]/[queryName].ts
  packages/toolpad-app/pages/api/data/[queryId].ts
  packages/toolpad-app/src/appDom/index.ts
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/runtime/useDataQuery.ts
  packages/toolpad-app/src/toolpad/AppState.tsx
Labels: core

#1819 Add app navigation sidebar
  packages/toolpad-app/src/appDom/index.ts
  packages/toolpad-app/src/canvas/index.tsx
  packages/toolpad-app/src/routes.ts
  packages/toolpad-app/src/runtime/AppContext.tsx
  packages/toolpad-app/src/runtime/AppNavigation.tsx
  packages/toolpad-app/src/runtime/AppOverview.tsx
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/toolpad/AppEditor/AppEditorShell.tsx
  packages/toolpad-app/src/toolpad/AppEditor/HierarchyExplorer/CreatePageNodeDialog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/PageOptionsPanel.tsx
  packages/toolpad-app/src/toolpad/ToolpadShell/Header/index.tsx
  packages/toolpad-app/src/types.ts
  test/models/ToolpadRuntime.ts
Labels: new feature

#1843 v0.1.2
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/create-toolpad-app/package.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
  packages/toolpad/package.json
Labels: core

#1844 Editor UX fixes
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/NodeHud.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/RenderOverlay.tsx
Labels: bug 🐛
