Repository mui/toolpad, pull requests merged in 2024-01, with the labels that each got.

#2925 Add authentication
  .vscode/settings.json
  docs/schemas/v1/definitions.json
  packages/toolpad-app/package.json
  packages/toolpad-app/src/appDom/index.ts
  packages/toolpad-app/src/constants.ts
  packages/toolpad-app/src/runtime/AppLayout.tsx
  packages/toolpad-app/src/runtime/PreviewHeader.tsx
  packages/toolpad-app/src/runtime/SignInPage.tsx
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/runtime/auth.tsx
  packages/toolpad-app/src/runtime/useAuth.ts
  packages/toolpad-app/src/server/auth.ts
  packages/toolpad-app/src/server/httpApiAdapters.ts
  packages/toolpad-app/src/server/index.ts
  packages/toolpad-app/src/server/localMode.ts
  packages/toolpad-app/src/server/schema.ts
  packages/toolpad-app/src/server/toolpadAppServer.ts
  packages/toolpad-app/src/toolpad/AppEditor/AppAuthorizationEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/BindingEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/PageOptionsPanel.tsx
  packages/toolpad-app/src/types.ts
  packages/toolpad-app/tsup.config.ts
  packages/toolpad-components/src/Chart.tsx
  yarn.lock
Labels: new feature

#3041 [docs] Fix dead link to live demo
  examples/basic-crud-app/README.md
  examples/npm-stats/README.md
  examples/qr-generator/README.md
Labels: docs, bug 🐛

#3043 Hosted 5 more examples on railway and linked them to docs
  examples/charts/README.md
  examples/dog-app/README.md
  examples/graphql/README.md
  examples/supabase/README.md
  examples/with-prisma-data-provider/README.md
Labels: examples

#3049 v0.1.44
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/create-toolpad-app/package.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
  packages/toolpad-utils/package.json
Labels: release 🚀

#3044 Remove react-devtools
  .eslintrc.js
  .gitignore
  packages/toolpad-app/package.json
  packages/toolpad-app/reactDevtools/bootstrap.ts
  packages/toolpad-app/src/canvas/getPageViewState.ts
  packages/toolpad-app/src/canvas/index.tsx
  packages/toolpad-app/src/runtime/CanvasHooksContext.tsx
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/server/appServerWorker.ts
  packages/toolpad-app/src/server/index.ts
  packages/toolpad-app/src/server/toolpadAppBuilder.ts
  packages/toolpad-app/tsup.config.ts
  packages/toolpad-app/typings/react-devtools-inline.d.ts
  packages/toolpad-components/src/PageColumn.tsx
  packages/toolpad-components/src/PageRow.tsx
  packages/toolpad-core/src/constants.ts
  packages/toolpad-core/src/runtime.tsx
  yarn.lock
Labels: core

#3057 Remove cache from useStorageState
  packages/toolpad-utils/src/hooks/useStorageState.ts
Labels: core

#3058 Add serverside row creation
  docs/data/toolpad/concepts/data-providers.md
  docs/public/static/toolpad/docs/concepts/data-providers/creating.mp4
  examples/with-prisma-data-provider/toolpad/application.yml
  examples/with-prisma-data-provider/toolpad/pages/crud/page.yml
  examples/with-prisma-data-provider/toolpad/pages/cursorBased/page.yml
  examples/with-prisma-data-provider/toolpad/pages/indexBased/page.yml
  examples/with-prisma-data-provider/toolpad/resources/crud.ts
  packages/toolpad-components/src/DataGrid.tsx
  packages/toolpad-core/src/types.ts
  test/integration/backend-basic/fixture/toolpad/application.yml
  test/integration/backend-basic/fixture/toolpad/pages/basic/page.yml
  test/integration/backend-basic/fixture/toolpad/pages/crud/page.yml
  test/integration/backend-basic/fixture/toolpad/pages/dataProviders/page.yml
  test/integration/backend-basic/fixture/toolpad/pages/extractedTypes/page.yml
  test/integration/backend-basic/fixture/toolpad/pages/serialization/page.yml
  test/integration/backend-basic/fixture/toolpad/resources/myCrudData.ts
  test/integration/backend-basic/index.spec.ts
  test/integration/components/basic.spec.ts
  test/integration/data-grid/basic.spec.ts
  test/integration/data-grid/custom.spec.ts
  test/integration/editor/index.spec.ts
  test/integration/propControls/basic.spec.ts
  test/integration/propControls/defaults.spec.ts
  test/integration/undo-redo/basic.spec.ts
  test/utils/clickCenter.ts
  test/utils/locators.ts
  test/visual/components/index.spec.ts
Labels: new feature

#3073 Don't create private packages with create-toolpad-app
  packages/create-toolpad-app/src/index.ts
Labels: enhancement

#3072 Update help text of --install flag in create-toolpad-app
  packages/create-toolpad-app/src/index.ts
Labels: enhancement

#3076 Handle errors during data provider introspection
  packages/toolpad-components/src/DataGrid.tsx
Labels: core

#3074 Make Toolpad apps compatible with pnpm
  packages/toolpad-app/src/server/toolpadAppBuilder.ts
Labels: core

#3078 v0.1.45
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/create-toolpad-app/package.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
  packages/toolpad-utils/package.json
Labels: release 🚀

#3047 Add universal required email configuration for authentication
  docs/schemas/v1/definitions.json
  packages/toolpad-app/src/appDom/index.ts
  packages/toolpad-app/src/runtime/AppLayout.tsx
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/runtime/useAuth.ts
  packages/toolpad-app/src/server/auth.ts
  packages/toolpad-app/src/server/index.ts
  packages/toolpad-app/src/server/schema.ts
  packages/toolpad-app/src/server/toolpadAppServer.ts
  packages/toolpad-app/src/toolpad/AppEditor/AppAuthorizationEditor.tsx
  packages/toolpad-app/src/toolpad/Toolpad.tsx
Labels: new feature

#3048 Improve authorization middleware
  packages/toolpad-app/src/server/auth.ts
  packages/toolpad-app/src/server/index.ts
  packages/toolpad-app/src/server/toolpadAppServer.ts
Labels: enhancement

#3084 Tweak data providers UI in the grid
  packages/toolpad-components/src/DataGrid.tsx
Labels: enhancement

#3087 Fix screenshot flakeyness
  packages/toolpad-app/src/components/Devtools.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/QueryEditor/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/index.tsx
  test/models/ToolpadEditor.ts
Labels: core

#3091 [code-infra] Add monorepo update script
  package.json
  scripts/updateMonorepo.ts
Labels: core

#3092 [code-infra] Replace hardcoded repository in monorepo update script
  scripts/updateMonorepo.ts
Labels: core

#3094 [release] v0.1.46
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/create-toolpad-app/package.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
  packages/toolpad-utils/package.json
Labels: release 🚀

#3088 Remove types and useBoolean proxy modules
  packages/toolpad-app/src/appDom/index.ts
  packages/toolpad-app/src/components/MapEntriesEditor.tsx
  packages/toolpad-app/src/components/MuiThemeEditor.tsx
  packages/toolpad-app/src/server/EnvManager.ts
  packages/toolpad-app/src/server/FunctionsManager.ts
  packages/toolpad-app/src/server/localMode.ts
  packages/toolpad-app/src/toolpad/AppEditor/BindingEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/NoPageFound.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/BindableEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ConnectionSelect.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/JsExpressionEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ParametersEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/QueriesExplorer/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/UrlQueryEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PagesExplorer/index.tsx
  packages/toolpad-app/src/toolpad/AppOptions/index.tsx
  packages/toolpad-app/src/toolpad/Toolpad.tsx
  packages/toolpad-app/src/toolpad/ToolpadShell/Header/UserFeedback/index.tsx
  packages/toolpad-app/src/toolpadDataSources/googleSheets/server.ts
  packages/toolpad-app/src/toolpadDataSources/local/server.ts
  packages/toolpad-app/src/toolpadDataSources/mysql/server.ts
  packages/toolpad-app/src/toolpadDataSources/postgres/server.ts
  packages/toolpad-app/src/toolpadDataSources/rest/AuthenticationEditor.tsx
  packages/toolpad-app/src/toolpadDataSources/rest/BodyEditor.tsx
  packages/toolpad-app/src/toolpadDataSources/rest/client.tsx
  packages/toolpad-app/src/toolpadDataSources/rest/server.ts
  packages/toolpad-app/src/toolpadDataSources/rest/shared.ts
  packages/toolpad-app/src/toolpadDataSources/rest/types.ts
  packages/toolpad-app/src/toolpadDataSources/sql/client.tsx
  packages/toolpad-app/src/toolpadDataSources/sql/types.ts
  packages/toolpad-app/src/types.ts
  packages/toolpad-app/src/utils/express.ts
  packages/toolpad-app/src/utils/types.ts
  packages/toolpad-app/src/utils/useBoolean.ts
  packages/toolpad-utils/src/types.ts
Labels: core

#3099 Make toolpad-core and toopad-components ESM only
  packages/toolpad-app/src/server/FunctionsManager.ts
  packages/toolpad-app/src/server/functionsRuntime.ts
  packages/toolpad-app/src/server/toolpadAppBuilder.ts
  packages/toolpad-components/package.json
  packages/toolpad-components/tsup.config.ts
  packages/toolpad-core/package.json
  packages/toolpad-core/src/server.ts
  packages/toolpad-core/src/serverRuntime.ts
  packages/toolpad-core/tsup.config.ts
Labels: core

#3112 Adjust schedule for monorepo update
  renovate.json
Labels: core

#3101 Remove old package.json
  packages/toolpad-app/browser/package.json
  packages/toolpad-app/canvas/package.json
  packages/toolpad-app/runtime/package.json
  packages/toolpad-app/server/package.json
  packages/toolpad-app/tsup.config.ts
  packages/toolpad-core/browser/package.json
  packages/toolpad-core/server/package.json
Labels: core

#3069 In the readme.md replaced product demo video with gif
  README.md
Labels: enhancement

#3116 Move App dom to Toolpad core
  .eslintrc.js
  packages/toolpad-app/src/canvas/index.tsx
  packages/toolpad-app/src/runtime/AppThemeProvider.tsx
  packages/toolpad-app/src/runtime/CanvasHooksContext.tsx
  packages/toolpad-app/src/runtime/ToolpadApp.spec.tsx
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/runtime/createRuntimeState.tsx
  packages/toolpad-app/src/runtime/toolpadComponents/index.tsx
  packages/toolpad-app/src/runtime/types.ts
  packages/toolpad-app/src/runtime/useAuth.ts
  packages/toolpad-app/src/runtime/useDataQuery.ts
  packages/toolpad-app/src/server/DataManager.ts
  packages/toolpad-app/src/server/appServerWorker.ts
  packages/toolpad-app/src/server/auth.ts
  packages/toolpad-app/src/server/localMode.ts
  packages/toolpad-app/src/server/toolpadAppBuilder.ts
  packages/toolpad-app/src/toolpad/AppEditor/AppAuthorizationEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/BindingEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/ConnectionEditor/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/ElementContext.tsx
  packages/toolpad-app/src/toolpad/AppEditor/HierarchyExplorer/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/NodeMenu.tsx
  packages/toolpad-app/src/toolpad/AppEditor/NodeNameEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageDisplayNameEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentCatalog/ComponentCatalog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentPanel.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ConnectionSelect.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/NodeAttributeEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/PageEditorProvider.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/PageOptionsPanel.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/QueriesExplorer/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/QueryEditor/QueryEditorPanel.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/QueryEditor/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/NodeDropArea.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/NodeHud.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/RenderOverlay.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/RenderPanel.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ThemeEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/UrlQueryEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PagePanel.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageTitleEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PagesExplorer/CreateCodeComponentNodeDialog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PagesExplorer/CreatePageNodeDialog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PagesExplorer/index.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PagesExplorer/validation.ts
  packages/toolpad-app/src/toolpad/AppEditor/pageLayout.ts
  packages/toolpad-app/src/toolpad/AppOptions/index.tsx
  packages/toolpad-app/src/toolpad/AppState.tsx
  packages/toolpad-app/src/toolpad/propertyControls/ChartData.tsx
  packages/toolpad-app/src/toolpadDataSources/googleSheets/client.tsx
  packages/toolpad-app/src/toolpadDataSources/sql/client.tsx
  packages/toolpad-app/src/types.ts
  packages/toolpad-app/src/utils/domView.ts
  packages/toolpad-core/package.json
  packages/toolpad-core/src/appDom.ts
  packages/toolpad-utils/src/immutability.ts
  pnpm-lock.yaml
Labels: core

#3119 [docs] `;` causes query to fail
  docs/data/toolpad/getting-started/first-app.md
Labels: docs, bug 🐛

#3124 Add missing dependencies to the next.js example
  examples/custom-server-nextjs/package.json
Labels: examples

#3123 Run prettier on files after generating schema json
  docs/schemas/v1/definitions.json
  scripts/docs/generateJsonSchemas.ts
Labels: enhancement

#3126 Improve portability of ToolpadApp
  packages/toolpad-app/cli/index.ts
  packages/toolpad-app/package.json
  packages/toolpad-app/src/packageInfo.ts
  packages/toolpad-app/src/runtime/AppHostContext.tsx
  packages/toolpad-app/src/runtime/PreviewHeader.tsx
  packages/toolpad-app/src/runtime/ToolpadApp.spec.tsx
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/runtime/constants.ts
  packages/toolpad-app/src/runtime/index.tsx
  packages/toolpad-app/src/server/FunctionsManager.ts
  packages/toolpad-app/src/server/functionsRuntime.ts
  packages/toolpad-app/src/server/index.ts
  packages/toolpad-app/src/server/localMode.ts
  packages/toolpad-app/src/server/toolpadAppBuilder.ts
  packages/toolpad-core/src/jsBrowserRuntime.tsx
Labels: core

#3128 v0.1.47
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/create-toolpad-app/package.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
  packages/toolpad-utils/package.json
Labels: release 🚀

#3131 0.1.48
  CHANGELOG.md
  RELEASE.md
  docs/package.json
  lerna.json
  package.json
  packages/create-toolpad-app/package.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
  packages/toolpad-utils/package.json
Labels: release 🚀

#3132 Run pnpm dedupe
  pnpm-lock.yaml
Labels: dependencies

#3134 Update monorepo
  docs/package.json
  package.json
  pnpm-lock.yaml
Labels: chore 🧹

#3144 Run prettier
  docs/data/toolpad/reference/components/autocomplete.md
  docs/data/toolpad/reference/components/button.md
  docs/data/toolpad/reference/components/chart.md
  docs/data/toolpad/reference/components/checkbox.md
  docs/data/toolpad/reference/components/container.md
  docs/data/toolpad/reference/components/data-grid.md
  docs/data/toolpad/reference/components/date-picker.md
  docs/data/toolpad/reference/components/file-picker.md
  docs/data/toolpad/reference/components/form.md
  docs/data/toolpad/reference/components/image.md
  docs/data/toolpad/reference/components/list.md
  docs/data/toolpad/reference/components/paper.md
  docs/data/toolpad/reference/components/select.md
  docs/data/toolpad/reference/components/stack.md
  docs/data/toolpad/reference/components/tabs.md
  docs/data/toolpad/reference/components/text-field.md
  docs/data/toolpad/reference/components/text.md
  docs/src/components/landing/DemoVideo.js
  pnpm-lock.yaml
Labels: core

#3145 [core] Use non breaking spaces
  docs/data/toolpad/reference/components/autocomplete.md
  docs/data/toolpad/reference/components/button.md
  docs/data/toolpad/reference/components/chart.md
  docs/data/toolpad/reference/components/checkbox.md
  docs/data/toolpad/reference/components/container.md
  docs/data/toolpad/reference/components/data-grid.md
  docs/data/toolpad/reference/components/date-picker.md
  docs/data/toolpad/reference/components/file-picker.md
  docs/data/toolpad/reference/components/form.md
  docs/data/toolpad/reference/components/image.md
  docs/data/toolpad/reference/components/list.md
  docs/data/toolpad/reference/components/paper.md
  docs/data/toolpad/reference/components/select.md
  docs/data/toolpad/reference/components/stack.md
  docs/data/toolpad/reference/components/tabs.md
  docs/data/toolpad/reference/components/text-field.md
  docs/data/toolpad/reference/components/text.md
  package.json
  packages/toolpad-components/src/Button.tsx
  packages/toolpad-components/src/Container.tsx
  packages/toolpad-components/src/Paper.tsx
  packages/toolpad-components/src/Select.tsx
  packages/toolpad-components/src/Stack.tsx
  packages/toolpad-components/src/Tabs.tsx
  packages/toolpad-components/src/TextField.tsx
  packages/toolpad-components/src/constants.tsx
Labels: core

#3077 Add RBAC with Azure AD authentication provider
  docs/schemas/v1/definitions.json
  packages/toolpad-app/src/components/icons/AzureIcon.tsx
  packages/toolpad-app/src/runtime/AppLayout.tsx
  packages/toolpad-app/src/runtime/SignInPage.tsx
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/runtime/auth.tsx
  packages/toolpad-app/src/runtime/useAuth.ts
  packages/toolpad-app/src/server/auth.ts
  packages/toolpad-app/src/server/schema.ts
  packages/toolpad-app/src/toolpad/AppEditor/AppAuthorizationEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/PageOptionsPanel.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PagesExplorer/CreatePageNodeDialog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PagesExplorer/index.tsx
  packages/toolpad-app/typings/@auth.d.ts
  packages/toolpad-core/src/appDom.ts
Labels: new feature

#3146 Add stronger warning to the auto generated files to avoid hand-editing
  docs/data/toolpad/reference/components/autocomplete.md
  docs/data/toolpad/reference/components/button.md
  docs/data/toolpad/reference/components/chart.md
  docs/data/toolpad/reference/components/checkbox.md
  docs/data/toolpad/reference/components/container.md
  docs/data/toolpad/reference/components/data-grid.md
  docs/data/toolpad/reference/components/date-picker.md
  docs/data/toolpad/reference/components/file-picker.md
  docs/data/toolpad/reference/components/form.md
  docs/data/toolpad/reference/components/image.md
  docs/data/toolpad/reference/components/list.md
  docs/data/toolpad/reference/components/manifest.json
  docs/data/toolpad/reference/components/metric.md
  docs/data/toolpad/reference/components/page-column.md
  docs/data/toolpad/reference/components/page-row.md
  docs/data/toolpad/reference/components/paper.md
  docs/data/toolpad/reference/components/select.md
  docs/data/toolpad/reference/components/stack.md
  docs/data/toolpad/reference/components/tabs.md
  docs/data/toolpad/reference/components/text-field.md
  docs/data/toolpad/reference/components/text.md
  docs/pages/toolpad/reference/components/autocomplete.js
  docs/pages/toolpad/reference/components/button.js
  docs/pages/toolpad/reference/components/chart.js
  docs/pages/toolpad/reference/components/checkbox.js
  docs/pages/toolpad/reference/components/container.js
  docs/pages/toolpad/reference/components/data-grid.js
  docs/pages/toolpad/reference/components/date-picker.js
  docs/pages/toolpad/reference/components/file-picker.js
  docs/pages/toolpad/reference/components/form.js
  docs/pages/toolpad/reference/components/image.js
  docs/pages/toolpad/reference/components/index.js
  docs/pages/toolpad/reference/components/list.js
  docs/pages/toolpad/reference/components/metric.js
  docs/pages/toolpad/reference/components/page-column.js
  docs/pages/toolpad/reference/components/page-row.js
  docs/pages/toolpad/reference/components/paper.js
  docs/pages/toolpad/reference/components/select.js
  docs/pages/toolpad/reference/components/stack.js
  docs/pages/toolpad/reference/components/tabs.js
  docs/pages/toolpad/reference/components/text-field.js
  docs/pages/toolpad/reference/components/text.js
  scripts/docs/buildComponentsReference.ts
Labels: core
