Repository mui/toolpad, pull requests merged in 2024-03, with the labels that each got.

#3264 [DataGrid] fix errors not showing up in the rows area
  packages/toolpad-components/src/DataGrid.tsx
  test/visual/components/fixture/toolpad/pages/components/page.yml
Labels: core

#3265 [core] Fix infinite loop in inline canvas mode
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
Labels: core

#3275 Release v0.1.51
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/create-toolpad-app/package.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
  packages/toolpad-utils/package.json
Labels: release

#3278 [website] Add star count fallback
  docs/src/components/landing/GithubStars.js
Labels: website

#3282 [release] v0.1.52
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/create-toolpad-app/package.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-studio-components/package.json
  packages/toolpad-studio-runtime/package.json
  packages/toolpad-studio/package.json
  packages/toolpad-utils/package.json
Labels: release

#3287 Fix flaky auth test with console error "Failed to fetch"
  package.json
  packages/create-toolpad-app/tests/index.spec.ts
  packages/toolpad-studio/src/runtime/SignInPage.tsx
  packages/toolpad-studio/src/server/auth.ts
  pnpm-lock.yaml
  test/integration/auth/domain.spec.ts
  test/integration/auth/fixture-domain/toolpad/application.yml
  test/integration/auth/fixture-domain/toolpad/pages/mypage/page.yml
Labels: test

#3290 Fix flaky authentication test: Wait for network idle in tests again
  test/integration/auth/domain.spec.ts
Labels: test

#3293 [docs] Fix some Vale errors
  .circleci/config.yml
  .github/styles/Vocab/accept.txt
  .gitignore
  .vale.ini
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  docs/README.md
  docs/data/toolpad/studio/components/date-picker/date-picker.md
  docs/data/toolpad/studio/components/text-field/text-field.md
  docs/data/toolpad/studio/concepts/page-properties.md
  docs/data/toolpad/studio/getting-started/support.md
  docs/data/toolpad/studio/getting-started/why-toolpad.md
  docs/data/toolpad/studio/how-to-guides/delete-grid-row.md
  docs/data/toolpad/studio/how-to-guides/editor-path.md
  docs/data/toolpad/studio/landing/features.js
  docs/data/toolpad/studio/landing/pricing.js
  docs/data/toolpad/studio/reference/components/autocomplete.md
  docs/data/toolpad/studio/reference/components/button.md
  docs/data/toolpad/studio/reference/components/data-grid.md
  docs/data/toolpad/studio/reference/components/date-picker.md
  docs/data/toolpad/studio/reference/components/file-picker.md
  docs/data/toolpad/studio/reference/components/select.md
  docs/data/toolpad/studio/reference/components/tabs.md
  docs/data/toolpad/studio/reference/components/text-field.md
  docs/data/toolpad/studio/reference/components/text.md
  docs/pages/toolpad/index.js
  docs/src/components/landing/Hero.js
  examples/npm-stats/README.md
  packages/create-toolpad-app/README.md
  packages/create-toolpad-app/src/packageType.ts
  packages/toolpad-studio-components/src/Autocomplete.tsx
  packages/toolpad-studio-components/src/Button.tsx
  packages/toolpad-studio-components/src/DataGrid.tsx
  packages/toolpad-studio-components/src/DatePicker.tsx
  packages/toolpad-studio-components/src/FilePicker.tsx
  packages/toolpad-studio-components/src/Select.tsx
  packages/toolpad-studio-components/src/Tabs.tsx
  packages/toolpad-studio-components/src/Text.tsx
  packages/toolpad-studio-components/src/TextField.tsx
  packages/toolpad-studio/NOTES.md
  packages/toolpad-studio/src/toolpad/AppEditor/PageEditor/ComponentPanel.tsx
  packages/toolpad-studio/src/types.ts
Labels: docs

#3299 [docs] Link blog post from examples overview page and some minor edits.
  docs/data/toolpad/studio/concepts/data-providers.md
  docs/data/toolpad/studio/getting-started/examples-overview.md
  docs/data/toolpad/studio/getting-started/why-toolpad.md
  docs/public/static/toolpad/marketing/hackernews-client.png
  examples/graphql/toolpad/application.yml
  examples/graphql/toolpad/pages/page/page.yml
  examples/hacker-news-client/README.md
  examples/hacker-news-client/package.json
Labels: docs

#3302 [core] Lower the frequency of no-response action runs
  .github/workflows/no-response.yml
Labels: core

#3306 [docs] Fix support link
  docs/data/toolpad/studio/getting-started/support.md
Labels: docs, bug 🐛

#3312 Remove lerna isolation
  renovate.json
Labels: dependencies

#3313 Remove deprecated dependencies
  package.json
  packages/toolpad-studio/package.json
  packages/toolpad-utils/package.json
  pnpm-lock.yaml
Labels: scope: code-infra

#3314 v0.1.53
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/create-toolpad-app/package.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-core/package.json
  packages/toolpad-studio-components/package.json
  packages/toolpad-studio-runtime/package.json
  packages/toolpad-studio/package.json
  packages/toolpad-utils/package.json
  test/package.json
Labels: release

#3323 Fix typo : use npm instead of pnpm in instruction
  docs/data/toolpad/studio/getting-started/installation.md
Labels: docs

#3324 Update Node.js in circleci
  .circleci/config.yml
Labels: scope: code-infra

#3326 Remove fallback modules
  docs/data/toolpad/studio/concepts/custom-components.md
  packages/toolpad-studio/src/server/localMode.ts
  packages/toolpad-studio/src/server/toolpadAppBuilder.ts
Labels: core

#3308 Allow OPTIONS method in HTTP queries
  packages/toolpad-studio/src/toolpadDataSources/rest/client.tsx
Labels: enhancement

#3327 Fix crash when components folder contains a tsconfig
  packages/toolpad-studio/src/server/localMode.ts
  test/integration/codeComponents/fixture/toolpad/components/tsconfig.json
Labels: core

#3304 [cli] Introduce `--core`
  packages/create-toolpad-app/public/gitignoreTemplate
  packages/create-toolpad-app/src/generateProject.ts
  packages/create-toolpad-app/src/index.ts
  packages/create-toolpad-app/src/writeFiles.ts
Labels: create-toolpad-app

#3330 Fix dedupe check
  .circleci/config.yml
Labels: scope: code-infra

#3329 Add custom component example
  examples/custom-component/.gitignore
  examples/custom-component/README.md
  examples/custom-component/application.yml
  examples/custom-component/components/Clock.tsx
  examples/custom-component/package.json
  examples/custom-component/pages/page/page.yml
Labels: examples

#3340 Upgrade vite
  packages/toolpad-studio/package.json
  packages/toolpad-studio/src/server/toolpadAppBuilder.ts
  pnpm-lock.yaml
Labels: dependencies

#3336 Add rename, duplicate and delete for Page Hierarchy
  packages/toolpad-studio/src/toolpad/AppEditor/HierarchyExplorer/index.tsx
  packages/toolpad-studio/src/toolpad/AppEditor/NodeMenu.tsx
Labels: core

#3341 Fix screenshot flakeyness
  test/integration/rest-basic/index.spec.ts
Labels: test
