Repository mui/toolpad, pull requests merged in 2024-04, with the labels that each got.

#3337 Move TreeView icons into the theme
  packages/toolpad-studio/src/theme.ts
  packages/toolpad-studio/src/toolpad/AppEditor/HierarchyExplorer/index.tsx
  packages/toolpad-studio/src/toolpad/AppEditor/PageEditor/QueriesExplorer/index.tsx
  packages/toolpad-studio/src/toolpad/AppEditor/PagesExplorer/index.tsx
  packages/toolpad-studio/src/toolpad/FunctionsEditor/index.tsx
Labels: enhancement

#3356 [docs] remove redirect to component reference
  docs/data/toolpad/studio/getting-started/why-toolpad.md
Labels: docs

#3354 [docs] Update delete-grid-row.md
  docs/data/toolpad/studio/how-to-guides/delete-grid-row.md
Labels: docs

#3353 Add RFC to readme
  README.md
Labels: docs

#3374 [queries] Remove locally hosted demo data
  packages/toolpad-studio/src/toolpadDataSources/rest/client.tsx
  packages/toolpad-studio/src/toolpadDataSources/rest/server.ts
  packages/toolpad-studio/src/toolpadDataSources/rest/shared.ts
  public/employees.json
  public/movies.json
Labels: feature: Queries

#3358 [ui] Add a chip to indicate pro features
  docs/data/toolpad/studio/concepts/authentication.md
  docs/data/toolpad/studio/concepts/rbac.md
  packages/toolpad-studio/public/pro.svg
  packages/toolpad-studio/src/components/HelpTooltipIcon.tsx
  packages/toolpad-studio/src/toolpad/AppEditor/AppAuthorizationEditor.tsx
  packages/toolpad-studio/src/toolpad/AppEditor/PageEditor/PageOptionsPanel.tsx
  packages/toolpad-studio/src/toolpad/AppEditor/UpgradeAlert.tsx
  packages/toolpad-studio/src/toolpad/AppEditor/UpgradeNotification.tsx
Labels: design: ui

#3377 [docs] Improve the writing on the "why Toolpad" doc
  docs/data/toolpad/studio/getting-started/why-toolpad.md
Labels: docs

#3382 [code-infra] Fix prettier in scripts
  docs/schemas/v1/definitions.json
  package.json
  pnpm-lock.yaml
  scripts/docs/buildComponentsReference.ts
  scripts/docs/generateJsonSchemas.ts
  scripts/docs/utils.ts
  scripts/tsconfig.json
Labels: scope: code-infra

#3301 [code-infra] Use @mui/docs from npm
  docs/next.config.mjs
  docs/package.json
  eslintWebpackResolverConfig.js
  pnpm-lock.yaml
Labels: scope: code-infra

#3206 [core] Move Monaco setup outside of the library
  .circleci/config.yml
  packages/toolpad-studio/src/components/MonacoEditor.tsx
  packages/toolpad-studio/src/server/toolpadAppBuilder.ts
  packages/toolpad-studio/tsup.config.ts
Labels: test

#3386 [release] v0.1.54
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/create-toolpad-app/package.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-core/package.json
  packages/toolpad-studio-components/package.json
  packages/toolpad-studio-runtime/package.json
  packages/toolpad-studio/package.json
  packages/toolpad-utils/package.json
  test/package.json
Labels: release

#3388 fix: Duplicate entry in `CHANGELOG.md`
  CHANGELOG.md
Labels: docs

#3376 Remove unsupported engines section from renovate
  renovate.json
Labels: dependencies, scope: code-infra

#3399 [core] Remove engine please-use-pnpm
  package.json
Labels: core

#3400 [docs] Remove more traces of yarn
  CONTRIBUTING.md
  docs/data/toolpad/core/introduction/overview.md
  docs/data/toolpad/studio/concepts/deployment.md
  docs/data/toolpad/studio/getting-started/installation.md
  docs/next.config.mjs
  render.yaml
Labels: docs

#3402 [docs] Fix trailing slashes on server render
  docs/next.config.mjs
Labels: docs

#3387 [docs] Add guide on deployment to Google cloud
  docs/data/toolpad/studio/how-to-guides/gcp-deploy.md
  docs/data/toolpad/studio/pages.ts
  docs/pages/toolpad/studio/how-to-guides/gcp-deploy.js
  docs/public/static/toolpad/docs/studio/deploy-gcp/back-to-cloud-run.png
  docs/public/static/toolpad/docs/studio/deploy-gcp/build-complete.png
  docs/public/static/toolpad/docs/studio/deploy-gcp/build-logs.png
  docs/public/static/toolpad/docs/studio/deploy-gcp/build-type.png
  docs/public/static/toolpad/docs/studio/deploy-gcp/choose-project.png
  docs/public/static/toolpad/docs/studio/deploy-gcp/choose-repository.png
  docs/public/static/toolpad/docs/studio/deploy-gcp/create-service.png
  docs/public/static/toolpad/docs/studio/deploy-gcp/deployment.png
  docs/public/static/toolpad/docs/studio/deploy-gcp/navigate-to-cloud-run.png
  docs/public/static/toolpad/docs/studio/deploy-gcp/pitfall.png
  docs/public/static/toolpad/docs/studio/deploy-gcp/set-container-port.png
  docs/public/static/toolpad/docs/studio/deploy-gcp/setup-run-service.png
Labels: docs

#3412 Use url.pathToFileURL to correctly resolve functions paths on windows
  packages/toolpad-studio/src/server/functionsRuntime.ts
Labels: bug 🐛

#3411 [docs] Fix some of the double redirections
  docs/public/_redirects
Labels: docs

#3409 [docs] Fix broken paths, meta for ahrefs
  docs/data/toolpad/studio/concepts/queries.md
  docs/data/toolpad/studio/how-to-guides/render-deploy.md
  docs/public/static/toolpad/docs/studio/how-to-guides/deploy-render/node-version.png
  docs/public/static/toolpad/docs/studio/how-to-guides/deploy-render/render-complete.png
  docs/public/static/toolpad/docs/studio/how-to-guides/deploy-render/render-config-commands.png
  docs/public/static/toolpad/docs/studio/how-to-guides/deploy-render/render-config-start.png
  docs/public/static/toolpad/docs/studio/how-to-guides/deploy-render/render-connect-github.png
  docs/public/static/toolpad/docs/studio/how-to-guides/deploy-render/render-github-new.png
  docs/public/static/toolpad/docs/studio/how-to-guides/deploy-render/render-search.png
  docs/public/static/toolpad/docs/studio/how-to-guides/deploy-render/render-start.png
Labels: docs, bug 🐛

#3415 [docs] Remove double redirections
  docs/public/_redirects
Labels: scope: docs-infra

#3413 Fix environment binding preview
  packages/toolpad-studio/src/server/EnvManager.ts
  packages/toolpad-studio/src/toolpad/AppEditor/BindingEditor.tsx
  packages/toolpad-studio/src/toolpad/AppEditor/PageEditor/BindableEditor.tsx
  packages/toolpad-studio/src/toolpad/AppEditor/PageEditor/ParametersEditor.tsx
  packages/toolpad-studio/src/toolpadDataSources/rest/client.tsx
  packages/toolpad-studio/src/toolpadDataSources/rest/server.ts
  packages/toolpad-studio/src/toolpadDataSources/rest/types.ts
Labels: core

#3381 [docs] Add a guide on how to deploy on railway
  docs/data/toolpad/studio/how-to-guides/gcp-deploy.md
  docs/data/toolpad/studio/how-to-guides/railway-deploy.md
  docs/data/toolpad/studio/how-to-guides/render-deploy.md
  docs/data/toolpad/studio/pages.ts
  docs/pages/toolpad/studio/how-to-guides/railway-deploy.js
  docs/public/static/toolpad/docs/studio/how-to-guides/deploy-gcp/back-to-cloud-run.png
  docs/public/static/toolpad/docs/studio/how-to-guides/deploy-gcp/build-complete.png
  docs/public/static/toolpad/docs/studio/how-to-guides/deploy-gcp/build-logs.png
  docs/public/static/toolpad/docs/studio/how-to-guides/deploy-gcp/build-type.png
  docs/public/static/toolpad/docs/studio/how-to-guides/deploy-gcp/choose-project.png
  docs/public/static/toolpad/docs/studio/how-to-guides/deploy-gcp/choose-repository.png
  docs/public/static/toolpad/docs/studio/how-to-guides/deploy-gcp/create-service.png
  docs/public/static/toolpad/docs/studio/how-to-guides/deploy-gcp/deployment.png
  docs/public/static/toolpad/docs/studio/how-to-guides/deploy-gcp/navigate-to-cloud-run.png
  docs/public/static/toolpad/docs/studio/how-to-guides/deploy-gcp/pitfall.png
  docs/public/static/toolpad/docs/studio/how-to-guides/deploy-gcp/set-container-port.png
  docs/public/static/toolpad/docs/studio/how-to-guides/deploy-gcp/setup-run-service.png
  docs/public/static/toolpad/docs/studio/how-to-guides/deploy-railway/add-port-as-a-variable.png
  docs/public/static/toolpad/docs/studio/how-to-guides/deploy-railway/add-variable.png
  docs/public/static/toolpad/docs/studio/how-to-guides/deploy-railway/choose-repository.png
  docs/public/static/toolpad/docs/studio/how-to-guides/deploy-railway/deploy.png
  docs/public/static/toolpad/docs/studio/how-to-guides/deploy-railway/generate-domain.png
  docs/public/static/toolpad/docs/studio/how-to-guides/deploy-railway/railway-create-new-project.png
  docs/public/static/toolpad/docs/studio/how-to-guides/deploy-railway/setting-root-directory.png
Labels: docs

#3425 [core] Use the root dependency
  docs/package.json
  pnpm-lock.yaml
Labels: core

#3426 [core] Add notes to help future blame
  docs/next.config.mjs
Labels: core

#3417 Fix issues from trying MUI ESM branch
  docs/package.json
  packages/toolpad-studio/package.json
  packages/toolpad-studio/scripts/tsconfig.json
  packages/toolpad-studio/scripts/typings.mts
  packages/toolpad-studio/scripts/waitForApp.mts
  packages/toolpad-studio/scripts/waitForDb.mts
  packages/toolpad-studio/src/toolpadDataSources/local/client.tsx
  pnpm-lock.yaml
Labels: core

#3440 Revert using published @mui/docs
  docs/next.config.mjs
  eslintWebpackResolverConfig.js
Labels: scope: code-infra

#3444 [docs] Add documentation on how to create controlled properties
  docs/data/toolpad/studio/concepts/custom-components.md
  docs/public/static/toolpad/docs/studio/concepts/custom-components/controlled-prop.mp4
  packages/toolpad-studio/src/toolpad/AppEditor/ExplorerHeader.tsx
  packages/toolpad-studio/src/toolpad/AppEditor/PagePanel.tsx
Labels: docs

#3445 Fix default value not initializing for controlled properties
  packages/toolpad-studio/src/runtime/ToolpadApp.tsx
  packages/toolpad-studio/src/runtime/evalJsBindings.ts
  test/integration/codeComponents/fixture/toolpad/application.yml
  test/integration/codeComponents/fixture/toolpad/components/MyTextField.tsx
  test/integration/codeComponents/fixture/toolpad/pages/page/page.yml
  test/integration/codeComponents/fixture/toolpad/pages/page1/page.yml
  test/integration/codeComponents/index.spec.ts
Labels: core

#3451 [docs] Remove MarkdownElement import
  docs/src/components/landing/CodeBlock.js
Labels: docs

#3448 Link/Update docs in Studio
  docs/data/toolpad/studio/reference/components/autocomplete.md
  docs/data/toolpad/studio/reference/components/button.md
  docs/data/toolpad/studio/reference/components/chart.md
  docs/data/toolpad/studio/reference/components/checkbox.md
  docs/data/toolpad/studio/reference/components/container.md
  docs/data/toolpad/studio/reference/components/data-grid.md
  docs/data/toolpad/studio/reference/components/date-picker.md
  docs/data/toolpad/studio/reference/components/file-picker.md
  docs/data/toolpad/studio/reference/components/form.md
  docs/data/toolpad/studio/reference/components/image.md
  docs/data/toolpad/studio/reference/components/list.md
  docs/data/toolpad/studio/reference/components/paper.md
  docs/data/toolpad/studio/reference/components/select.md
  docs/data/toolpad/studio/reference/components/spacer.md
  docs/data/toolpad/studio/reference/components/stack.md
  docs/data/toolpad/studio/reference/components/text-field.md
  docs/data/toolpad/studio/reference/components/text.md
  packages/toolpad-studio-components/src/Button.tsx
  packages/toolpad-studio-components/src/DataGrid.tsx
  packages/toolpad-studio-components/src/DatePicker.tsx
  packages/toolpad-studio-components/src/List.tsx
  packages/toolpad-studio-components/src/TextField.tsx
  packages/toolpad-studio-components/src/constants.tsx
  packages/toolpad-studio/src/components/HelpTooltipIcon.tsx
  packages/toolpad-studio/src/toolpad/AppEditor/BindingEditor.tsx
  packages/toolpad-studio/src/toolpad/AppEditor/PageEditor/QueriesExplorer/index.tsx
  packages/toolpad-studio/src/toolpadDataSources/local/client.tsx
  packages/toolpad-studio/src/toolpadDataSources/rest/client.tsx
Labels: docs

#3441 [code-infra] Closer sync with eslint config of codebase
  .eslintrc.js
  docs/data/toolpad/studio/components/button/ButtonBasic.js
  docs/data/toolpad/studio/components/button/ButtonColor.js
  docs/data/toolpad/studio/components/button/ButtonSize.js
  docs/data/toolpad/studio/components/button/ButtonState.js
  docs/data/toolpad/studio/components/button/ButtonVariant.js
  docs/data/toolpad/studio/components/data-grid/DataGridBasic.js
  docs/data/toolpad/studio/components/data-grid/DataGridHideToolbar.js
  docs/data/toolpad/studio/components/data-grid/DataGridPro.js
  docs/data/toolpad/studio/components/data-grid/DataGridStandard.js
  docs/data/toolpad/studio/components/data-grid/data-grid.md
  docs/data/toolpad/studio/components/date-picker/DatePickerBasic.js
  docs/data/toolpad/studio/components/date-picker/DatePickerDisabled.js
  docs/data/toolpad/studio/components/date-picker/DatePickerFormat.js
  docs/data/toolpad/studio/components/date-picker/DatePickerSize.js
  docs/data/toolpad/studio/components/date-picker/DatePickerVariant.js
  docs/data/toolpad/studio/components/date-picker/date-picker.md
  docs/data/toolpad/studio/components/list/List.js
  docs/data/toolpad/studio/components/text-field/TextFieldBasic.js
  docs/data/toolpad/studio/components/text-field/TextFieldDisabled.js
  docs/data/toolpad/studio/components/text-field/TextFieldSize.js
  docs/data/toolpad/studio/components/text-field/TextFieldVariant.js
  docs/data/toolpad/studio/components/text-field/text-field.md
Labels: scope: code-infra

#3454 [docs] Make sure we install the latest version of Toolpad Studio
  docs/data/toolpad/studio/getting-started/first-app.md
Labels: docs, bug 🐛

#3460 Remove dead code
  packages/toolpad-studio/src/toolpad/AppEditor/ConnectionEditor/index.tsx
Labels: core

#3463 Update README files
  README.md
  packages/toolpad-studio/README.md
Labels: docs

#3424 [core] Update monorepo
  docs/next.config.mjs
Labels: dependencies

#3483 [core] Remove react pages experiment
  docs/schemas/v1/definitions.json
  examples/react-pages/README.md
  examples/react-pages/data.json
  examples/react-pages/toolpad/.gitignore
  examples/react-pages/toolpad/pages/foo/page.tsx
  examples/react-pages/toolpad/pages/foo/page.yml
  examples/react-pages/toolpad/resources/functions.ts
  packages/toolpad-studio-runtime/src/appDom.ts
  packages/toolpad-studio/src/entrypoint.tsx
  packages/toolpad-studio/src/runtime/ToolpadApp.tsx
  packages/toolpad-studio/src/runtime/globalState.ts
  packages/toolpad-studio/src/runtime/index.tsx
  packages/toolpad-studio/src/server/localMode.ts
  packages/toolpad-studio/src/server/schema.ts
  packages/toolpad-studio/src/server/toolpadAppBuilder.ts
  packages/toolpad-studio/src/toolpad/AppEditor/PageEditor/PageOptionsPanel.tsx
  packages/toolpad-studio/src/toolpad/AppEditor/PageEditor/RenderPanel/RenderPanel.tsx
  packages/toolpad-studio/src/toolpad/AppEditor/PageEditor/index.tsx
  packages/toolpad-studio/src/toolpad/AppEditor/PagePanel.tsx
Labels: core

#3482 Work on decoupling studio server constituents
  packages/toolpad-studio/src/constants.ts
  packages/toolpad-studio/src/server/DataManager.ts
  packages/toolpad-studio/src/server/EnvManager.ts
  packages/toolpad-studio/src/server/FunctionsManager.ts
  packages/toolpad-studio/src/server/appServerWorker.ts
  packages/toolpad-studio/src/server/index.ts
  packages/toolpad-studio/src/server/localMode.ts
  packages/toolpad-studio/src/server/projectRpcServer.ts
  packages/toolpad-studio/src/server/toolpadAppBuilder.ts
  packages/toolpad-studio/src/server/toolpadAppServer.ts
  packages/toolpad-studio/src/toolpad/AppEditor/PageEditor/QueryEditor/QueryEditorPanel.tsx
  packages/toolpad-studio/src/toolpadDataSources/googleSheets/server.ts
  packages/toolpad-studio/src/toolpadDataSources/server.ts
  packages/toolpad-studio/src/types.ts
Labels: core
