Repository mui/toolpad, pull requests merged in 2024-09, with the labels that each got.

#4035 [website] Fix Calendly link for Toolpad Studio demo
  docs/src/route.ts
  packages/toolpad-studio/src/constants.ts
Labels: website

#3982 [docs] Add `next-auth` v4 example
  CONTRIBUTING.md
  docs/data/toolpad/core/components/sign-in-page/sign-in-page.md
  examples/core-auth-nextjs-pages-nextauth-4/.eslintrc.json
  examples/core-auth-nextjs-pages-nextauth-4/README.md
  examples/core-auth-nextjs-pages-nextauth-4/next-env.d.ts
  examples/core-auth-nextjs-pages-nextauth-4/next.config.mjs
  examples/core-auth-nextjs-pages-nextauth-4/package.json
  examples/core-auth-nextjs-pages-nextauth-4/src/pages/_app.tsx
  examples/core-auth-nextjs-pages-nextauth-4/src/pages/_document.tsx
  examples/core-auth-nextjs-pages-nextauth-4/src/pages/api/auth/[...nextauth].ts
  examples/core-auth-nextjs-pages-nextauth-4/src/pages/auth/signin.tsx
  examples/core-auth-nextjs-pages-nextauth-4/src/pages/index.tsx
  examples/core-auth-nextjs-pages-nextauth-4/src/pages/orders/index.tsx
  examples/core-auth-nextjs-pages-nextauth-4/tsconfig.json
  pnpm-lock.yaml
Labels: docs, examples

#4041 [docs] Remove the list of upcoming features
  docs/data/toolpad/core/introduction/overview.md
Labels: docs

#4013 [docs] Link docs from component demos on Toolpad Core landing page
  docs/src/components/landing/ToolpadFeaturesSwitcher.tsx
Labels: website

#4059 Revert "Bump Tanstack to 5.55.0"
  packages/toolpad-studio-components/package.json
  packages/toolpad-studio-runtime/package.json
  packages/toolpad-studio/package.json
  pnpm-lock.yaml
Labels: dependencies

#4075 [docs-infra] Strengthen CSP
  docs/public/_headers
Labels: security, scope: docs-infra

#4077 [code-infra] Replace issue cleanup workflow with centralized one
  .github/workflows/issue-cleanup.yml
  .github/workflows/new-issue-triage.yml
Labels: enhancement, scope: infra

#4040 [cli] Clean templates, fix a bunch of issues in generated apps
  examples/core-auth-nextjs-pages-nextauth-4/src/pages/index.tsx
  examples/core-auth-nextjs-pages-nextauth-4/src/pages/orders/index.tsx
  examples/core-auth-nextjs-pages/src/auth.ts
  examples/core-auth-nextjs-pages/src/pages/_app.tsx
  examples/core-auth-nextjs-pages/src/pages/index.tsx
  examples/core-auth-nextjs-pages/src/theme.ts
  examples/core-auth-nextjs/src/app/(dashboard)/orders/page.tsx
  examples/core-auth-nextjs/src/app/(dashboard)/page.tsx
  examples/core-auth-nextjs/src/app/layout.tsx
  examples/core-auth-nextjs/src/app/public/page.tsx
  examples/core-auth-nextjs/src/auth.ts
  examples/core-auth-nextjs/src/theme.ts
  packages/create-toolpad-app/src/generateProject.ts
  packages/create-toolpad-app/src/generateStudioProject.ts
  packages/create-toolpad-app/src/index.ts
  packages/create-toolpad-app/src/templates/auth/auth.ts
  packages/create-toolpad-app/src/templates/auth/envLocal.ts
  packages/create-toolpad-app/src/templates/auth/nextjs-app/dashboardPage.ts
  packages/create-toolpad-app/src/templates/auth/nextjs-app/packageJson.ts
  packages/create-toolpad-app/src/templates/auth/nextjs-app/signInPage.ts
  packages/create-toolpad-app/src/templates/auth/nextjs-pages/app.ts
  packages/create-toolpad-app/src/templates/auth/nextjs-pages/packageJson.ts
  packages/create-toolpad-app/src/templates/auth/nextjs-pages/signIn.ts
  packages/create-toolpad-app/src/templates/auth/route.ts
  packages/create-toolpad-app/src/templates/dashboardPage.ts
  packages/create-toolpad-app/src/templates/indexPage.ts
  packages/create-toolpad-app/src/templates/nextjs-app/dashboardLayout.ts
  packages/create-toolpad-app/src/templates/nextjs-app/navigateButton.ts
  packages/create-toolpad-app/src/templates/nextjs-app/rootLayout.ts
  packages/create-toolpad-app/src/templates/nextjs-pages/app.ts
  packages/create-toolpad-app/src/templates/nextjs-pages/indexPage.ts
  packages/create-toolpad-app/src/templates/nextjs-pages/packageJson.ts
  packages/create-toolpad-app/src/templates/packageJson.ts
  packages/create-toolpad-app/src/templates/rootLayout.ts
  packages/create-toolpad-app/src/templates/rootPage.ts
  packages/create-toolpad-app/src/templates/studio/packageJson.ts
  packages/create-toolpad-app/src/types.ts
  packages/toolpad-core/src/SignInPage/SignInPage.tsx
  playground/nextjs-pages/src/auth.ts
  playground/nextjs-pages/src/pages/_app.tsx
  playground/nextjs-pages/src/pages/index.tsx
  playground/nextjs-pages/src/pages/orders/index.tsx
  playground/nextjs/src/app/(dashboard)/orders/page.tsx
  playground/nextjs/src/app/(dashboard)/page.tsx
  playground/nextjs/src/app/public/page.tsx
  playground/nextjs/src/auth.ts
Labels: create-toolpad-app

#3992 [core] Refactor `<Account />`
  docs/data/toolpad/core/components/account/AccountCustom.js
  docs/data/toolpad/core/components/account/AccountCustom.tsx
  docs/data/toolpad/core/components/account/AccountCustom.tsx.preview
  docs/data/toolpad/core/components/account/AccountSlots.js
  docs/data/toolpad/core/components/account/AccountSlots.tsx
  docs/data/toolpad/core/components/account/AccountSlots.tsx.preview
  docs/data/toolpad/core/components/account/CustomMenu.js
  docs/data/toolpad/core/components/account/CustomMenu.tsx
  docs/data/toolpad/core/components/account/account.md
  docs/pages/toolpad/core/api/account.json
  docs/pages/toolpad/core/api/dashboard-layout.json
  docs/translations/api-docs/account/account.json
  packages/toolpad-core/src/Account/Account.tsx
  packages/toolpad-core/src/Account/SessionAvatar.tsx
  packages/toolpad-core/src/DashboardLayout/DashboardLayout.tsx
  packages/toolpad-core/src/shared/locales/en.tsx
Labels: enhancement

#3933 [core] Add more OAuth providers to `SignInPage`
  codecov.yml
  docs/data/toolpad/core/components/sign-in-page/OAuthSignInPage.js
  docs/data/toolpad/core/components/sign-in-page/OAuthSignInPage.tsx
  docs/data/toolpad/core/components/sign-in-page/OAuthSignInPage.tsx.preview
  docs/data/toolpad/core/components/sign-in-page/sign-in-page.md
  docs/pages/toolpad/core/api/sign-in-page.json
  examples/core-auth-nextjs-pages-nextauth-4/src/pages/_app.tsx
  examples/core-auth-nextjs-pages/src/pages/_app.tsx
  examples/core-auth-nextjs/src/app/layout.tsx
  packages/create-toolpad-app/package.json
  packages/create-toolpad-app/src/index.ts
  packages/create-toolpad-app/src/templates/auth/auth.ts
  packages/create-toolpad-app/src/templates/auth/envLocal.ts
  packages/create-toolpad-app/src/templates/auth/utils.ts
  packages/create-toolpad-app/src/types.ts
  packages/toolpad-core/package.json
  packages/toolpad-core/src/SignInPage/SignInPage.tsx
  packages/toolpad-core/src/SignInPage/icons/Auth0.tsx
  packages/toolpad-core/src/SignInPage/icons/Cognito.tsx
  packages/toolpad-core/src/SignInPage/icons/Discord.tsx
  packages/toolpad-core/src/SignInPage/icons/Facebook.tsx
  packages/toolpad-core/src/SignInPage/icons/FusionAuth.tsx
  packages/toolpad-core/src/SignInPage/icons/GitLab.tsx
  packages/toolpad-core/src/SignInPage/icons/Google.tsx
  packages/toolpad-core/src/SignInPage/icons/Instagram.tsx
  packages/toolpad-core/src/SignInPage/icons/Keycloak.tsx
  packages/toolpad-core/src/SignInPage/icons/Line.tsx
  packages/toolpad-core/src/SignInPage/icons/LinkedIn.tsx
  packages/toolpad-core/src/SignInPage/icons/MicrosoftEntra.tsx
  packages/toolpad-core/src/SignInPage/icons/Okta.tsx
  packages/toolpad-core/src/SignInPage/icons/Slack.tsx
  packages/toolpad-core/src/SignInPage/icons/Spotify.tsx
  packages/toolpad-core/src/SignInPage/icons/TikTok.tsx
  packages/toolpad-core/src/SignInPage/icons/Twitch.tsx
  packages/toolpad-core/src/SignInPage/icons/Twitter.tsx
  packages/toolpad-utils/src/strings.spec.ts
  packages/toolpad-utils/src/strings.ts
  playground/nextjs/src/app/layout.tsx
  pnpm-lock.yaml
Labels: enhancement

#4083 Adjust DashboardLayout documentation to link to AppProvider more clearly
  docs/data/toolpad/core/components/app-provider/app-provider.md
  docs/data/toolpad/core/components/dashboard-layout/DashboardLayoutSlots.js
  docs/data/toolpad/core/components/dashboard-layout/DashboardLayoutSlots.tsx
  docs/data/toolpad/core/components/dashboard-layout/DashboardLayoutSlots.tsx.preview
  docs/data/toolpad/core/components/dashboard-layout/dashboard-layout.md
  docs/next-env.d.ts
Labels: docs

#4017 [core] Add mini drawer variant to DashboardLayout
  docs/data/toolpad/core/components/dashboard-layout/DashboardLayoutNoMiniSidebar.js
  docs/data/toolpad/core/components/dashboard-layout/DashboardLayoutNoMiniSidebar.tsx
  docs/data/toolpad/core/components/dashboard-layout/DashboardLayoutNoMiniSidebar.tsx.preview
  docs/data/toolpad/core/components/dashboard-layout/dashboard-layout.md
  docs/pages/toolpad/core/api/dashboard-layout.json
  docs/translations/api-docs/dashboard-layout/dashboard-layout.json
  packages/toolpad-core/src/DashboardLayout/DashboardLayout.tsx
  packages/toolpad-core/src/DashboardLayout/ThemeSwitcher.tsx
  playground/nextjs/next-env.d.ts
Labels: feature: Components

#4086 v0.6.0
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/create-toolpad-app/package.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-core/package.json
  packages/toolpad-studio-components/package.json
  packages/toolpad-studio-runtime/package.json
  packages/toolpad-studio/package.json
  packages/toolpad-utils/package.json
  playground/nextjs-pages/package.json
  playground/nextjs/package.json
  test/package.json
Labels: release

#4038 [code-infra] Bring CI to node 20
  .circleci/config.yml
  .codesandbox/ci.json
  examples/with-prisma-data-provider/package.json
  examples/with-prisma/package.json
  netlify.toml
  package.json
  packages/create-toolpad-app/package.json
  packages/toolpad-studio/package.json
  playground/nextjs/package.json
  pnpm-lock.yaml
  renovate.json
Labels: scope: code-infra

#4105 [docs] Fix typo from feedback
  docs/data/toolpad/studio/concepts/data-providers.md
Labels: docs

#4114 [PageContainer] Make PageContainer customizable for dynamic routes
  docs/data/toolpad/core/components/page-container/CustomPageContainer.js
  docs/data/toolpad/core/components/page-container/CustomPageContainer.tsx
  docs/data/toolpad/core/components/page-container/CustomPageContainer.tsx.preview
  docs/data/toolpad/core/components/page-container/TitleBreadcrumbsPageContainer.js
  docs/data/toolpad/core/components/page-container/TitleBreadcrumbsPageContainer.tsx
  docs/data/toolpad/core/components/page-container/page-container.md
  docs/pages/toolpad/core/api/app-provider.json
  docs/pages/toolpad/core/api/page-container.json
  docs/translations/api-docs/page-container/page-container.json
  package.json
  packages/toolpad-core/src/AppProvider/AppProvider.tsx
  packages/toolpad-core/src/PageContainer/PageContainer.test.tsx
  packages/toolpad-core/src/PageContainer/PageContainer.tsx
  packages/toolpad-core/src/index.ts
  packages/toolpad-core/src/internals/demo.tsx
  packages/toolpad-core/src/shared/navigation.tsx
  packages/toolpad-core/src/useActivePage/index.ts
  packages/toolpad-core/src/useActivePage/useActivePage.ts
  pnpm-lock.yaml
Labels: new feature

#4126 [code-infra] Update path-to-regexp to 6.3.0
  packages/toolpad-core/package.json
  packages/toolpad-core/src/nextjs/AppProvider.test.tsx
  packages/toolpad-core/src/nextjs/AppProvider.tsx
  packages/toolpad-core/src/nextjs/AppProviderNextApp.tsx
  packages/toolpad-core/src/nextjs/AppProviderNextPages.tsx
  packages/toolpad-core/src/nextjs/nextCompatRouter.ts
  packages/toolpad-core/src/nextjs/nextNavigation.ts
  packages/toolpad-core/src/nextjs/nextRouter.ts
  packages/toolpad-core/vitest.config.mts
  packages/toolpad-studio/package.json
  pnpm-lock.yaml
Labels: dependencies, priority: important, security

#4104 Fixes for docs and DashboardLayout component
  docs/data/toolpad/core/components/dashboard-layout/DashboardLayoutNavigationActions.js
  docs/data/toolpad/core/components/dashboard-layout/DashboardLayoutNavigationActions.tsx
  docs/data/toolpad/core/components/dashboard-layout/DashboardLayoutPattern.js
  docs/data/toolpad/core/components/dashboard-layout/DashboardLayoutPattern.tsx
  docs/data/toolpad/core/components/dashboard-layout/DashboardLayoutPattern.tsx.preview
  docs/data/toolpad/core/components/dashboard-layout/DashboardLayoutSlots.js
  docs/data/toolpad/core/components/dashboard-layout/DashboardLayoutSlots.tsx
  docs/data/toolpad/core/components/dashboard-layout/dashboard-layout.md
  packages/toolpad-core/src/AppProvider/AppThemeProvider.tsx
  packages/toolpad-core/src/DashboardLayout/DashboardLayout.test.tsx
  packages/toolpad-core/src/DashboardLayout/DashboardLayout.tsx
  packages/toolpad-core/src/shared/navigation.tsx
Labels: bug 🐛

#4080 [docs] Add integration, base concepts
  docs/data/toolpad/core/components/account/account.md
  docs/data/toolpad/core/components/app-provider/app-provider.md
  docs/data/toolpad/core/components/dashboard-layout/dashboard-layout.md
  docs/data/toolpad/core/components/page-container/page-container.md
  docs/data/toolpad/core/components/persistent-state/persistent-state.md
  docs/data/toolpad/core/components/sign-in-page/sign-in-page.md
  docs/data/toolpad/core/components/use-dialogs/use-dialogs.md
  docs/data/toolpad/core/components/use-notifications/use-notifications.md
  docs/data/toolpad/core/introduction/base-concepts.md
  docs/data/toolpad/core/introduction/installation.md
  docs/data/toolpad/core/introduction/integration.md
  docs/data/toolpad/core/pages.ts
  docs/pages/toolpad/core/introduction/base-concepts.js
  docs/pages/toolpad/core/introduction/integration.js
  docs/public/static/toolpad/docs/core/integration-nextjs-app-dark.png
  docs/public/static/toolpad/docs/core/integration-nextjs-app.png
  docs/public/static/toolpad/docs/core/integration-nextjs-pages-dark.png
  docs/public/static/toolpad/docs/core/integration-nextjs-pages.png
  playground/nextjs-pages/src/auth.ts
  pnpm-lock.yaml
Labels: docs

#4127 V0.7.0
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/create-toolpad-app/package.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-core/package.json
  packages/toolpad-studio-components/package.json
  packages/toolpad-studio-runtime/package.json
  packages/toolpad-studio/package.json
  packages/toolpad-utils/package.json
  playground/nextjs-pages/package.json
  playground/nextjs/package.json
  test/package.json
Labels: release

#4143 [PageContainer] Rename breadCrumbs to breadcrumbs
  docs/data/toolpad/core/components/page-container/CustomPageContainer.js
  docs/data/toolpad/core/components/page-container/CustomPageContainer.tsx
  docs/data/toolpad/core/components/page-container/CustomPageContainer.tsx.preview
  docs/data/toolpad/core/components/page-container/page-container.md
  docs/pages/toolpad/core/api/page-container.json
  docs/translations/api-docs/page-container/page-container.json
  packages/toolpad-core/src/PageContainer/PageContainer.test.tsx
  packages/toolpad-core/src/PageContainer/PageContainer.tsx
  packages/toolpad-core/src/useActivePage/useActivePage.ts
  packages/toolpad-utils/src/warnOnce.ts
Labels: enhancement, component: PageContainer

#4152 [code-infra] remove e identifier
  docs/src/components/landing-studio/CodeBlock.js
  packages/toolpad-core/src/useDialogs/useDialogs.tsx
  packages/toolpad-studio/src/server/appServerWorker.ts
  packages/toolpad-studio/src/toolpadDataSources/googleSheets/server.ts
Labels: scope: code-infra

#4171 [core] Increase the minimum Node.js version support to 14.0.0
  .browserslistrc
Labels: core, breaking change

#4154 [code-infra] Remove custom playwright installation steps
  .circleci/config.yml
Labels: scope: code-infra

#4157 [FIX] docs: input.label in SlotsSignIn
  docs/data/toolpad/core/components/sign-in-page/SlotsSignIn.js
  docs/data/toolpad/core/components/sign-in-page/SlotsSignIn.tsx
Labels: docs
