Repository mui/toolpad, pull requests merged in 2024-07, with the labels that each got.

#3696 [core] Implement persistent state hooks
  docs/data/toolpad/core/components/persistent-state/LocalStorageStateCustom.js
  docs/data/toolpad/core/components/persistent-state/LocalStorageStateCustom.tsx
  docs/data/toolpad/core/components/persistent-state/LocalStorageStateCustom.tsx.preview
  docs/data/toolpad/core/components/persistent-state/LocalStorageStateError.js
  docs/data/toolpad/core/components/persistent-state/LocalStorageStateError.tsx
  docs/data/toolpad/core/components/persistent-state/LocalStorageStateError.tsx.preview
  docs/data/toolpad/core/components/persistent-state/LocalStorageStateString.js
  docs/data/toolpad/core/components/persistent-state/LocalStorageStateString.tsx
  docs/data/toolpad/core/components/persistent-state/LocalStorageStateString.tsx.preview
  docs/data/toolpad/core/components/persistent-state/LocalStorageStateZod.js
  docs/data/toolpad/core/components/persistent-state/LocalStorageStateZod.tsx
  docs/data/toolpad/core/components/persistent-state/LocalStorageStateZod.tsx.preview
  docs/data/toolpad/core/components/persistent-state/persistent-state.md
  docs/data/toolpad/core/components/persistent-state/use-local-storage-state-api.md
  docs/data/toolpad/core/components/persistent-state/use-session-storage-state-api.md
  docs/data/toolpad/core/pages.ts
  docs/package.json
  docs/pages/toolpad/core/react-persistent-state/index.js
  docs/pages/toolpad/core/react-persistent-state/use-local-storage-state-api.js
  docs/pages/toolpad/core/react-persistent-state/use-session-storage-state-api.js
  packages/toolpad-core/src/index.ts
  packages/toolpad-core/src/persistence/codec.tsx
  packages/toolpad-core/src/persistence/index.ts
  packages/toolpad-core/src/persistence/useStorageState.test.tsx
  packages/toolpad-core/src/persistence/useStorageState.tsx
  packages/toolpad-core/src/useLocalStorageState/index.ts
  packages/toolpad-core/src/useLocalStorageState/useLocalStorageState.tsx
  packages/toolpad-core/src/useSearchParamState/index.ts
  packages/toolpad-core/src/useSessionStorageState/index.tsx
  packages/toolpad-core/src/useSessionStorageState/useSessionStorageState.tsx
  pnpm-lock.yaml
Labels: core, new feature

#3751 [code-infra] Use `@mui/docs` where possible
  docs/data/toolpad/studio/landing/pricing.js
  docs/package.json
  docs/src/components/landing/CodeBlock.js
  docs/src/modules/components/SchemaReference.tsx
  pnpm-lock.yaml
Labels: core, scope: code-infra, scope: docs-infra

#3754 Remove dead code
  packages/toolpad-studio/src/canvas/BridgeContext.ts
  packages/toolpad-studio/src/canvas/ToolpadBridge.tsx
  packages/toolpad-studio/src/canvas/index.tsx
  packages/toolpad-studio/src/toolpad/AppEditor/PageEditor/EditorCanvasHost.tsx
  packages/toolpad-studio/src/toolpad/AppEditor/PageEditor/RenderPanel/RenderOverlay.tsx
  packages/toolpad-studio/src/toolpad/AppEditor/PageEditor/RenderPanel/RenderPanel.tsx
Labels: core

#3755 [core] Optimize studio production build
  packages/toolpad-studio/src/server/toolpadAppBuilder.ts
Labels: core

#3756 [core] Fix a few performance issues in Toolpad production apps
  packages/toolpad-studio/package.json
  packages/toolpad-studio/src/runtime/constants.ts
  packages/toolpad-studio/src/server/index.ts
  packages/toolpad-studio/src/server/toolpadAppBuilder.ts
  packages/toolpad-studio/src/toolpad/AppEditor/PageEditor/EditorCanvasHost.tsx
  pnpm-lock.yaml
Labels: core

#3749 [cli] Add information when `--example` is present
  packages/create-toolpad-app/src/examples.ts
Labels: create-toolpad-app

#3753 [docs] Update to match monorepo script
  RELEASE.md
Labels: docs

#3757 [security] Slightly improve CSP header
  packages/toolpad-studio/src/server/index.ts
  test/integration/deploy/index.spec.ts
  test/playwright.config.ts
Labels: security, scope: toolpad-studio

#3774 v0.3.1
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/create-toolpad-app/package.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-core/package.json
  packages/toolpad-studio-components/package.json
  packages/toolpad-studio-runtime/package.json
  packages/toolpad-studio/package.json
  packages/toolpad-utils/package.json
  playground/nextjs-pages/package.json
  playground/nextjs/package.json
  test/package.json
Labels: release

#3790 [docs] Migrate Grid2 in the docs to fix landing page layout
  docs/src/components/landing/CardGrid.js
  docs/src/components/landing/UseCases.js
Labels: docs

#3789 [docs] Improve changelog format
  RELEASE.md
Labels: docs

#3796 [core] Remove lib dom from create-toolpad-app
  packages/create-toolpad-app/src/examples.ts
  packages/create-toolpad-app/tsconfig.json
Labels: core

#3803 [docs] Add tabs example
  examples/tabs/README.md
  examples/tabs/package.json
  examples/tabs/toolpad/.gitignore
  examples/tabs/toolpad/application.yml
  examples/tabs/toolpad/pages/Tabs/page.yml
  packages/toolpad-studio/src/runtime/ToolpadApp.tsx
Labels: docs

#3750 [core] Make DashboardLayout navigation responsive
  docs/data/toolpad/core/components/app-provider/AppProviderBasic.js
  docs/data/toolpad/core/components/app-provider/AppProviderBasic.tsx
  docs/data/toolpad/core/components/app-provider/AppProviderBasic.tsx.preview
  docs/data/toolpad/core/components/app-provider/AppProviderTheme.js
  docs/data/toolpad/core/components/app-provider/AppProviderTheme.tsx
  docs/data/toolpad/core/components/dashboard-layout/DashboardLayoutBasic.js
  docs/data/toolpad/core/components/dashboard-layout/DashboardLayoutBasic.tsx
  docs/data/toolpad/core/components/dashboard-layout/DashboardLayoutBasic.tsx.preview
  docs/data/toolpad/core/components/dashboard-layout/DashboardLayoutBranding.js
  docs/data/toolpad/core/components/dashboard-layout/DashboardLayoutBranding.tsx
  docs/data/toolpad/core/components/dashboard-layout/DashboardLayoutBranding.tsx.preview
  docs/data/toolpad/core/components/dashboard-layout/DashboardLayoutNavigation.js
  docs/data/toolpad/core/components/dashboard-layout/DashboardLayoutNavigation.tsx
  docs/data/toolpad/core/components/dashboard-layout/DashboardLayoutNavigation.tsx.preview
  docs/data/toolpad/core/introduction/TutorialDefault.js
  docs/data/toolpad/core/introduction/TutorialDefault.tsx
  docs/data/toolpad/core/introduction/TutorialPages.js
  docs/data/toolpad/core/introduction/TutorialPages.tsx
  packages/toolpad-core/src/AppProvider/AppProvider.tsx
  packages/toolpad-core/src/AppProvider/AppThemeProvider.tsx
  packages/toolpad-core/src/DashboardLayout/DashboardLayout.tsx
  packages/toolpad-core/src/shared/context.ts
  packages/toolpad-core/vitest.config.mts
Labels: feature: Components, enhancement, mobile

#3810 v0.3.2
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/create-toolpad-app/package.json
  packages/create-toolpad-app/src/generateProject.ts
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-core/package.json
  packages/toolpad-studio-components/package.json
  packages/toolpad-studio-runtime/package.json
  packages/toolpad-studio/package.json
  packages/toolpad-utils/package.json
  playground/nextjs-pages/package.json
  playground/nextjs/package.json
  test/package.json
Labels: release

#3690 [website] Add Toolpad core landing page
  docs/package.json
  docs/pages/toolpad-studio/index.js
  docs/pages/toolpad/index.js
  docs/public/static/toolpad/marketing/nextjs-icon-svgrepo-com.svg
  docs/public/static/toolpad/marketing/react-svgrepo-com.svg
  docs/public/static/toolpad/marketing/typescript-svgrepo-com.svg
  docs/src/components/landing-core/BuiltWith.js
  docs/src/components/landing-core/Examples.js
  docs/src/components/landing-core/Features.js
  docs/src/components/landing-core/GetStartedButtons.js
  docs/src/components/landing-core/Hero.js
  docs/src/components/landing-core/StudioIntro.js
  docs/src/components/landing-core/ToolpadDashboardLayout.tsx
  docs/src/components/landing-core/ToolpadDialogDemo.tsx
  docs/src/components/landing-core/ToolpadFeaturesSwitcher.tsx
  docs/src/components/landing-core/ToolpadNotificationDemo.tsx
  docs/src/modules/components/DemoSandbox.js
  docs/src/modules/components/Frame.tsx
  package.json
  pnpm-lock.yaml
Labels: website

#3813 [core] Fix create-toolpad-app content margin
  packages/create-toolpad-app/src/generateProject.ts
Labels: bug 🐛

#3809 [core] Fix theming bugs
  packages/toolpad-core/package.json
  packages/toolpad-core/src/AppProvider/AppThemeProvider.tsx
  packages/toolpad-core/src/DashboardLayout/DashboardLayout.tsx
  pnpm-lock.yaml
Labels: bug 🐛

#3829 Fix mobile menu in landing page
  docs/src/components/landing-core/ToolpadDashboardLayout.tsx
Labels: bug 🐛

#3825 [core] OOM issues during build
  package.json
  packages/toolpad-studio-components/package.json
  packages/toolpad-studio-components/src/Autocomplete.tsx
  packages/toolpad-studio-components/src/Chart.tsx
  packages/toolpad-studio-components/src/Form.tsx
  packages/toolpad-studio-components/src/Image.tsx
  packages/toolpad-studio-components/src/List.tsx
  packages/toolpad-studio-components/src/Paper.tsx
  packages/toolpad-studio-components/src/Select.tsx
  packages/toolpad-studio-components/src/Text.tsx
  packages/toolpad-studio-components/tsup.config.ts
  packages/toolpad-studio/src/components/CenteredSpinner.tsx
  packages/toolpad-studio/src/components/Devtools.tsx
  packages/toolpad-studio/src/components/EditableText.tsx
  packages/toolpad-studio/src/components/EditableTreeItem.tsx
  packages/toolpad-studio/src/components/HelpTooltipIcon.tsx
  packages/toolpad-studio/src/toolpad/AppEditor/QueryIcon.tsx
  packages/toolpad-studio/src/toolpad/AppEditor/UpgradeNotification.tsx
  packages/toolpad-studio/src/toolpad/propertyControls/DataProviderSelector.tsx
  packages/toolpad-studio/src/toolpadDataSources/QueryPreview.tsx
  packages/toolpad-utils/tsup.config.ts
Labels: core

#3828 Bring back studio landing page
  docs/pages/toolpad-studio/index.js
  docs/pages/toolpad/core/index.js
  docs/pages/toolpad/index.js
Labels: docs

#3794 [core] Tweak navigation API
  docs/data/toolpad/core/components/app-provider/AppProviderBasic.js
  docs/data/toolpad/core/components/app-provider/AppProviderBasic.tsx
  docs/data/toolpad/core/components/dashboard-layout/DashboardLayoutBasic.js
  docs/data/toolpad/core/components/dashboard-layout/DashboardLayoutBasic.tsx
  docs/data/toolpad/core/components/dashboard-layout/DashboardLayoutBranding.js
  docs/data/toolpad/core/components/dashboard-layout/DashboardLayoutBranding.tsx
  docs/data/toolpad/core/components/dashboard-layout/DashboardLayoutNavigation.js
  docs/data/toolpad/core/components/dashboard-layout/DashboardLayoutNavigation.tsx
  docs/data/toolpad/core/components/dashboard-layout/DashboardLayoutNavigation.tsx.preview
  docs/data/toolpad/core/introduction/TutorialPages.js
  docs/data/toolpad/core/introduction/TutorialPages.tsx
  docs/data/toolpad/core/introduction/tutorial.md
  docs/pages/toolpad/core/api/app-provider.json
  packages/create-toolpad-app/src/generateProject.ts
  packages/toolpad-core/src/AppProvider/AppProvider.tsx
  packages/toolpad-core/src/DashboardLayout/DashboardLayout.test.tsx
  packages/toolpad-core/src/DashboardLayout/DashboardLayout.tsx
  packages/toolpad-core/src/internals/demo.tsx
  packages/toolpad-core/src/shared/Link.tsx
  packages/toolpad-core/src/shared/navigation.tsx
  packages/toolpad-core/tsconfig.json
  packages/toolpad-core/vitest.config.mts
  playground/nextjs/src/app/layout.tsx
Labels: core, scope: toolpad-core

#3830 [docs] Fix landing page warnings
  docs/package.json
  docs/pages/toolpad/core/index.js
  docs/scripts/formattedTSDemos.js
  docs/src/components/landing-core/Examples.js
  docs/src/components/landing-core/Features.js
  docs/src/components/landing-core/StudioIntro.js
  docs/src/components/landing-core/ToolpadDashboardLayout.tsx
  docs/src/components/landing/UseCases.js
  docs/src/modules/components/DemoSandbox.js
  pnpm-lock.yaml
  tsconfig.json
Labels: docs

#3832 [docs] Remove absolute url from get started button
  docs/src/components/landing-core/Examples.js
  docs/src/components/landing-core/Hero.js
Labels: docs

#3776 [DashboardLayout] Add navigation actions
  docs/data/toolpad/core/components/app-provider/AppProviderBasic.js
  docs/data/toolpad/core/components/app-provider/AppProviderBasic.tsx
  docs/data/toolpad/core/components/app-provider/AppProviderTheme.js
  docs/data/toolpad/core/components/app-provider/AppProviderTheme.tsx
  docs/data/toolpad/core/components/dashboard-layout/DashboardLayoutBasic.js
  docs/data/toolpad/core/components/dashboard-layout/DashboardLayoutBasic.tsx
  docs/data/toolpad/core/components/dashboard-layout/DashboardLayoutBranding.js
  docs/data/toolpad/core/components/dashboard-layout/DashboardLayoutBranding.tsx
  docs/data/toolpad/core/components/dashboard-layout/DashboardLayoutNavigationActions.js
  docs/data/toolpad/core/components/dashboard-layout/DashboardLayoutNavigationActions.tsx
  docs/data/toolpad/core/components/dashboard-layout/DashboardLayoutNavigationActions.tsx.preview
  docs/data/toolpad/core/components/dashboard-layout/DashboardLayoutNavigationItems.js
  docs/data/toolpad/core/components/dashboard-layout/DashboardLayoutNavigationItems.tsx
  docs/data/toolpad/core/components/dashboard-layout/DashboardLayoutNavigationItems.tsx.preview
  docs/data/toolpad/core/components/dashboard-layout/dashboard-layout.md
  docs/data/toolpad/core/introduction/TutorialPages.js
  docs/data/toolpad/core/introduction/TutorialPages.tsx
  docs/data/toolpad/core/introduction/overview.md
  docs/pages/toolpad/core/api/app-provider.json
  examples/core-tutorial/app/layout.tsx
  packages/toolpad-core/package.json
  packages/toolpad-core/src/AppProvider/AppProvider.tsx
  packages/toolpad-core/src/DashboardLayout/DashboardLayout.test.tsx
  packages/toolpad-core/src/DashboardLayout/DashboardLayout.tsx
  packages/toolpad-core/src/nextjs/AppProvider.test.tsx
  playground/nextjs-pages/src/pages/_app.tsx
  playground/nextjs/src/app/layout.tsx
Labels: feature: Components

#3837 [docs] Fix theme switcher in Toolpad Core landing page
  packages/create-toolpad-app/src/generateProject.ts
  packages/toolpad-core/src/AppProvider/AppThemeProvider.tsx
  playground/nextjs-pages/src/pages/_document.tsx
  playground/nextjs/src/app/layout.tsx
Labels: bug 🐛

#3713 [core] Add PageContainer component
  docs/data/toolpad/core/components/page-container/ActionsPageContainer.js
  docs/data/toolpad/core/components/page-container/ActionsPageContainer.tsx
  docs/data/toolpad/core/components/page-container/ActionsPageContainer.tsx.preview
  docs/data/toolpad/core/components/page-container/BasicPageContainer.js
  docs/data/toolpad/core/components/page-container/BasicPageContainer.tsx
  docs/data/toolpad/core/components/page-container/BasicPageContainer.tsx.preview
  docs/data/toolpad/core/components/page-container/PageContent.js
  docs/data/toolpad/core/components/page-container/PageContent.tsx
  docs/data/toolpad/core/components/page-container/TitleBreadcrumbsPageContainer.js
  docs/data/toolpad/core/components/page-container/TitleBreadcrumbsPageContainer.tsx
  docs/data/toolpad/core/components/page-container/TitleBreadcrumbsPageContainer.tsx.preview
  docs/data/toolpad/core/components/page-container/page-container.md
  docs/data/toolpad/core/introduction/TutorialDefault.js
  docs/data/toolpad/core/introduction/TutorialDefault.tsx
  docs/data/toolpad/core/introduction/TutorialDefault.tsx.preview
  docs/data/toolpad/core/introduction/TutorialPages.js
  docs/data/toolpad/core/introduction/TutorialPages.tsx
  docs/data/toolpad/core/introduction/TutorialPages.tsx.preview
  docs/data/toolpad/core/introduction/tutorial.md
  docs/data/toolpad/core/pages.ts
  docs/data/toolpad/core/pagesApi.js
  docs/package.json
  docs/pages/toolpad/core/api/page-container-toolbar.js
  docs/pages/toolpad/core/api/page-container-toolbar.json
  docs/pages/toolpad/core/api/page-container.js
  docs/pages/toolpad/core/api/page-container.json
  docs/pages/toolpad/core/react-page-container/index.js
  docs/src/components/landing-core/Features.js
  docs/src/components/landing-core/ToolpadDashboardLayout.tsx
  docs/src/components/landing-core/ToolpadPageContainerDemo.tsx
  docs/translations/api-docs/page-container-toolbar/page-container-toolbar.json
  docs/translations/api-docs/page-container/page-container.json
  packages/create-toolpad-app/src/generateProject.ts
  packages/toolpad-core/src/DashboardLayout/DashboardLayout.tsx
  packages/toolpad-core/src/PageContainer/PageContainer.test.tsx
  packages/toolpad-core/src/PageContainer/PageContainer.tsx
  packages/toolpad-core/src/PageContainer/PageContainerToolbar.test.tsx
  packages/toolpad-core/src/PageContainer/PageContainerToolbar.tsx
  packages/toolpad-core/src/PageContainer/index.ts
  packages/toolpad-core/src/index.ts
  packages/toolpad-core/src/shared/branding.ts
  playground/nextjs/src/app/(dashboard)/layout.tsx
  playground/nextjs/src/app/(dashboard)/orders/page.tsx
  playground/nextjs/src/app/(dashboard)/page.tsx
  pnpm-lock.yaml
Labels: core

#3841 [release] v0.4.0
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/create-toolpad-app/package.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-core/package.json
  packages/toolpad-studio-components/package.json
  packages/toolpad-studio-runtime/package.json
  packages/toolpad-studio/package.json
  packages/toolpad-utils/package.json
  playground/nextjs-pages/package.json
  playground/nextjs/package.json
  pnpm-lock.yaml
  test/package.json
Labels: release

#3843 [cli] Upgrade `inquirer` to `@inquirer/prompts`
  package.json
  packages/create-toolpad-app/package.json
  packages/create-toolpad-app/src/index.ts
  pnpm-lock.yaml
Labels: create-toolpad-app
