Repository mui/toolpad, pull requests merged in 2024-02, with the labels that each got.

#3137 [code-infra] Avoid aliasing to the monorepo dependencies
  docs/babel.config.js
  docs/next.config.mjs
  docs/package.json
  pnpm-lock.yaml
Labels: docs

#3147 fix: "Unexpected token ';'" in expressions with trailing ';'
  packages/toolpad-app/src/toolpad/AppEditor/BindingEditor.tsx
Labels: enhancement

#3056 Authentication/authorization tests
  docs/schemas/v1/definitions.json
  packages/toolpad-app/src/runtime/SignInPage.tsx
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/runtime/useAuth.ts
  packages/toolpad-app/src/server/auth.ts
  packages/toolpad-app/src/server/httpApiAdapters.ts
  packages/toolpad-app/src/server/index.ts
  packages/toolpad-app/src/server/schema.ts
  packages/toolpad-app/src/server/toolpadAppServer.ts
  packages/toolpad-app/src/toolpad/AppEditor/AppAuthorizationEditor.tsx
  packages/toolpad-core/src/appDom.ts
  pnpm-lock.yaml
  test/integration/auth/domain.spec.ts
  test/integration/auth/fixture-domain/toolpad/.gitignore
  test/integration/auth/fixture-domain/toolpad/application.yml
  test/integration/auth/fixture-domain/toolpad/pages/mypage/page.yml
  test/integration/auth/fixture-domain/toolpad/resources/functions.ts
  test/integration/auth/fixture-roles/toolpad/.gitignore
  test/integration/auth/fixture-roles/toolpad/application.yml
  test/integration/auth/fixture-roles/toolpad/pages/adminpage/page.yml
  test/integration/auth/fixture-roles/toolpad/pages/publicpage/page.yml
  test/integration/auth/fixture-roles/toolpad/resources/functions.ts
  test/integration/auth/roles.spec.ts
  test/integration/auth/shared.ts
Labels: test

#3067 Add authorization docs
  docs/data/pages.ts
  docs/data/toolpad/concepts/authentication.md
  docs/data/toolpad/concepts/rbac.md
  docs/pages/toolpad/concepts/authentication.js
  docs/pages/toolpad/concepts/rbac.js
  docs/public/static/toolpad/docs/concepts/authorization/authentication-settings.png
  docs/public/static/toolpad/docs/concepts/authorization/azure-ad-redirect-url.png
  docs/public/static/toolpad/docs/concepts/authorization/azure-ad-roles.png
  docs/public/static/toolpad/docs/concepts/authorization/github-callback-url.png
  docs/public/static/toolpad/docs/concepts/authorization/google-redirect-url.png
  docs/public/static/toolpad/docs/concepts/authorization/restricting-pages.png
  docs/public/static/toolpad/docs/concepts/authorization/role-mapping-settings.png
  docs/public/static/toolpad/docs/concepts/authorization/roles-settings.png
  docs/public/static/toolpad/docs/concepts/authorization/sign-in-page.png
  packages/toolpad-app/src/constants.ts
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/PageOptionsPanel.tsx
  packages/toolpad-app/src/toolpad/Toolpad.tsx
Labels: docs

#3148 Improve package layout
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
  packages/toolpad-core/public/serverModules.d.ts
  packages/toolpad-core/src/server.ts
  packages/toolpad-core/tsconfig.json
  packages/toolpad-utils/package.json
Labels: core

#3156 [core] [docs] Add warnings, docs and gating for paid features
  docs/data/pages.ts
  docs/data/toolpad/getting-started/roadmap.md
  docs/schemas/v1/definitions.json
  packages/toolpad-app/src/constants.ts
  packages/toolpad-app/src/server/index.ts
  packages/toolpad-app/src/server/localMode.ts
  packages/toolpad-app/src/server/schema.ts
  packages/toolpad-app/src/toolpad/AppEditor/AppAuthorizationEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/PageOptionsPanel.tsx
  packages/toolpad-app/src/toolpad/AppEditor/UpgradeAlert.tsx
  packages/toolpad-core/src/appDom.ts
  test/integration/auth/fixture-roles/toolpad/application.yml
Labels: docs, enhancement, dx

#3173 Fix a few react-resizable-panels warnings
  packages/toolpad-app/src/toolpad/AppEditor/PagePanel.tsx
Labels: enhancement

#3170 Add isCanvas into app host context
  packages/toolpad-app/src/canvas/index.tsx
  packages/toolpad-app/src/runtime/AppHostContext.tsx
  packages/toolpad-app/src/runtime/ToolpadApp.spec.tsx
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/runtime/index.tsx
  packages/toolpad-app/src/runtime/useAuth.ts
Labels: core

#3174 Authentication fixes/improvements
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/runtime/useAuth.ts
  packages/toolpad-app/src/server/auth.ts
  packages/toolpad-app/src/server/index.ts
Labels: bug 🐛

#3185 Add pie chart future component
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentCatalog/ComponentCatalog.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentCatalog/ComponentCatalogItem.tsx
Labels: enhancement

#3171 [core] Add canvas mode that doesn't rely on vite
  packages/toolpad-app/package.json
  packages/toolpad-app/src/canvas/ToolpadBridge.tsx
  packages/toolpad-app/src/canvas/index.tsx
  packages/toolpad-app/src/components/FlexFill.tsx
  packages/toolpad-app/src/components/Pre.tsx
  packages/toolpad-app/src/components/resizablePanels.tsx
  packages/toolpad-app/src/entrypoint.tsx
  packages/toolpad-app/src/exports/editor.tsx
  packages/toolpad-app/src/exports/entrypoint.ts
  packages/toolpad-app/src/runtime/AppHostContext.tsx
  packages/toolpad-app/src/runtime/CanvasHooksContext.tsx
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/runtime/api.ts
  packages/toolpad-app/src/runtime/index.tsx
  packages/toolpad-app/src/runtime/useDataProvider.ts
  packages/toolpad-app/src/runtime/useDataQuery.ts
  packages/toolpad-app/src/server/appServerWorker.ts
  packages/toolpad-app/src/server/index.ts
  packages/toolpad-app/src/server/toolpadAppBuilder.ts
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/EditorCanvasHost.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/EditorCanvasHostInline.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/RenderPanel.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PagePanel.tsx
  packages/toolpad-app/src/toolpad/Toolpad.tsx
  packages/toolpad-app/src/toolpad/vite.config.mts
  packages/toolpad-app/tsup.config.ts
  pnpm-lock.yaml
  test/utils/page.ts
Labels: core

#3188 Fix project loading several times
  packages/toolpad-app/src/project.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/EditorCanvasHostInline.tsx
  packages/toolpad-app/src/toolpad/Toolpad.tsx
Labels: core

#3187 Fix editable tree item bugs
  packages/toolpad-app/src/components/EditableTreeItem.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PagesExplorer/index.tsx
  test/integration/duplication/index.spec.ts
  test/integration/editor/new.spec.ts
  test/integration/pages/index.spec.ts
  test/integration/undo-redo/multiple-pages.spec.ts
Labels: bug 🐛

#3157 Add authenticated session to app server context
  docs/data/toolpad/concepts/custom-functions.md
  docs/data/toolpad/reference/api/get-context.md
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/runtime/useAuth.ts
  packages/toolpad-app/src/server/DataManager.ts
  packages/toolpad-app/src/server/auth.ts
  packages/toolpad-app/src/server/rpc.ts
  packages/toolpad-core/package.json
  packages/toolpad-core/src/auth.ts
  packages/toolpad-core/src/serverRuntime.ts
  packages/toolpad-core/tsconfig.json
  packages/toolpad-core/typings/@auth.d.ts
  packages/toolpad-utils/package.json
  packages/toolpad-utils/src/httpApiAdapters.ts
  pnpm-lock.yaml
  test/integration/auth/domain.spec.ts
  test/integration/auth/fixture-domain/toolpad/pages/mypage/page.yml
  test/integration/auth/fixture-domain/toolpad/resources/functions.ts
Labels: docs, feature: Queries

#3191 Fix undo/redo in new canvas implementation
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/EditorCanvasHostInline.tsx
Labels: core

#3192 Correct test urls for canvas tests
  test/integration/duplication/index.spec.ts
  test/integration/editor/deleteLast.spec.ts
Labels: core

#3193 Fix test for code components under new editor runtime
  test/integration/codeComponents/index.spec.ts
  test/models/ToolpadRuntime.ts
Labels: test

#3194 Create predictably named test directories
  test/playwright/localTest.ts
Labels: core

#3189 Fix vm shim in the editor
  packages/toolpad-app/src/server/toolpadAppBuilder.ts
Labels: core

#3210 Remove semicolon from jsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/QueriesExplorer/index.tsx
Labels: enhancement

#3208 Make sure the inline canvas uses the correct font
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/EditorCanvasHostInline.tsx
Labels: core

#3135 Add authentication examples
  CONTRIBUTING.md
  docs/public/static/toolpad/marketing/auth-github.png
  docs/public/static/toolpad/marketing/auth-google.png
  docs/src/modules/components/ExamplesGrid.js
  examples/auth-github/.env.example
  examples/auth-github/README.md
  examples/auth-github/package.json
  examples/auth-github/toolpad/.gitignore
  examples/auth-github/toolpad/application.yml
  examples/auth-github/toolpad/pages/protectedpage/page.yml
  examples/auth-google/.env.example
  examples/auth-google/README.md
  examples/auth-google/package.json
  examples/auth-google/toolpad/.gitignore
  examples/auth-google/toolpad/application.yml
  examples/auth-google/toolpad/pages/protectedpage/page.yml
Labels: docs

#3207 Reroute "open in editor" link in app preview
  packages/toolpad-app/src/exports/editor.tsx
  packages/toolpad-app/src/runtime/PreviewHeader.tsx
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/runtime/globalState.ts
  packages/toolpad-app/src/runtime/index.tsx
  packages/toolpad-app/src/server/appServerWorker.ts
  packages/toolpad-app/src/server/index.ts
  packages/toolpad-app/src/server/toolpadAppBuilder.ts
  packages/toolpad-app/src/toolpad/Toolpad.tsx
  packages/toolpad-app/src/toolpad/propertyControls/ToggleButtons.tsx
  packages/toolpad-app/src/utils/domView.ts
  test/integration/custom-server/dev.spec.ts
Labels: core

#3214 Add documentation about installing Toolpad in an existing project
  docs/data/toolpad/concepts/custom-server.md
  docs/data/toolpad/getting-started/installation.md
Labels: docs

#3217 [code-infra] Deprecate usage of the next export command
  docs/next.config.mjs
  docs/package.json
  netlify.toml
  package.json
  pnpm-lock.yaml
  renovate.json
Labels: scope: code-infra

#3215 Show save/discard for created record when updateRecords is unavailable
  packages/toolpad-components/src/DataGrid.tsx
Labels: bug 🐛

#3218 v0.1.50
  CHANGELOG.md
  docs/package.json
  lerna.json
  packages/create-toolpad-app/package.json
  packages/eslint-plugin-material-ui/package.json
  packages/toolpad-app/package.json
  packages/toolpad-components/package.json
  packages/toolpad-core/package.json
  packages/toolpad-utils/package.json
Labels: release 🚀

#3222 [code-infra] Use `experimental.cpus` to control amount of export workers in Next.js
  docs/next.config.mjs
Labels: scope: code-infra

#3224 [code-infra] Disable renovatebot semantic commits
  CHANGELOG.md
  renovate.json
Labels: scope: docs-infra

#3220 Prevent app header from covering page elements
  packages/toolpad-app/src/runtime/AppLayout.tsx
Labels: design: ui, design: ux

#3221 Fix unintentional page rows being created
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/RenderOverlay.tsx
  test/models/ToolpadEditor.ts
  test/visual/components/fixture/toolpad/components/FullWidth.tsx
  test/visual/components/fixture/toolpad/pages/blank/page.yml
  test/visual/components/index.spec.ts
Labels: bug 🐛

#3169 Show loading indicator when runtime config is loading in query editor
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/QueryEditor/QueryEditorPanel.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/QueryEditor/index.tsx
Labels: enhancement

#3133 [code-infra] Remove pnpm cache on CircleCI
  .circleci/config.yml
Labels: core

#3232 [code-infra] Bump monorepo
  docs/config.js
  docs/package.json
  docs/pages/_app.js
  docs/src/components/landing/Banner.js
  docs/src/components/landing/GetStartedButtons.js
  docs/src/components/landing/UseCases.js
  eslintWebpackResolverConfig.js
  package.json
  pnpm-lock.yaml
Labels: scope: code-infra

#2170 [examples] Hacker News client example
  docs/data/toolpad/reference/components/list.md
  examples/hacker-news-client/README.md
  examples/hacker-news-client/package.json
  examples/hacker-news-client/toolpad/.gitignore
  examples/hacker-news-client/toolpad/application.yml
  examples/hacker-news-client/toolpad/pages/hackernews/page.yml
  examples/hacker-news-client/toolpad/resources/functions.ts
  packages/toolpad-components/src/List.tsx
Labels: examples

#3114 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: docs

#3237 Make building layout visual tests more stable
  test/visual/components/index.spec.ts
Labels: test

#2818 Fix and improve resizing in editor (incl. Add Spacer component)
  docs/data/toolpad/reference/components/chart.md
  docs/data/toolpad/reference/components/data-grid.md
  docs/data/toolpad/reference/components/index.md
  docs/data/toolpad/reference/components/manifest.json
  docs/data/toolpad/reference/components/spacer.md
  docs/pages/toolpad/reference/components/spacer.js
  docs/schemas/v1/definitions.json
  packages/toolpad-app/src/runtime/ToolpadApp.tsx
  packages/toolpad-app/src/runtime/toolpadComponents/index.tsx
  packages/toolpad-app/src/server/localMode.ts
  packages/toolpad-app/src/server/schema.ts
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentCatalog/ComponentCatalogItem.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/ComponentEditor.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/NodeDropArea.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/NodeHud.tsx
  packages/toolpad-app/src/toolpad/AppEditor/PageEditor/RenderPanel/RenderOverlay.tsx
  packages/toolpad-app/src/toolpad/AppEditor/pageLayout.ts
  packages/toolpad-app/src/toolpad/AppEditor/toolpadComponents.tsx
  packages/toolpad-components/src/Chart.tsx
  packages/toolpad-components/src/DataGrid.tsx
  packages/toolpad-components/src/Spacer.tsx
  packages/toolpad-components/src/index.tsx
  packages/toolpad-core/src/appDom.ts
  packages/toolpad-core/src/types.ts
  test/models/ToolpadEditor.ts
  test/utils/locators.ts
  test/visual/components/fixture/toolpad/application.yml
  test/visual/components/fixture/toolpad/pages/blank/page.yml
  test/visual/components/fixture/toolpad/pages/components/page.yml
  test/visual/components/fixture/toolpad/pages/dragdrop/page.yml
  test/visual/components/fixture/toolpad/pages/grids/page.yml
  test/visual/components/fixture/toolpad/pages/rows/page.yml
  test/visual/components/fixture/toolpad/pages/text/page.yml
  test/visual/components/index.spec.ts
Labels: bug 🐛, feature: App Editor

#3211 Add a data providers CRUD page to basic crud app example
  examples/basic-crud-app/toolpad/application.yml
  examples/basic-crud-app/toolpad/pages/AdminApp/page.yml
  examples/basic-crud-app/toolpad/pages/AdminApp1/page.yml
  examples/basic-crud-app/toolpad/resources/dataProvider.ts
  packages/toolpad-components/src/DataGrid.tsx
Labels: examples

#3254 [core] add engines field to @mui/toolpad package.json
  packages/toolpad-app/package.json
Labels: enhancement

#3255 Add some missing docs for the hasNextPage property
  docs/data/toolpad/reference/api/create-data-provider.md
Labels: docs

#3253 Stabilize visual regression tests
  test/visual/components/index.spec.ts
Labels: test

#3234 [docs-infra] Fixes for vale-action with shared config
  .github/styles/Vocab/accept.txt
  .gitignore
  .vale.ini
Labels: scope: docs-infra

#3256 Image error overlay fixes
  packages/toolpad-components/src/components/ErrorOverlay.tsx
  test/visual/components/fixture/toolpad/pages/components/page.yml
Labels: enhancement, breaking change

#3257 Add scroll fixes to DataGrid skeleton loading
  packages/toolpad-components/src/DataGrid.tsx
Labels: enhancement

#2690 Global functions explorer and header
  packages/toolpad-app/src/components/EditableTreeItem.tsx
  packages/toolpad-app/src/toolpad/AppEditor/ExplorerHeader.tsx
  packages/toolpad-app/src/toolpad/AppEditor/HierarchyExplorer/index.tsx
  packages/toolpad-app/src/toolpad/FunctionsEditor/index.tsx
  packages/toolpad-app/src/toolpad/OpenCodeEditor.tsx
  packages/toolpad-app/src/toolpad/Toolpad.tsx
  packages/toolpad-app/src/toolpad/ToolpadShell/ToolpadNavigation.tsx
Labels: new feature

#3260 Remove isInvalid prop from all components
  docs/data/toolpad/reference/components/autocomplete.md
  docs/data/toolpad/reference/components/checkbox.md
  docs/data/toolpad/reference/components/date-picker.md
  docs/data/toolpad/reference/components/file-picker.md
  docs/data/toolpad/reference/components/select.md
  docs/data/toolpad/reference/components/text-field.md
  examples/basic-crud-app/toolpad/pages/AdminApp/page.yml
  packages/toolpad-components/src/Autocomplete.tsx
  packages/toolpad-components/src/Checkbox.tsx
  packages/toolpad-components/src/DatePicker.tsx
  packages/toolpad-components/src/FilePicker.tsx
  packages/toolpad-components/src/Form.tsx
  packages/toolpad-components/src/Select.tsx
  packages/toolpad-components/src/TextField.tsx
  test/integration/components/fixture-form/toolpad/pages/form/page.yml
  test/integration/components/form.spec.ts
Labels: core

#3259 Update monorepo
  docs/package.json
  docs/pages/_app.js
  package.json
  pnpm-lock.yaml
  scripts/canaryMonorepo.ts
  scripts/gitUtils.ts
  scripts/tsconfig.json
  scripts/updateMonorepo.ts
Labels: core
